<div id="page-wrapper" class="bac_img">
	<div class="container-fluid">
		<div class="row page_lo">
			<div class="col-xs-2 col-md-4 text-left">
				<div class="btn_site"><a href="<?php echo $this->baseUrl; ?>summary-info">Upload Tax Documents</a></div>
			</div>  
			<div class="col-xs-10 col-md-8 text-right btn_pad">
				<div class="btn_site sm-hide">
					File Number: <?php if(isset($_SEESSION["user"]["file_name"]) && $_SEESSION["user"]["file_name"]!=""){ echo $_SEESSION["user"]["file_name"]; } else { ?> UTS0023 <?php } ?>
				</div>
				<div class="dropdown btn_site">
					<a class=" dropdown-toggle" data-toggle="dropdown"> Welcome <?php if(isset($_SEESSION["user"]["user_name"]) && $_SEESSION["user"]["user_name"]!=""){ echo ucfirst($_SEESSION["user"]["user_name"]); } else { ?> Dileep <?php } ?>   <span class="caret"></a>
					 <ul class="dropdown-menu">
						<li><a href="<?php echo $baseUrl;?>referral-list">Referral List</a></li>
						<li><a href="javascript:void(0);" onClick="changeQ();">Change Password</a></li>
						<li><a href="javascript:void(0);" onClick="logOutFun();">Logout</a></li>
					 </ul>
				</div>
			</div>
		</div>
		<div class="row mar_t20 bac_uplo" id="view_tax_documents">
			<?php if(count($this->taxDocuments) != 0){
				foreach($this->taxDocuments as $category=>$files){
			?>
				<div class="col-lg-6 ">
					<div class="table-responsive">
						<table class="table	">
							<tbody>
								<?php foreach($files as $file){ ?>
								<tr>
									<?php if($category =="P1099INT"){?>
										<th style="width:100%">1099INT</th>
									<?php }else{ ?>
										<th style="width:100%"><?php echo $category; ?></th>
									<?php } ?>									
									<td style="width:100%"><a href="<?php echo $this->baseUrl.'uploads/'.$this->user_id.'/'.$category.'/'.$file; ?>" download><?php echo $file; ?></a></td>
								</tr>
								<?php } ?>
							</tbody>
						</table>
					</div>
				</div>
			<?php }}else{ ?>
				<div class="col-lg-6 ">
					<div class="table-responsive">
						<i>Documents are not available</i>
					</div>
				</div>
			<?php } ?>
			<div class="col-lg-12 label_col">
				<div class="pull-right">
					<button type="button" class="btn btn-warning btn-md" onclick="showTaxUploads(2)">EDIT</button>
					<!--<button type="button" class="btn btn-success btn-md">SUBMIT</button>-->
				</div>
			</div>
		</div>
		<div id="edit_tax_documents" style="display:none">
			<form id="taxDocumentsForm" name="dependentsForm" method="POST" enctype="multipart/form-data" data-fv-message="This value is not valid"
			data-fv-icon-valid="glyphicon glyphicon-ok"
			data-fv-icon-invalid="glyphicon glyphicon-remove"
			data-fv-icon-validating="glyphicon glyphicon-refresh">
				<div class="row mar_t20">
					<?php if(count($this->categories) != 0){
						foreach($this->categories as $name){
					?>
					<div class="col-lg-6 label_col">
						<div class="form-group" style="background:#ddd;width:100%;padding:6px;border-radius:5px;">
							<label style="color:#111;margin-top:4px;">
							<?php if($name->upt_name=='P1099INT'){ ?>
							1099INT :
							<?php } else {?>
							<?php echo $name->upt_name; ?> :
							<?php } ?>
							</label>
						</div>
						<?php if(isset($this->taxDocuments[$name->upt_name]) && count($this->taxDocuments[$name->upt_name]) != 0){
							foreach($this->taxDocuments[$name->upt_name] as $fileId => $file){
						?>
							
							<div class="form-group">
								<div class="col-lg-6">
									<p id="existsFile_<?php echo $fileId; ?>"><a style="color:#fff !important" href="<?php echo $this->baseUrl.'uploads/'.$this->user_id.'/'.$name->upt_name.'/'.$file; ?>" download><?php echo $file; ?> &nbsp;&nbsp; <a href="javascript:void(0);" style="color:#ff3349 !important;font-size:20px;padding-left:10px;" onclick="removeFile(<?php echo $fileId; ?>)"><span class="glyphicon glyphicon-trash"></span></a></p>
								</div>
							</div>
							<div class="clearfix"></div>
						<?php }} ?>
						<div class="form-group">
							<button type="button" class="btn btn-success btn-md" onclick="addMoreFiles(<?php echo $name->upt_id; ?>)">Add more</button>
						</div>
						<div class="col-lg-12" id="addMore_<?php echo $name->upt_id; ?>"></div>
					</div>
					<?php }} ?>
				</div>
				<div class="col-lg-12 label_col">
					<div class="pull-right">
						<button type="button" class="btn btn-warning btn-md" onclick="showTaxUploads(1)">VIEW</button>
						<button type="button" class="btn btn-success btn-md" onclick="submitTaxDocumentsForm();">SUBMIT</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<input type="hidden" id="filesCount" value="1">
<input type="hidden" id="hid_tax_file_id">
<div class="modal fade" id="confirm-remove-file" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
				<h3 class="modal-title" id="lineModalLabel">Confirmation</h3>
			</div>
			<div class="modal-body">
				<p>Oops! are you sure want to remove the record.</p>
			</div>
			<div class="modal-footer">
				<span id="loading_remove_file" style="display:none;" class="pull-left"><i>Loading...</i></span>
				<button type="button" class="btn btn-default" data-dismiss="modal"  role="button">Close</button>
				<button  type="button" class="btn btn-raised btn-info btn-sm" onclick="removeTaxFile()">Ok</button>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="warning-upload-files" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
				<h3 class="modal-title" id="lineModalLabel">Warnning</h3>
			</div>
			<div class="modal-body">
				<p>Oops! please upload atleat one file.</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal"  role="button">Close</button>
			</div>
		</div>
	</div>
</div>