<div id="page-wrapper" class="bac_img">
	<div class="container-fluid">
		<div class="row page_lo">
			<div class="col-xs-2 col-md-4 text-left">
				<div class="btn_site"><a href="<?php echo $this->baseUrl; ?>summary-info">View Tax Summary</a></div>
			</div>  
			<div class="col-xs-10 col-md-8 text-right btn_pad user_drop" >
				<div class="btn_site sm-hide">
					File Number: <?php if(isset($_SESSION["user"]["unique_code"]) && $_SESSION["user"]["unique_code"]!=""){ echo $_SESSION["user"]["unique_code"]; } else { ?> Not yet assigned <?php } ?>
				</div>
				<div class="dropdown btn_site" style="margin-bottom:10px;">
					<a class=" dropdown-toggle" data-toggle="dropdown"> Welcome <?php if(isset($_SESSION["user"]["user_name"]) && $_SESSION["user"]["user_name"]!=""){ echo ucfirst($_SESSION["user"]["user_name"]); } else { ?> User <?php } ?>   <span class="caret"></a>
					 <ul class="dropdown-menu">
						<li><a href="<?php echo $baseUrl;?>referral-list">Referral List</a></li>
						<li><a href="javascript:void(0);" onClick="changeQ();">Change Password</a></li>
						<li><a href="javascript:void(0);" onClick="logOutFun();">Logout</a></li>
					 </ul>
				</div>
			</div>
		</div>
		
		<div class="row mar_t20 bac_uplo" id="view_tax_documents">
			<?php if(count($this->taxSummary) != 0){ ?>
				<div class="col-lg-12">
					<div class="table-responsive">
						<table class="table	">
							<tbody>
								<?php foreach($this->taxSummary as $s){ ?>
								<tr>
									<th><?php echo $s->synopsys_title; ?></th>
									<td><a href="<?php echo $this->baseUrl.'synopsys/'.$s->synopsys_file; ?>" download><?php echo $s->synopsys_file; ?></a></td>
								</tr>
								<?php } ?>
							</tbody>
						</table>
					</div>
				</div>
			<?php }else{ ?>
				<div class="col-lg-6 ">
					<div class="table-responsive">
						<i>Documents are not available</i>
					</div>
				</div>
			<?php } ?>
		</div>
	</div>
</div>