<div class="content-wrapper">
		<div class="bredcrum_bg">
			<div class="container">
				<section class="content-header mar_t40">
					<h1 class="text-right">
						&nbsp;
					</h1>
					<ol class="breadcrumb">
						<li><a href="<?php echo $baseUrl;?>/home" class="color_a">Home</a></li>
						<li><a>About XDI</a></li>
					</ol>
				</section>
			</div>
		</div>
		<div class="container">
			<div class="title_heading pos_r mar_t40">
				<h1><span class="span_bg_g">XDI's Mission</span></h1>
				<div class="title_lines"></div>
			</div>
			<div class="text-center mar_b20">
				<p>To empower EA to continuously advance external development through invaluable industry leading services.</p>
			</div>
			<div class="row menuof_services">
			<div class="col-md-4 mmhide"></div>
				<div class="col-md-4 col-xs-6 text-center">
				<div class="" style="background:#06172d;border-radius:2px;border:1px solid #06172e">
					<a href="<?php echo $baseUrl;?>/menu-of-services" class="imglg"><img src="<?php echo $this->basePath; ?>/images/menu-of-service.png" class="img-responsive img_inline"/></a>
					<div style="padding:10px 0;border-top:1px solid #202f42" class="sm_hide"><a href="<?php echo $baseUrl;?>/menu-of-services" class="imglg text-uppercase">Click Here to View Menu of Services</a></div>
				</div>
				</div>
				<div class="col-md-4 col-xs-6 large_deskt_hide">
					<a href="mailto:XDIManagers@EA.com"><div class="text-center min_hs">
					<h1 class="font_sizexx"><i class="fa fa-envelope" aria-hidden="true"></i></h1>
					<h2>CONTACT  XDI</h2></div></a>
				</div>
				<div class="col-md-4 mmhide sm_hide"></div><div class="clearfix"></div>
				<div class="col-md-12 col-xs-6 mmhide sm_hide text-center mar_t10">
					<a href="mailto:XDIManagers@EA.com"><div class="text-center min_hs">
					<h1 class="font_sizexx"><i class="fa fa-envelope" aria-hidden="true"></i></h1>
					<h2>CONTACT  XDI</h2></div></a>
				</div>
			</div>
		</div>
		<!--<div class="text-center"><img src="<?php echo $this->basePath; ?>/images/menu.png" class="img-responsive img_inline"/></div>-->
		
	<!-- Community profiles -->
	<div class="container">
	<!--  XDI Team Members -->
		<div class="title_heading pos_r mar_t40">
			<h1><span class="span_bg_g"> XDI Team Members</span></h1>
			<div class="title_lines"></div>
			<div class="text-center mar_b30">
				<p>EA's External Development Intelligence team is a globally recognized leader advancing game industry external development through world-class knowledge, consulting, and events.</p>
			</div>
		</div>
	<!-- End -->
		<div class="mar_t20 pos_r">
				<div class="row outsourcing_sm" id="type_team_members_1">
					<?php 
						if($this->xdiUsers->count()){
							foreach($this->xdiUsers as $kx=>$xu){
								if($kx <= 5){
					?>
					<div class="col-md-4">
						<div class="community_bg">
							<div class="row">
								<div class="col-xs-2" >
								<?php
								if($xu->u_profile_image != ""){
									$pImagePath = $this->basePath.'/uploads/profiles/'.$xu->u_profile_image;
								}else{
									$pImagePath = $this->basePath.'/images/user_profile.png';
								}
								?>
								<img class="profile_pic" src="<?php echo $pImagePath; ?>"/>
								</div>
								<div class="col-xs-10">
								<a href="<?php echo $this->baseUrl; ?>/view-profile/<?php echo $xu->u_id; ?>"><b><?php echo $xu->u_first_name.' '.$xu->u_last_name; ?></b></a>
								<!--<p><span>Title:</span> <?php echo $xu->u_title; ?></p>-->
								<p><span>Team:</span> XDI Team</p>
								<p><span>Studio:</span> <?php echo $xu->st_name; ?></p>
								</div>
								<div class="col-xs-12"><p> <?php echo $xu->u_bio; ?> </p></div>
							</div>
						</div>
					</div>
					<?php }}}else{ ?>
					<div class="text-center">There are no team members.</div>
					<?php } ?>
				</div>
				<div class="col-md-4">&nbsp;</div>
				<?php if($this->xdiUsers->count() > 6){ ?>
				<div class="col-md-4 text-center mar_t20" id="expand_type_1">
					<a href="javascript:void(0);" onclick="aboutXdiUsers(1);" class="btn btn-primary btn-lg btn-block">Expand to see all( <b id="view_more_1"><?php echo $this->xdiUsers->count(); ?></b> )</a>
				</div>
				<?php } ?>
				<div class="col-md-4">&nbsp;</div>
		</div>
	</div>
	<!-- End -->
	
	
	<!-- Legal & Business Affairs profiles -->
	<div class="container">
	<!--  XDI Team Members -->
		<div class="title_heading pos_r mar_t40">
			<h1><span class="span_bg_g"> Legal & Business Affairs Business Partners</span></h1>
			<div class="title_lines"></div>
			<div class="text-center mar_b30">
				<p>Business Affairs and EA’s Legal Team work closely together to provide EA’s external development community with world class IP protection via their contract and negotiation services. They assist with partner diligence and ensure that EA game teams understand their legal obligations to partners.</p>
			</div>
		</div>
	<!-- End -->
		<div class="mar_t20 pos_r">
			<div class="row outsourcing_sm" id="type_team_members_2">
				<?php 
					if($this->LegalUsers->count()){
						foreach($this->LegalUsers as $kl=>$lu){
							if($kl <= 5){
				?>
				<div class="col-md-4">
					<div class="community_bg">
						<div class="row">
							<div class="col-xs-2" >
							<?php
							if($lu->u_profile_image != ""){
								$pImagePath = $this->basePath.'/uploads/profiles/'.$lu->u_profile_image;
							}else{
								$pImagePath = $this->basePath.'/images/user_profile.png';
							}
							?>
							<img class="profile_pic" src="<?php echo $pImagePath; ?>"/>
							</div>
							<div class="col-xs-10">
							<a href="<?php echo $this->baseUrl; ?>/view-profile/<?php echo $lu->u_id; ?>"><b><?php echo $lu->u_first_name.' '.$lu->u_last_name; ?></b></a>
							<!--<p><span>Title:</span> <?php echo $lu->u_title; ?></p>-->
							<p><span>Team:</span> Legal & Business Affairs Business Partner</p>
							<p><span>Studio:</span> <?php echo $lu->st_name; ?></p>
							</div>
							<div class="col-xs-12"><p> <?php echo $lu->u_bio; ?> </p></div>
						</div>
					</div>
				</div>
				<?php }}}else{ ?>
				<div class="text-center">There are no business partners.</div>
				<?php } ?>
			</div>
			<div class="col-md-4">&nbsp;</div>
			<?php if($this->LegalUsers->count() > 6){ ?>
			<div class="col-md-4 text-center mar_t20" id="expand_type_2">
				<a href="javascript:void(0);" onclick="aboutXdiUsers(2);" class="btn btn-primary btn-lg btn-block">Expand to see all( <b id="view_more_2"><?php echo $this->LegalUsers->count(); ?></b> ) </a>
			</div>
			<?php } ?>
			<div class="col-md-4">&nbsp;</div>
		</div>
	</div>
	<!-- End -->
	
	<!-- SRM profiles -->
	<div class="container">
	<!--  XDI Team Members -->
		<div class="title_heading pos_r mar_t40">
			<h1><span class="span_bg_g"> SRM Business Partners</span></h1>
			<div class="title_lines"></div>
			<div class="text-center mar_b30">
				<p>EA's Security & Risk Management team manages a Security Risk Assessment (SRA) program on behalf of EA. The goal of the program is to protect EA's commercial interests by reducing identified risks associated with entrusting external partners with intellectual property and sensitive assets. The SRA program provides EA with a global framework for conducting risk assessments. It is one of many programs that EA's SRM team provides.</p>
			</div>
		</div>
	<!-- End -->
		<div class="mar_t20 pos_r">
			<div class="row outsourcing_sm" id="type_team_members_3">
				<?php 
					if($this->srmUsers->count()){
						foreach($this->srmUsers as $ks=>$su){
							if($ks <= 5){
				?>
				<div class="col-md-4">
					<div class="community_bg">
						<div class="row">
							<div class="col-xs-2" >
							<?php
							if($su->u_profile_image != ""){
								$pImagePath = $this->basePath.'/uploads/profiles/'.$su->u_profile_image;
							}else{
								$pImagePath = $this->basePath.'/images/user_profile.png';
							}
							?>
							<img class="profile_pic" src="<?php echo $pImagePath; ?>"/>
							</div>
							<div class="col-xs-10">
							<a href="<?php echo $this->baseUrl; ?>/view-profile/<?php echo $su->u_id; ?>"><b><?php echo $su->u_first_name.' '.$su->u_last_name; ?></b></a>
							<!--<p><span>Title:</span> <?php echo $su->u_title; ?></p>-->
							<p><span>Team:</span> SRM Business Partner</p>
							<p><span>Studio:</span> <?php echo $su->st_name; ?></p>
							</div>
							<div class="col-xs-12"><p> <?php echo $su->u_bio; ?> </p></div>
						</div>
					</div>
				</div>
				<?php }}}else{ ?>
				<div class="text-center">There are no business partners.</div>
				<?php } ?>
			</div>
			<div class="col-md-4">&nbsp;</div>
			<?php if($this->srmUsers->count() > 6){ ?>
			<div class="col-md-4 text-center mar_t20" id="expand_type_3">
				<a href="javascript:void(0);" onclick="aboutXdiUsers(3);" class="btn btn-primary btn-lg btn-block">Expand to see all( <b id="view_more_3"><?php echo $this->srmUsers->count(); ?></b> ) </a>
			</div>
			<?php } ?>
			<div class="col-md-4">&nbsp;</div>
		</div>
	</div>
	<!-- End -->
	
	<!-- Distribute profiles -->
	<div class="container mar_b30">
	<!--  XDI Team Members -->
		<div class="title_heading pos_r mar_t40">
			<h1><span class="span_bg_g"> Distributed Development Business Partners</span></h1>
			<div class="title_lines"></div>
			<div class="text-center mar_b30">
				<p>EA’s Distributed Development team helps EA Teams with connectivity requests for our external partners. Examples of areas of support include; VPN tunnel set-up, Per Force and Jira access. It is this team’s goal to ensure EA teams have efficient pipelines in place with our external partners. </p>
			</div>
		</div>
	<!-- End -->
		<div class="mar_t20 pos_r">
			<div class="row outsourcing_sm" id="type_team_members_4">
				<?php 
					if($this->distributeUsers->count()){
						foreach($this->distributeUsers as $kd=>$du){
							if($kd <= 5){
				?>
				<div class="col-md-4">
					<div class="community_bg">
						<div class="row">
							<div class="col-xs-2" >
							<?php
							if($du->u_profile_image != ""){
								$pImagePath = $this->basePath.'/uploads/profiles/'.$du->u_profile_image;
							}else{
								$pImagePath = $this->basePath.'/images/user_profile.png';
							}
							?>
							<img class="profile_pic" src="<?php echo $pImagePath; ?>"/>
							</div>
							<div class="col-xs-10">
							<a href="<?php echo $this->baseUrl; ?>/view-profile/<?php echo $du->u_id; ?>"><b><?php echo $du->u_first_name.' '.$du->u_last_name; ?></b></a>
							<!--<p><span>Title:</span> <?php echo $du->u_title; ?></p>-->
							<p><span>Team:</span> Distributed Development Business Partner</p>
							<p><span>Studio:</span> <?php echo $du->st_name; ?></p>
							</div>
							<div class="col-xs-12"><p> <?php echo $du->u_bio; ?> </p></div>
						</div>
					</div>
				</div>
				<?php }}}else{ ?>
				<div class="text-center">There are no business partners.</div>
				<?php } ?>
			</div>
			<div class="col-md-4">&nbsp;</div>
			<?php if($this->distributeUsers->count() > 6){ ?>
			<div class="col-md-4 text-center mar_t20" id="expand_type_4">
				<a href="javascript:void(0);" onclick="aboutXdiUsers(4);" class="btn btn-primary btn-lg btn-block">Expand to see all( <b id="view_more_4"><?php echo $this->distributeUsers->count(); ?></b> ) </a>
			</div>
			<?php } ?>
			<div class="col-md-4">&nbsp;</div>
		</div>
	</div>
	<!-- End -->
	
</div>
<input type="hidden" id="type_team_total_1" value="<?php echo $this->xdiUsers->count(); ?>">
<input type="hidden" id="type_team_total_2" value="<?php echo $this->LegalUsers->count(); ?>">
<input type="hidden" id="type_team_total_3" value="<?php echo $this->srmUsers->count(); ?>">
<input type="hidden" id="type_team_total_4" value="<?php echo $this->distributeUsers->count(); ?>">
<input type="hidden" id="type_team_1" value="1">
<input type="hidden" id="type_team_2" value="1">
<input type="hidden" id="type_team_3" value="1">
<input type="hidden" id="type_team_4" value="1">


<!--<div class="modal fade" id="imgopenlg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg menuof_img80">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title" id="myModalLabel">Menu of Services</h4>
            </div>
          <div class="modal-body no_padding">
            <img id="mimg" src="<?php echo $this->basePath; ?>/images/menu.png" class="img-responsive img_inline">
          </div>
        </div>
      </div>
    </div>
</div>
</div>-->