<?php 
	if($this->teamUsers->count()){
		foreach($this->teamUsers as $k=>$u){
?>
<div class="col-md-4">
	<div class="community_bg">
		<div class="row">
			<div class="col-xs-2" >
			<?php
			if($u->u_profile_image != ""){
				$pImagePath = $this->basePath.'/uploads/profiles/'.$u->u_profile_image;
			}else{
				$pImagePath = $this->basePath.'/images/user_profile.png';
			}
			?>
			<?php 
				$team = "N/A";
				if($u->u_team_type == 1){
					$team = 'XDI Team';
				}else if($u->u_team_type == 2){
					$team = 'Legal & Business Affairs Business Partner';
				}else if($u->u_team_type == 3){
					$team = 'SRM Business Partner';
				}else if($u->u_team_type == 4){
					$team = 'Distributed Development Business Partner';
				}
			?>
			<img class="profile_pic" src="<?php echo $pImagePath; ?>"/>
			</div>
			<div class="col-xs-10">
			<a href="<?php echo $this->baseUrl; ?>/view-profile/<?php echo $u->u_id; ?>"><b><?php echo $u->u_first_name.' '.$u->u_last_name; ?></b></a>
			<!--<p><span>Title:</span> <?php echo $u->u_title; ?></p>-->
			<p><span>Team:</span> <?php echo $team; ?></p>
			<p><span>Studio:</span> <?php echo $u->st_name; ?></p>
			</div>
			<div class="col-xs-12"><p> <?php echo $u->u_bio; ?> </p></div>
		</div>
	</div>
</div>
<?php }} ?>