<?php
	$header			=	$this->action('Application\Controller\IndexController', 'headerAction');
	$baseUrl 		= 	$header->headerarray['baseUrl'];
	$basePath 		= 	$header->headerarray['basePath'];
?>
<div id="page-wrapper" class="">
	<div class="container-fluid">
			<div class="row page_lo">
				<div class="col-xs-2 col-md-4 text-left">
					<a class="btn_site" href="<?php echo $baseUrl; ?>">Home</a>
				</div>  
				<?php include('home-menu.phtml'); ?>
			</div>
			<div class="row whit_col">
				<div class="col-lg-12">
					<h3>Welcome to Umpire Tax Solutions,LLC</h2>
				</div>
				<div class="col-lg-12 whit_col text-center">
					<h3>6 Steps to File your Tax Returns</h2>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12 text-center">
					<img  class="img-responsive2"src="<?php echo $basePath;?>/img/steps.png">
				</div>
			 </div>
	</div>
</div>