<?php
	$header			=	$this->action('Application\Controller\IndexController', 'headerAction');
	$baseUrl 		= 	$header->headerarray['baseUrl'];
	$basePath 		= 	$header->headerarray['basePath'];
?>
<div id="page-wrapper" class="">
	<div class="container-fluid">
			<div class="row page_lo">
				<div class="col-xs-2 col-md-4 text-left">
					<div class="btn_site"><a  href="<?php echo $baseUrl; ?>dashboard">Welcome to Umpire Tax Solutions,LLC </a></div>
				</div>  
				<?php include('home-menu.phtml'); ?>
			</div>
			<div class="row whit_col">
				<div class="col-lg-12 text-center ">
					<h4>6 Steps to File your Tax Returns</h4>
					<img  class="img-responsive2"src="<?php echo $basePath;?>/img/steps.png">
				</div>
				
			</div>
		</div>
</div>