<div id="page-wrapper" class="bac_img">
	<div class="container-fluid">
		<div class="row page_lo">
			<div class="col-xs-2 col-md-4 text-left">
				<div class="btn_site"><a href="<?php echo $this->baseUrl; ?>dependents-info">Dependents Information</a></div>
			</div>  
			<?php include('home-menu.phtml'); ?>
		</div>
		<div class="row mar_t20" id="editDependentshideShow">
			<form role="form" id="dependentInformation" onSubmit="submitDependentsInfo()" method="POST" 
			data-fv-message="This value is not valid"	
			data-fv-icon-valid="glyphicon glyphicon-ok"
			data-fv-icon-invalid="glyphicon glyphicon-remove"
			data-fv-icon-validating="glyphicon glyphicon-refresh">
				<div id="addMoreDepents">
					<?php if(count($this->dependentsInfo) != 0){
					foreach($this->dependentsInfo as $k=>$d){
						$index = $k+1;
					?>
					<div id="dependent-<?php echo $index; ?>">
						<?php if($index != 1){ ?>
						<div><a class="text-left btn_site">Dependent</a>&nbsp;&nbsp;<sup><a style="color:red" href="javascript:void(0);" onclick="removeDependents(<?php echo $index; ?>)">Remove</a></sup></div><br/>
						<?php }else{ ?>
						<div><div class="text-left">Dependent</div></div><br/>
						<?php } ?>
						<div class="col-lg-6 label_col">
							<div class="form-group">
								<label>First Name:</label>
								<input class="form-control" type="text" name="fname[]" id="fname<?php echo $index; ?>" required data-fv-notempty-message="Please enter firstname" value="<?php echo $d['first_name']; ?>">
							</div>
							<div class="form-group">
								<label>SSN/ITIN</label>
								<input class="form-control" type="text" name="ssn[]" id="ssn<?php echo $index; ?>" value="<?php echo $d['ssn']; ?>">
							</div>
							<div class="form-group">
								<label>DOB</label>
								<input class="form-control" type="text" name="dob[]" id="dob<?php echo $index; ?>" value="<?php echo $d['dob']; ?>">
							</div>
						</div>
						<div class="col-lg-6 label_col">
							<div class="form-group">
								<label>Last Name:</label>
								<input class="form-control" type="text" name="lname[]" id="lname<?php echo $index; ?>" value="<?php echo $d['last_name']; ?>">
							</div>
							<div class="form-group">
								<label>Relationship:</label>
								<select name="occupation[]" id="occupation<?php echo $index; ?>"  class="form-control" >
									<?php if(isset($d['occupation']) && $d['occupation']!="") { ?>
											<?php if($d['occupation'] == 'Aunt') { ?>
												<option value="Aunt" selected="selected">Aunt</option>
												<option value="Brother">Brother</option>
												<option value="Daughter">Daughter</option>
												<option value="Father">Father</option>
												<option value="Mother">Mother</option>
												<option value="Nephew">Nephew</option>
												<option value="Niece">Niece</option>
												<option value="Son">Son</option>
												<option value="Sister">Sister</option>
												<option value="Uncle">Uncle</option>
												<option value="others">others</option>
											<?php } else if($d['occupation'] == 'Brother'){?>
												<option value="Aunt">Aunt</option>
												<option value="Brother" selected="selected">Brother</option>
												<option value="Daughter">Daughter</option>
												<option value="Father">Father</option>
												<option value="Mother">Mother</option>
												<option value="Nephew">Nephew</option>
												<option value="Niece">Niece</option>
												<option value="Son">Son</option>
												<option value="Sister">Sister</option>
												<option value="Uncle">Uncle</option>
												<option value="others">others</option>
											<?php }  else if($d['occupation'] == 'Daughter'){?>
													<option value="Aunt">Aunt</option>
													<option value="Brother" >Brother</option>
													<option value="Daughter" selected="selected">Daughter</option>
													<option value="Father">Father</option>
													<option value="Mother">Mother</option>
													<option value="Nephew">Nephew</option>
													<option value="Niece">Niece</option>
													<option value="Son" >Son</option>
													<option value="Sister">Sister</option>
													<option value="Uncle">Uncle</option>
													<option value="others">others</option>
											<?php } else if($d['occupation'] == 'Father'){?>
													<option value="Aunt">Aunt</option>
													<option value="Brother" >Brother</option>
													<option value="Daughter">Daughter</option>
													<option value="Father"selected="selected">Father</option>
													<option value="Mother">Mother</option>
													<option value="Nephew">Nephew</option>
													<option value="Niece">Niece</option>
													<option value="Son" >Son</option>
													<option value="Sister">Sister</option>
													<option value="Uncle">Uncle</option>
													<option value="others">others</option>
											<?php } else if($d['occupation'] == 'Mother'){?>
													<option value="Aunt">Aunt</option>
													<option value="Brother" >Brother</option>
													<option value="Daughter">Daughter</option>
													<option value="Father">Father</option>
													<option value="Mother"selected="selected">Mother</option>
													<option value="Nephew">Nephew</option>
													<option value="Niece">Niece</option>
													<option value="Son" >Son</option>
													<option value="Sister">Sister</option>
													<option value="Uncle">Uncle</option>
													<option value="others">others</option>
											<?php } else if($d['occupation'] == 'Nephew'){?>
													<option value="Aunt">Aunt</option>
													<option value="Brother" >Brother</option>
													<option value="Daughter">Daughter</option>
													<option value="Father">Father</option>
													<option value="Mother">Mother</option>
													<option value="Nephew"selected="selected">Nephew</option>
													<option value="Niece">Niece</option>
													<option value="Son" >Son</option>
													<option value="Sister">Sister</option>
													<option value="Uncle">Uncle</option>
													<option value="others">others</option>
											<?php } else if($d['occupation'] == 'Niece'){?>
													<option value="Aunt">Aunt</option>
													<option value="Brother" >Brother</option>
													<option value="Daughter">Daughter</option>
													<option value="Father">Father</option>
													<option value="Mother">Mother</option>
													<option value="Nephew">Nephew</option>
													<option value="Niece"selected="selected">Niece</option>
													<option value="Son" >Son</option>
													<option value="Sister">Sister</option>
													<option value="Uncle">Uncle</option>
													<option value="others">others</option>
											<?php } else if($d['occupation'] == 'Son'){?>
													<option value="Aunt">Aunt</option>
													<option value="Brother" >Brother</option>
													<option value="Daughter">Daughter</option>
													<option value="Father">Father</option>
													<option value="Mother">Mother</option>
													<option value="Nephew">Nephew</option>
													<option value="Niece">Niece</option>
													<option value="Son" selected="selected">Son</option>
													<option value="Sister">Sister</option>
													<option value="Uncle">Uncle</option>
													<option value="others">others</option>
											<?php } else if($d['occupation'] == 'Sister'){?>
													<option value="Aunt">Aunt</option>
													<option value="Brother" >Brother</option>
													<option value="Daughter">Daughter</option>
													<option value="Father">Father</option>
													<option value="Mother">Mother</option>
													<option value="Nephew">Nephew</option>
													<option value="Niece">Niece</option>
													<option value="Son" >Son</option>
													<option value="Sister"selected="selected">Sister</option>
													<option value="Uncle">Uncle</option>
													<option value="others">others</option>
											<?php } else if($d['occupation'] == 'Uncle'){?>
													<option value="Aunt">Aunt</option>
													<option value="Brother" >Brother</option>
													<option value="Daughter">Daughter</option>
													<option value="Father">Father</option>
													<option value="Mother">Mother</option>
													<option value="Nephew">Nephew</option>
													<option value="Niece">Niece</option>
													<option value="Son" >Son</option>
													<option value="Sister">Sister</option>
													<option value="Uncle"selected="selected">Uncle</option>
													<option value="others">others</option>
											<?php } else if($d['occupation'] == 'others'){?>
													<option value="Aunt">Aunt</option>
													<option value="Brother" >Brother</option>
													<option value="Daughter">Daughter</option>
													<option value="Father">Father</option>
													<option value="Mother">Mother</option>
													<option value="Nephew">Nephew</option>
													<option value="Niece">Niece</option>
													<option value="Son" >Son</option>
													<option value="Sister">Sister</option>
													<option value="Uncle">Uncle</option>
													<option value="others"selected="selected">others</option>
											<?php } else {?>
													<option value="Aunt">Aunt</option>
													<option value="Brother">Brother</option>
													<option value="Daughter">Daughter</option>
													<option value="Father">Father</option>
													<option value="Mother">Mother</option>
													<option value="Nephew">Nephew</option>
													<option value="Niece">Niece</option>
													<option value="Son" selected="selected">Son</option>
													<option value="Sister">Sister</option>
													<option value="Uncle">Uncle</option>
													<option value="others">others</option>
											<?php } ?>
									<?php } else {?>
										<option value="Aunt">Aunt</option>
										<option value="Brother">Brother</option>
										<option value="Daughter">Daughter</option>
										<option value="Father">Father</option>
										<option value="Mother">Mother</option>
										<option value="Nephew">Nephew</option>
										<option value="Niece">Niece</option>
										<option value="Son" selected="selected">Son</option>
										<option value="Sister">Sister</option>
										<option value="Uncle">Uncle</option>
										<option value="others">others</option>
									<?php } ?>
								</select>
							</div>
							<div class="form-group">
								<label>Visa Type:</label>
								<input class="form-control" type="text" name="visa_type[]" id="visa_type<?php echo $index; ?>" value="<?php echo $d['visa_type']; ?>">
							</div>
						</div>
					</div>
					<?php }}else{ ?>
					<div id="dependent-1">
						<div><a class="text-left btn_site">Dependent</a></div><br/>
						<div class="col-lg-6 label_col">
							<div class="form-group">
								<label>First Name:</label>
								<input class="form-control" type="text" name="fname[]" id="fname1" required data-fv-notempty-message="Please enter firstname">
							</div>
							<div class="form-group">
								<label>ITIN/SSN</label>
								<input class="form-control" type="text" name="ssn[]" id="ssn1">
							</div>
							<div class="form-group">
								<label>DOB</label>
								<input class="form-control" type="text" name="dob[]" id="dob1">
							</div>
						</div>
						<div class="col-lg-6 label_col">
							<div class="form-group">
								<label>Last Name:</label>
								<input class="form-control" type="text" name="lname[]" id="lname1">
							</div>
							<div class="form-group">
								<label>Relationship:</label>
								<!--<input class="form-control" type="text" name="occupation[]" id="occupation1">-->
								<select class="form-control" name="occupation[]" id="occupation1">
									<option value="Aunt">Aunt</option>
									<option value="Brother">Brother</option>
									<option value="Daughter">Daughter</option>
									<option value="Father">Father</option>
									<option value="Mother">Mother</option>
									<option value="Nephew">Nephew</option>
									<option value="Niece">Niece</option>
									<option value="Son" selected="selected">Son</option>
									<option value="Sister">Sister</option>
									<option value="Uncle">Uncle</option>
									<option value="others">others</option>
								</select>
							</div>
							<div class="form-group">
								<label>Visa Type:</label>
								<input class="form-control" type="text" name="visa_type[]" id="visa_type1">
							</div>
						</div>
					</div>
					<?php } ?>
				</div>
				<div class="col-lg-12 label_col">
					<div class="col-lg-4">
						<div class="pull-left">
							<button type="button" class="btn btn-success btn-md" onclick="addMoreDependents();">Add more Dependents</button>
						</div>
					</div>
					<div class="pull-right">
						<button type="button" class="btn btn-warning  btn-md" onClick="viewDependtsInfoFun()" >BACK</button>
						<button type="submit" class="btn btn-success btn-md">SUBMIT</button>
					</div>
				</div>
		   </form>
		</div>	
	</div>
</div>
<?php if(count($this->dependentsInfo) != 0){ ?>
<input type="hidden" name="depentsCount" id="depentsCount" value="<?php count($this->dependentsInfo); ?>" />
<?php }else{ ?>
<input type="hidden" name="depentsCount" id="depentsCount" value="1" />
<?php } ?>
