<div id="page-wrapper" class="bac_img">
	<div class="container-fluid">
		<div class="row page_lo">
			<div class="col-xs-2 col-md-4 text-left">
				<div class="btn_site"><a href="<?php echo $this->baseUrl; ?>dependents-info">Dependents Information</a></div>
			</div>  
			<?php include('home-menu.phtml'); ?>
		</div>
		<div class="row mar_t20 bac_uplo" id="hideShowDependents" >
			<?php if(count($this->dependentsInfo) != 0){ 
			foreach($this->dependentsInfo as $k=>$d){
				$index = $k+1;
			?>
			<div class="col-lg-6 ">
				<div class="table-responsive">
				<div class="text-left">Dependent <?php echo $index; ?></div>
					<table class="table	">
						<tbody>
							<tr>
								<th>First Name</th>
								<td><?php echo $d['first_name']; ?></td>
							</tr>
							<tr>
							   <th>SSN/ITIN</th>
								<td><?php echo $d['ssn']; ?></td>
							</tr>
							<tr>
							   <th>DOB</th>
								<td><?php echo $d['dob']; ?></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div class="col-lg-6 ">
				<div class="table-responsive">
					<a class="text-left">&nbsp;</a>
					<table class="table	">
						<tbody>
							<tr>
							   <th>Last Name</th>
								<td><?php echo $d['last_name']; ?></td>
							</tr>
							<tr>
							   <th>Occupation</th>
								<td><?php echo $d['occupation']; ?></td>
							</tr>
							<tr>
							   <th>Visa Type</th>
								<td><?php echo $d['visa_type']; ?></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<?php }}else{ ?>
			<i>Depents information not available.</i>
			<?php } ?>
			<div class="col-lg-12 label_col">
				<div class="pull-right">
					<button type="button" onClick="editDependtsInfoFun()" class="btn btn-warning btn-md">EDIT</button>
				</div>
			</div>
		</div>
	</div>
</div>
