<div id="page-wrapper" class="bac_img">
	<div class="container-fluid">
	<div class="row page_lo">
	<div class="col-xs-2 col-md-4 text-left">
	<a class="btn_site" href="<?php echo $this->baseUrl; ?>dependents-info">Dependents</a>
	</div>  
	<div class="col-xs-10 col-md-8 text-right btn_pad">
		<a class="btn_site sm-hide" >File Number:UTS0023</a>
		<div class="dropdown btn_site">
			<a class=" dropdown-toggle" data-toggle="dropdown"> welcome dileep   <span class="caret"></a>
		 <ul class="dropdown-menu">
			<li><a href="#">Referral List</a></li>
			<li><a href="#">Change Password</a></li>
			<li><a href="#">Logout</a></li>
		 </ul>
		</div>
	</div>
	</div>
	<div class="row mar_t20">
	<form id="dependentsForm" name="dependentsForm" method="POST" onSubmit="submitDependentsForm()" data-fv-message="This value is not valid"
						data-fv-icon-valid="glyphicon glyphicon-ok"
						data-fv-icon-invalid="glyphicon glyphicon-remove"
						data-fv-icon-validating="glyphicon glyphicon-refresh">
			<div class="col-lg-6 label_col">
					<div class="form-group">
						<label>First Name:</label>
						<input class="form-control" type="text" name="firstName" id="firstName" required data-fv-notempty-message="Please enter firstname">
					</div>
					<div class="form-group">
						<label>SSN</label>
						<input class="form-control" type="text" name="ssn" id="ssn" required data-fv-notempty-message="Please enter ssn">
					</div><div class="form-group">
						<label>DOB</label>
						<input class="form-control" type="text" name="dob" id="dob" required data-fv-notempty-message="Please enter ssn">
					</div>
			</div>
			
			<div class="col-lg-6 label_col">
					<div class="form-group">
						<label>Last Name:</label>
						<input class="form-control" type="text" name="lastName" id="lastName" required data-fv-notempty-message="Please enter lastname">
					</div>
					<div class="form-group">
						<label>Occupation:</label>
						<input class="form-control" type="text" name="occupation" id="occupation" required data-fv-notempty-message="Please enter occupation">
					</div>
					<div class="form-group">
						<label>Visa Type:</label>
						<input class="form-control" type="text" name="visaType" id="visaType" required data-fv-notempty-message="Please enter Visa type">
					</div>
				
			</div>
			
			<div class="col-lg-12 label_col">
			<p class="whit_col">Note: If Spouse doesn’t hold either SSN/ITIN please upload Passport Scan copy</p>
					
			</div>
		</div>
		<div class="col-lg-12 label_col">
			<div class="col-lg-4">
				<div class="pull-left">
					<button type="button" class="btn btn-success btn-md">Add more Dependents</button>
				</div>
			</div>
			<div class="col-lg-8">
				<div class="pull-right">
					<button type="button" class="btn btn-warning btn-md">EDIT</button>
					<button type="submit" class="btn btn-success btn-md">SUBMIT</button>
				</div>
		  </div>
	  </div>
	 </form>
</div>
</div>