<div id="page-wrapper" class="bac_img">
	<div class="container-fluid">
	<div class="row page_lo">
		<div class="col-xs-2 col-md-4 text-left">
			<a class="btn_site" href="<?php echo $this->baseUrl; ?>emp-info">Emp Info </a>
		</div>  
	</div>
	<div class="row mar_t20">
	 <div class="col-lg-6 label_col">
		<form role="form">
			<div class="form-group">
				<label>Employer Name:</label>
				<input class="form-control">
			</div>
			<div class="form-group">
				<label>Project Start Date</label>
				<input class="form-control">
			</div>
			
		</form>
	</div>
	<div class="col-lg-6 label_col">
		<form role="form">
			<div class="form-group">
				<label>Client Name(Any):</label>
				<input class="form-control">
			</div>
			<div class="form-group">
			<label>Project End Date</label>
			<input class="form-control">
			</div>
		</form>
	</div>
	<div class="col-lg-12 label_col">
		<p class="whit_col">Note: If Spouse doesn’t hold either SSN/ITIN please upload Passport Scan copy</p>
		<div class="pull-right">
			<button type="button" class="btn btn-warning btn-md">EDIT</button>
			<button type="button" class="btn btn-success btn-md">SUBMIT</button>
		</div>
   </div>
   </div>
</div>
</div>