<div id="page-wrapper" class="bac_img">
	<div class="container-fluid">
		<div class="row page_lo">
			<div class="col-xs-2 col-md-4 text-left">
				<div class="btn_site"><a href="<?php echo $this->baseUrl; ?>spouse-info">Employer Information</a></div>
			</div>  
			<?php include('home-menu.phtml'); ?>
		</div>
		
		<div class="row mar_t20 bac_uplo" id="hideShowDependents" >
			<?php if(count($this->empInfo) != 0){
			foreach($this->empInfo as $k=>$e){
				$index = $k+1;
			?>
			<div class="col-lg-6 ">
				<div class="table-responsive">
				<a class="text-left btn_site">Information <?php echo $index; ?></a>
					<table class="table	">
						<tbody>
							<tr>
								<th>Employer Name:</th>
								<td><?php echo $e['company_name']; ?></td>
							</tr>
							<tr>
							   <th>Project Start Date:</th>
								<td><?php echo $e['proj_start_date']; ?></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<style>
				.btn_sitea{
					-moz-user-select: none;
					background-image: none;
					border: 1px solid transparent;
					color: #fff;
					cursor: pointer;
					display: inline-block;
					font-size: 14px;
					font-weight: 400;
					line-height: 1.42857;
					margin-bottom: 0;
					padding: 6px 12px;
					text-align: center;
					vertical-align: middle;
					white-space: nowrap;
				}
			</style>
			<div class="col-lg-6 ">
				<div class="table-responsive">
					<a class="text-left btn_sitea">&nbsp;&nbsp;&nbsp;&nbsp;</a>
					<table class="table	">
						<tbody>
							<tr>
							   <th>Client Name(Any):</th>
								<td><?php echo $e['client_name']; ?></td>
							</tr>
							<tr>
							   <th>Project End Date:</th>
								<td><?php echo $e['proj_end_date']; ?></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<?php }}else{ ?>
			<i>Employee information not available.</i>
			<?php } ?>
			<div class="col-lg-12 label_col">
				<div class="pull-right">
					<button type="button" onClick="editEmpInfoFun()" class="btn btn-warning btn-md">EDIT</button>
				</div>
			</div>
		</div>
	</div>
</div>
