<?php	
	$header			=	$this->action('Application\Controller\IndexController', 'headerAction');
	$baseUrl 		= 	$header->headerarray['baseUrl'];
	$basePath 		= 	$header->headerarray['basePath'];
	// echo "<pre>";print_r($_SESSION["user"]["user_name"]);exit;
?>
<div class="col-xs-10 col-md-8 text-right btn_pad">
	<div class="btn_site sm-hide">
		File Number : <?php if(isset($_SESSION["user"]["unique_code"]) && $_SESSION["user"]["unique_code"]!=""){ echo $_SESSION["user"]["unique_code"]; } else { ?> Not yet assigned <?php } ?>
	</div>
	<div class="dropdown btn_site">
		<a class=" dropdown-toggle" data-toggle="dropdown"> Welcome <?php if(isset($_SESSION["user"]["user_id"]) && $_SESSION["user"]["user_id"]!=""){ echo ucfirst($_SESSION["user"]["user_name"]); } else { ?> User <?php } ?>   <span class="caret"></a>
		 <ul class="dropdown-menu">
			<li><a href="<?php echo $baseUrl;?>referral-list">Referral List</a></li>
			<li><a href="javascript:void(0);" onClick="changeQ();">Change Password</a></li>
			<li><a href="javascript:void(0);" onClick="logOutFun();">Logout</a></li>
		 </ul>
	</div>
</div>