<?php	
	$header			=	$this->action('Application\Controller\IndexController', 'headerAction');
	$baseUrl 		= 	$header->headerarray['baseUrl'];
	$basePath 		= 	$header->headerarray['basePath'];
?>
<div class="col-xs-10 col-md-8 text-right btn_pad">
	<div class="btn_site sm-hide">
		File Number: <?php if(isset($_SEESSION["user"]["file_name"]) && $_SEESSION["user"]["file_name"]!=""){ echo $_SEESSION["user"]["file_name"]; } else { ?> UTS0023 <?php } ?>
	</div>
	<div class="dropdown btn_site">
		<a class=" dropdown-toggle" data-toggle="dropdown"> Welcome <?php if(isset($_SEESSION["user"]["user_name"]) && $_SEESSION["user"]["user_name"]!=""){ echo ucfirst($_SEESSION["user"]["user_name"]); } else { ?> Dileep <?php } ?>   <span class="caret"></a>
		 <ul class="dropdown-menu">
			<li><a href="<?php echo $baseUrl;?>referral-list">Referral List</a></li>
			<li><a href="javascript:void(0);" onClick="changeQ();">Change Password</a></li>
			<li><a href="javascript:void(0);" onClick="logOutFun();">Logout</a></li>
		 </ul>
	</div>
</div>