<div class="content-wrapper">
		<div class="bredcrum_bg">
			<div class="container">
				<section class="content-header mar_t40">
					<h1 class="text-right">
						&nbsp;
					</h1>
					<ol class="breadcrumb">
						<li><a href="<?php echo $baseUrl;?>/home" class="color_a">Home</a></li>
						<li><a href="<?php echo $baseUrl;?>/about-xdi" class="color_a" >About XDI</a></li>
						<li><a> Menu Of Services </a></li>
					</ol>
				</section>
			</div>
		</div>
		<div class="container">
			<div class="title_heading pos_r mar_t40 mar_b10">
				<h1><span class="span_bg_g">XDI's Menu of Services</span></h1>
				<div class="title_lines"></div>
			</div>
		</div>
		 <div class="text-center"><img id="mimg" src="<?php echo $this->basePath; ?>/images/menu.png" class="img-responsive img_inline"></div>
</div>