<?php //echo "<pre>"; print_r($this->allVendors); exit; ?>
		<div class="mar_t20 pos_r">
			<div class="row outsourcing_sm">
			<?php foreach($this->allVendors as $key => $ru){ ?>
				<div class="col-md-4">
					<div class="community_bg pos_r">
						<div class="row">
							<div class="col-xs-2" >
							<?php
							if($ru['u_profile_image'] != ""){
								$pImagePath = $this->basePath.'/uploads/profiles/'.$ru['u_profile_image'];
							}else{
								$pImagePath = $this->basePath.'/images/user_profile.png';
							}
							?>
							<?php 
								$team = "Team not available";
								if($ru['u_team_type'] == 1){
									$team = 'XDI Team';
								}else if($ru['u_team_type'] == 2){
									$team = 'Legal & Business Affairs Business Partner';
								}else if($ru['u_team_type'] == 3){
									$team = 'SRM Business Partner';
								}else if($ru['u_team_type'] == 4){
									$team = 'Distributed Development Business Partner';
								}
							?>
							<img class="profile_pic" src="<?php echo $pImagePath; ?>"/>
							</div>
							<div class="col-xs-10">
							<a href="<?php echo $this->baseUrl; ?>/view-profile/<?php echo $ru['u_id']; ?>"><b><?php echo $ru['u_first_name'].' '.$ru['u_last_name']; ?></b></a>
							<!--<p><span>Title:</span> <?php echo $ru['u_title']; ?></p>-->
							<p><span>Team:</span> <?php echo $team; ?></p>
								<p><span>Studio:</span> <?php if(isset($ru['st_name']) && $ru['st_name'] !=""){ echo $ru['st_name']; }else{ echo "Studio not available"; } ?></p>	
							</div>
							<div class="col-xs-12"><p> <?php echo $ru['u_bio']; ?> </p></div>
						</div>
						<?php if($ru['u_team_type'] == 1){ ?>
						<div class="xxdi_tem_posab"><img title="XDI Team Member" alt="xditeam" src="<?php echo $basePath; ?>/images/xditeam.png"/></div>
						<?php } ?>
					</div>
				</div>
			<?php } ?>
			</div>
		</div>
	<!-- Pagination shoow -->
	<div class="box_white mar_t20">
	<div class="paginatin_pad">
	<div class="pull-left">
		<p style="margin-top:13px;" id="latestPartnersCount"></p>
	</div>
	<div class="pull-right">
	<ul class="pagination no_margin">
		<li class="item p_m text-center products-list1" id="pagination" >
			<?php 
				echo $this->paginationControl(
					$this->paginationVendors,
					'sliding',
					array('partial/outsourcingpaginator.phtml', 'Application'),
					array(
						'route' => 'outsourcing-viewall'
					)
				);
			?>
		</li>
	</ul>
	</div>
	<div class="clearfix"></div>
	</div>
	</div>
	<!-- End -->
	<input type="hidden" id="startResults" value="<?php echo $this->startResults; ?>">
	<input type="hidden" id="endResults" value="<?php echo $this->endResults; ?>">
	<input type="hidden" id="totalCount" value="<?php echo $this->totalCount; ?>">

<script>
$(document).ready(function()
	{
		var $container = $('div.row').has('div.col-md-4');
		$container.isotope({
		});
		
	});
	if ($(window).width() < 768){
		$('#smroffset').removeClass('col-xs-offset-3');
	} else {
		$('#smroffset').addClass('col-xs-offset-3');
	}
</script>		