<div id="page-wrapper" class="bac_img">
	<div class="container-fluid">
	<div class="row page_lo">
	<div class="col-xs-2 col-md-4 text-left">
	<div class="btn_site"><a href="<?php echo $this->baseUrl; ?>refereal-list">Referral-list</a></div>
	</div>  
	<?php include('home-menu.phtml'); ?>
	</div><br/>
	<!-- Main content -->
	<section class="content">
	<div class="box">
			<div class="box-body tEList">
			 
			</div><!-- /.box-body -->
		  </div><!-- /.box -->
	</section>
	</div>
</div>