<div id="page-wrapper" class="bac_img">
	<div class="container-fluid">
	<div class="row page_lo">
	<div class="col-xs-2 col-md-4 text-left">
	<div class="btn_site"><a href="<?php echo $this->baseUrl; ?>spouse-info">Spouse </a></div>
	</div>  
	<?php include('home-menu.phtml'); ?>
	</div>
	<div class="row mar_t20 bac_uplo" id="hideShowSpouse" >
		<div class="col-lg-6 ">
			<div class="table-responsive">
				<table class="table	">
					<tbody>
						<tr>
							<th>First Name</th>
							<td><?php if(isset($this->userInfo->first_name) && $this->userInfo->first_name !=""){ echo $this->userInfo->first_name; }?></td>
						</tr>
						<tr>
						   <th>SSN</th>
							<td><?php if(isset($this->userInfo->ssnitin) && $this->userInfo->ssnitin !=""){ echo $this->userInfo->ssnitin; }?></td>
						</tr>
						<tr>
						   <th>DOB</th>
							<td><?php if(isset($this->userInfo->dob) && $this->userInfo->dob !=""){ echo $this->userInfo->dob; }?></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<div class="col-lg-6 ">
			<div class="table-responsive">
				<table class="table	">
					<tbody>
						<tr>
						   <th>Last Name</th>
							<td><?php if(isset($this->userInfo->last_name) && $this->userInfo->last_name !=""){ echo $this->userInfo->last_name; }?></td>
						</tr>
						<tr>
						   <th>ITIN</th>
							<td><?php if(isset($this->userInfo->itin) && $this->userInfo->itin !=""){ echo $this->userInfo->itin; }?></td>
						</tr>
						<tr>
						   <th>Occupation</th>
							<td><?php if(isset($this->userInfo->occupation) && $this->userInfo->occupation !=""){ echo $this->userInfo->occupation; }?></td>
						</tr>
						<tr>
						   <th>Visa Type</th>
							<td><?php if(isset($this->userInfo->visa_type) && $this->userInfo->visa_type !=""){ echo $this->userInfo->visa_type; }?></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<div class="col-lg-12 label_col">
			<div class="pull-right">
				<button type="button" onClick="editSpouseInfoFun()" class="btn btn-warning btn-md">EDIT</button>
			</div>
		</div>
	</div>
	
	<div class="row mar_t20" id="editSpousehideShow" style="display:none">
	<form role="form" id="spouseInformation" onSubmit="submitSpouseInfo()" method="POST" 
	data-fv-message="This value is not valid"	
	data-fv-icon-valid="glyphicon glyphicon-ok"
	data-fv-icon-invalid="glyphicon glyphicon-remove"
	data-fv-icon-validating="glyphicon glyphicon-refresh">
	 <div class="col-lg-6 label_col">
			<div class="form-group">
					<label>First Name:</label>
					<input class="form-control" type="text" name="fname" id="fname" required data-fv-notempty-message="Please enter firstname" value="<?php if(isset($this->userInfo->first_name) && $this->userInfo->first_name !=""){ echo $this->userInfo->first_name; }?>">
				</div>
				<div class="form-group">
					<label>SSN</label>
					<input class="form-control" type="text" name="ssn" id="ssn" value="<?php if(isset($this->userInfo->ssnitin) && $this->userInfo->ssnitin !=""){ echo $this->userInfo->ssnitin; }?>">
				</div>
				<div class="form-group">
					<label>DOB</label>
					<input class="form-control" type="text" name="dob" id="dob" value="<?php if(isset($this->userInfo->dob) && $this->userInfo->dob !=""){ echo $this->userInfo->dob; }?>">
				</div>
			</div>
			<div class="col-lg-6 label_col">
				<div class="form-group">
					<label>Last Name:</label>
					<input class="form-control" type="text" name="lname" id="lname" value="<?php if(isset($this->userInfo->last_name) && $this->userInfo->last_name !=""){ echo $this->userInfo->last_name; }?>">
				</div>
				<div class="form-group">
					<label>ITIN</label>
					<input class="form-control" type="text" name="itin" id="itin" value="<?php if(isset($this->userInfo->itin) && $this->userInfo->itin !=""){ echo $this->userInfo->itin; }?>">
				</div>
				<div class="form-group">
					<label>Occupation:</label>
					<input class="form-control" type="text" name="occupation" id="occupation" value="<?php if(isset($this->userInfo->occupation) && $this->userInfo->occupation !=""){ echo $this->userInfo->occupation; }?>">
				</div>
			<div class="form-group">
				<label>Visa Type:</label>
				<input class="form-control" type="text" name="visa_type" id="visa_type" value="<?php if(isset($this->userInfo->visa_type) && $this->userInfo->visa_type !=""){ echo $this->userInfo->visa_type; }?>">
			</div>
		
	</div>
	<div class="col-lg-12 label_col">
		<p class="whit_col">Note: If Spouse doesn’t hold either SSN/ITIN please upload Passport Scan copy</p>
		<div class="pull-right">
			<button type="button" class="btn btn-warning  btn-md" onClick="backSpouseFun()" >BACK</button>
			<button type="submit" class="btn btn-success btn-md">SUBMIT</button>
		</div>
   </div>
   <input type="hidden" name="hidUserId" id="hidUserId" value="<?php if(isset($this->userInfo->user_id) && $this->userInfo->user_id){ echo $this->userInfo->user_id; }?>" />
      </form>
   </div>
</div>
</div>