<div id="page-wrapper" class="bac_img">
	<div class="container-fluid">
	<div class="row page_lo">
	<div class="col-xs-2 col-md-4 text-left">
	<a class="btn_site" href="<?php echo $this->baseUrl; ?>summary-info">View Tax Summary</a>
	</div>  
	<div class="col-xs-10 col-md-8 text-right btn_pad">
		<a class="btn_site sm-hide" >File Number:UTS0023</a>
		<div class="dropdown btn_site">
			<a class=" dropdown-toggle" data-toggle="dropdown"> welcome dileep   <span class="caret"></a>
		 <ul class="dropdown-menu">
			<li><a href="#">Referral List</a></li>
			<li><a href="#">Change Password</a></li>
			<li><a href="#">Logout</a></li>
		 </ul>
		</div>
	</div>
	</div>
	<div class="row mar_t20 bac_uplo">
		<div class="col-lg-6 ">
			<div class="table-responsive">
				&nbsp;
			</div>
		</div>
		<div class="col-lg-6 ">
			&nbsp;
		</div>
	</div>		
</div>
</div>