<div id="page-wrapper" class="bac_img">
	<div class="container-fluid">
	<div class="row page_lo">
	<div class="col-xs-2 col-md-4 text-left">
	<a class="btn_site" href="<?php echo $this->baseUrl; ?>tax-info">Tax Payer Information</a>
	</div>  
	<div class="col-xs-10 col-md-8 text-right btn_pad">
		<a class="btn_site sm-hide" >File Number:UTS0023</a>
		<div class="dropdown btn_site">
			<a class=" dropdown-toggle" data-toggle="dropdown"> welcome dileep   <span class="caret"></a>
		 <ul class="dropdown-menu">
			<li><a href="#">Referral List</a></li>
			<li><a href="#">Change Password</a></li>
			<li><a href="#">Logout</a></li>
		 </ul>
		</div>
	</div>
	</div>
	<div class="row mar_t20">
	<div class="col-lg-6 label_col">
	<form role="form">
	<div class="form-group">
	<label>First Name:</label>
	<input class="form-control">
	</div>
	<div class="form-group">
	<label>SSN</label>
	<input class="form-control">
	</div><div class="form-group">
	<label>DOB</label>
	<input class="form-control">
	</div>
	<div class="form-group">
	<label>Dependents:Yes/No:</label>
	<input class="form-control">
	</div>
	<div class="form-group">
	<label>Mobile/Phone</label>
	<input class="form-control">
	</div>
	<div class="form-group">
	<label>Address:</label>
	<!-- <textarea class="form-control" rows="3"></textarea> -->
	<input class="form-control">
	</div>
	<div class="form-group">
	<label>State:</label>
	<input class="form-control">
	</div>
	<div class="form-group">
	<label>Zip Code:</label>
	<input class="form-control">
	</div>
	<div class="form-group">
	<label>Employer Name:</label>
	<input class="form-control">
	</div>
	</form>
	</div>

	<div class="col-lg-6 label_col">
	<form role="form">
	<div class="form-group">
	<label>Last Name:</label>
	<input class="form-control">
	</div>
	<div class="form-group">
	<label>Occupation:</label>
	<input class="form-control">
	</div><div class="form-group">
	<label>Filing Status:</label>
	<input class="form-control">
	</div>
	<div class="form-group">
	<label>E-Mail:</label>
	<input class="form-control">
	</div>
	<div class="form-group">
	<label>Work Phone:</label>
	<input class="form-control">
	</div>
	<div class="form-group">
	<label>City:</label>
	<input class="form-control">
	</div>
	<div class="form-group">
	<label>Country:</label>
	<input class="form-control">
	</div>
	<div class="form-group">
	<label>Do you have health Insurance</label>
	<input class="form-control">
	</div>
	<div class="form-group">
	<label>Client Name(If working in CL Location)</label>
	<input class="form-control">
	</div>
	</form>
	<div class="col-lg-12 label_col">
	<div class="pull-right">
	<button type="button" class="btn btn-warning btn-md">EDIT</button>
	<button type="button" class="btn btn-success btn-md">SUBMIT</button>
	</div>
	</div>
	</div>
	</div>
	</div>
</div>