<div class="content-wrapper">
		<div class="bredcrum_bg">
			<div class="container">
				<section class="content-header mar_t40">
					<h1 class="text-right">
						&nbsp;
					</h1>
					<ol class="breadcrumb">
						<li><a href="<?php echo $baseUrl;?>/home" class="color_a">Home</a></li>
						<li><a>Terms & Conditions</a></li>
					</ol>
				</section>
			</div>
		</div>
		<div class="container">
			<div class="partner_heading pos_r mar_t40">
				<h1><span class="span_bg_g">Terms and Conditions</span></h1>
				<div class="title_lines"></div>
			</div>
			<div class="terms_con mar_b20">
				<h3>Representations of Prospective External Partner</h3>
				<ol>
					<li> The information set forth in the foregoing EA Due Diligence Questionnaire is accurate and complete.  The Company agrees to promptly notify EA in writing of any material changes in the information set forth in such questionnaire.</li>
					<li>The Company, its parent, subsidiary and affiliate and any director, corporate officer or top management of the Company, its parent, subsidiary and affiliate is not also an employee, officer, or representative of a government, a public international organization, political party or candidate for political office except as disclosed in the EA Due Diligence Questionnaire.</li>
					<li> It acknowledges that it understands that U.S. legislation prohibits U.S. citizens and U.S. companies from paying bribes to foreign officials in order to obtain or retain business and that Vendor must comply with such legislation if it wishes to conduct business with EA.  Therefore, The Company further understands and represents that it will NOT:
						<ul type="a">
							<li>Offer, pay, or promise to pay or give anything of value;</li>
							<li> To foreign officials, public international organization officials, foreign political party officials or candidates for such offices directly or indirectly;</li>
							<li>For purposes of influencing officials acts and decisions (including failures to act and to decide);</li>
							<li> In order to assist EA in obtaining or retaining business.</li>
						</ul>
					</li>
					<li>  It will comply with all laws of the local country with regard to prohibition of bribery of government personnel.</li>
				</ol>
				<b>By accepting terms and conditions, you certify that you have read and understood the nature, relevance and importance of the statements contained in the EA Due Diligence Questionnaire (Pt.A) and this Representations of Prospective Business Partner.  You understand that any agreement that The Company may enter into with EA will contain such statements as representations.  You hereby certify that such representations are true and correct to the best of your knowledge</b>
			</div>
		</div>
	</div>