<div class="content-wrapper">
	<div class="bredcrum_bg">
			<div class="container">
				<section class="content-header mar_t40 tooltip_pw">
					<h1 class="text-right ">
						&nbsp;
					</h1>
					<ol class="breadcrumb sm_hide">
						<li><a href="<?php echo $this->baseUrl;?>/home" class="color_a">Home</a></li>
						<li><a href="<?php echo $this->baseUrl;?>/outsourcing-viewall" class="color_a">External Development Community</a></li>
						<li><a>Update Profile</a></li>
					</ol>
				</section>
			</div>
	</div>
	<div class="container mar_t40 sm_container_pad">
		<div class="box_white">
		<!-- Box Title -->
		<div class="box-header with-border">
		  <h1 class="box-title">Update Profile</h1>
		  <div class="box-tools pull-right">
			<a href="<?php echo  $baseUrl;?>/view-profile/<?php echo $this->u_id; ?>" class="font_18 text-uppercase">Back</a>
		  </div>
		</div>
		<!-- End -->
		<?php if(isset($this->getUserInfo->u_profile_image) && $this->getUserInfo->u_profile_image != "") {
			$proPic = $this->basePath.'/uploads/profiles/'.$this->getUserInfo->u_profile_image;
		}else{
			$proPic = $this->basePath.'/images/people-2.png';
		} ?>
		<div class="box-body pad_t30 mandatory_color">
		 <form class="form-horizontal" id="userForm"  name="userForm" onsubmit="updateProfileValidation()" method="POST"  
					  data-fv-message="This value is not valid"
                      data-fv-icon-valid="glyphicon"
                      data-fv-icon-invalid="glyphicon"
                      data-fv-icon-validating="glyphicon glyphicon-refresh">
			<div class="row">
				<div class="col-md-20 text-center">
					<div class="user_profile_img">
						<img id="uploadedProfileImage" src="<?php echo $proPic; ?>" class="img-responsive">
					</div><br/>
					<button type="button" class="btn btn-info" onclick="showCropPopup();" >Edit Photo</button>
				</div>
				<div class="col-md-99 psm_c">
					<div class="form-group">
                      <label for="firstname" class="col-sm-2 control-label">First Name <sup>*</sup></label>
                      <div class="col-sm-6">
                        <input type="text" class="form-control" id="firstName" name="firstName"  placeholder="Fist Name" value="<?php if(isset($this->getUserInfo->u_first_name) && $this->getUserInfo->u_first_name!=""){ echo $this->getUserInfo->u_first_name; } ?>" required data-fv-notempty-message="The lastname is required and cannot be empty" data-fv-regexp="true" data-fv-regexp-regexp="^\d*[a-zA-Z]{1,}\d*" $data-fv-regexp-message="The first name can consist of alphanumarical characters" data-fv-stringlength="true" data-fv-stringlength-max="100" data-fv-stringlength-message="The first name must be less than 100 characters">
                      </div>
                    </div>
					 
					 <div class="form-group">
                      <label for="lastname" class="col-sm-2 control-label">Last Name <sup>*</sup></label>
                      <div class="col-sm-6">
                        <input type="text" class="form-control" id="lastName" name="lastName" placeholder="Last Name" value="<?php if(isset($this->getUserInfo->u_last_name) && $this->getUserInfo->u_last_name!=""){ echo $this->getUserInfo->u_last_name; } ?>" required data-fv-notempty-message="The firstname is required and cannot be empty" data-fv-regexp="true" data-fv-regexp-regexp="^\d*[a-zA-Z]{1,}\d*" $data-fv-regexp-message="The last name can consist of alphanumarical characters" data-fv-stringlength="true" data-fv-stringlength-max="100" data-fv-stringlength-message="The last name must be less than 100 characters">
                      </div>
                    </div>
                    <div class="form-group">
                      <label for="businesstitle" class="col-sm-2 control-label">Title <sup>*</sup></label>
                      <div class="col-sm-6">
                        <input type="text" class="form-control" id="title" name="title"  placeholder="Title" value="<?php if(isset($this->getUserInfo->u_title) && $this->getUserInfo->u_title!=""){ echo $this->getUserInfo->u_title; } ?>" required data-fv-notempty-message="The title is required and cannot be empty" data-fv-stringlength="true" data-fv-stringlength-max="100" data-fv-stringlength-message="The title must be less than 100 characters">
                      </div>
                    </div>
					<?php if(isset($this->getUserInfo->u_email) && $this->getUserInfo->u_email!=""){ 
						$disable = 'disabled';
					}else{
						$disable = '';
					}?>
					<div class="form-group">
                      <label for="emailaddress" class="col-sm-2 control-label">Email Address  <sup>*</sup></label>
                      <div class="col-sm-6">
                        <input type="text" class="form-control" id="emailAddress" name="emailAddress" placeholder="Email Address" required data-fv-notempty-message="The email is required and cannot be empty" 
						data-fv-emailaddress="true"
					   data-fv-emailaddress-message="The input is not a valid email address" value="<?php if(isset($this->getUserInfo->u_email) && $this->getUserInfo->u_email!=""){ echo $this->getUserInfo->u_email; }?>"  <?php echo $disable; ?> data-fv-regexp="true" data-fv-regexp-regexp="^([A-Za-z0-9_\-\.]+)@[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)*(\.[A-Za-z]{2,3})$"  data-fv-regexp-message="EX : (xdi@portal.com)" data-fv-stringlength="true" data-fv-stringlength-max="100" data-fv-stringlength-message="The email must be less than 100 characters">
                      </div>
                    </div>
					<div class="form-group">
                      <label for="password" class="col-sm-2 control-label">Ea Studio <sup>*</sup></label>
                      <div class="col-sm-6">
                        <select class="form-control" id="studio"  name="studio" required data-fv-notempty-message="The ea studio is required and cannot be empty"  >
						<option value="" >- Select Studio-</option>
						<?php if($this->studiolist->count() != 0){
							$select  = '';
										foreach($this->studiolist as $sl){
											if(isset($this->getUserInfo->u_studios) && $this->getUserInfo->u_studios!="" ){
												
												if($this->getUserInfo->u_studios == $sl->st_id){
													$select  = 'selected';
												}else{
													$select  = '';
												}
											}
									?>
								<option value="<?php echo $sl->st_id; ?>" <?php echo  $select; ?>><?php if($sl->st_name != ""){ echo $sl->st_name; } ?></option>
							<?php }} ?>
						</select>
                      </div>
                    </div>
					<div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">External partner utilized</label>
                      <div class="col-sm-6">
						<select class="test form-control" id="vendorUtilized" name="vendorUtilized[]" multiple="multiple" placeholder="Select Partner Utilized" >
						<option value="" > Select Partner Utilized </option>
							<?php if($this->vendorList->count() != 0){
								$venSelected = "";
									foreach($this->vendorList as $vl){
										 if(in_array($vl->v_id ,$this->userVedors)){
												$venSelected = 'selected';
											}else{
												$venSelected = '';
											}
										 
									?>
								<option value="<?php echo $vl->v_id; ?>" <?php echo $venSelected;?> ><?php if($vl->v_name != ""){ echo $vl->v_name; } ?></option>
							<?php }} ?>
						</select>
                      </div>
                    </div>
					<div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">Expertise</label>
                      <div class="col-sm-6">
						<select class="test form-control"  id="expertise" name="expertise[]"  multiple="multiple" placeholder="Select Expertise" >
							<?php if($this->expertiseList->count() != 0){
								$expSelected = '';
									foreach($this->expertiseList as $el){
										if(in_array($el->ex_id ,$this->userExprt)){
											$expSelected = 'selected';
										}else{
											$expSelected = '';
										}
											
									?>
								<option value="<?php echo $el->ex_id; ?>" <?php echo $expSelected;?> ><?php if($el->ex_name != ""){ echo $el->ex_name; } ?></option>
							<?php }} ?>
						</select>
                      </div>
                    </div>
					<div class="form-group">
                      <label for="firstname" class="col-sm-2 control-label">Expertise Additional</label>
                      <div class="col-sm-6">
                        <input type="text" class="form-control" id="expAdditional" name="expAdditional"  value="<?php if(isset($this->getUserInfo->u_expertise_additional) && $this->getUserInfo->u_expertise_additional!=""){ echo $this->getUserInfo->u_expertise_additional; } ?>" placeholder="Expertise Additional" data-fv-stringlength="true" data-fv-stringlength-max="100" data-fv-stringlength-message="The expertise additional must be less than 100 characters">
                      </div>
                    </div>
					<div class="form-group">
                      <label for="firstname" class="col-sm-2 control-label">Titles Workes On</label>
                      <div class="col-sm-6">
                        <textarea class="form-control" id="titleWorkOn" name="titleWorkOn" placeholder="Titles Works On"><?php if(isset($this->getUserInfo->u_titles_worked_on) && $this->getUserInfo->u_titles_worked_on!=""){ echo $this->getUserInfo->u_titles_worked_on; } ?></textarea>
                      </div>
                    </div>
					<div class="form-group">
                      <label for="firstname" class="col-sm-2 control-label">BIO</label>
                      <div class="col-sm-6">
                        <textarea class="form-control" id="bio" name="bio" placeholder="BIO"><?php if(isset($this->getUserInfo->u_bio) && $this->getUserInfo->u_bio!=""){ echo $this->getUserInfo->u_bio; } ?></textarea>
                      </div>
                    </div>
					<div class="form-group">
                      <label for="firstname" class="col-sm-2 control-label">Is Admin</label>
                      <div class="col-sm-6">
					   <?php
						if(isset($this->getUserInfo->u_ut_id) && $this->getUserInfo->u_ut_id !="" ){
						if($this->getUserInfo->u_ut_id == 4){
								$yChecked = "checked";
								$nChecked = "";
							}else{
								$nChecked = "checked";
								$yChecked = "";
							}
						}else{
							$nChecked = "checked";
							$yChecked = "";
						}
					  ?>
					<input type="radio" id="isAdmin1" name="isAdmin" value="1" <?php echo $nChecked; ?>>No
					<input type="radio" id="isAdmin2" name="isAdmin" value="2" <?php echo $yChecked; ?>>Yes
                      </div>
                    </div>
				</div>
			</div>
			<div class="form-group no_margin brg_topborder">
				<div class="col-sm-12">
				 <span id="loadRegistration"  style="float:left;display:none"><i class="fa fa-refresh fa-spin"></i></span>
					<div class="pull-right pad_t15 btn_gap">
						<a href="<?php echo $baseUrl;?>/view-profile/<?php echo $this->u_id; ?>" ><button type="button" class="btn btn-default pull-right" style="margin-right:10px;">Cancel</button></a>
						<button type="submit" class="btn btn-primary">Update Profile</button>
					</div>
				</div>
			</div>
			<input type="hidden" name="hid_u_id" id="hid_u_id" value="<?php echo $this->u_id; ?>" />
			<input type="hidden" name="imageId" id="imageId" value="<?php if(isset($this->getUserInfo->u_profile_image) && $this->getUserInfo->u_profile_image != "") { echo $this->getUserInfo->u_profile_image; } ?>" /> 
			<input type="hidden" name="team_members_type" id="team_members_type" value="<?php if(isset($this->getUserInfo->u_team_type) && $this->getUserInfo->u_team_type != "") { echo $this->getUserInfo->u_team_type; } ?>" /> 
		</form>
		</div>
		</div>
	</div>
</div>
<!-- Crop User Profile Image -->
<div class="modal fade" id="crop_user_profile_image" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h3 class="modal-title" style="color:#fff" id="myModalLabel">Upload <span class="sm_hide">Profile</span> Image</h3>
				<span class="profilecropbtn" ><button type="button" class="btn btn-info" onclick="selectCropImage();">Upload</button>&nbsp; <button type="button" class="btn btn-info export" onclick="checkCoords();" style="display:none">Crop</button></span>
			</div>
			<div class="modal-body img_responsive">
				<div id="cropSrcImgContainer" style="min-height:300px;margin-top:30px;">
					<img alt="" src="" id="cropbox" />
				</div>
				<div class="jc_coords">
					<form id="CropForm" method="post" >
						<input type="hidden" id="x" name="x" />
						<input type="hidden" id="y" name="y" />
						<input type="hidden" id="w" name="w" />
						<input type="hidden" id="h" name="h" />
					</form>
				</div>
				<div class="modal-footer">
					<span id="loadCrop"  style="display:none"><i class="fa fa-refresh fa-spin"></i></span>
					<button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancel</button>
				</div>
				<input type="file" id="fileCropInp" name="fileCropInp" style="display:none;"  />
			</div>
		</div>
	</div>
</div>