	<style>
	.tex_lef{
		text-align: left !important;
	}
	</style>
	<?php 
	if(($_SERVER['REQUEST_URI'] != '/') && ($_SERVER['REQUEST_URI'] != '/quotes/trunk/') &&($_SERVER['REQUEST_URI'] != '/ea/quotes/') && (strpos($_SERVER['REQUEST_URI'], 'viewers') == false) && (strpos($_SERVER['REQUEST_URI'], 'search') == false) ){
		require 'right-side-bar1.phtml';			
	}
	
	?>
	<div class="text-center pad_b40" style="background:#fff;"><img src="<?php echo $basePath;?>/images/footerad.png"></div>
	<footer class="main-footer">
        <div class="container">
          <div class="pull-right hidden-xs">
            <b>Design and Developed By <a href="http://aapthitech.com">Aapthitech</a></b>
          </div>
          <strong>Copyright &copy; 2014-2015 <a href="http://aapthitech.com">Aapthitech</a>.</strong> All rights reserved.
        </div><!-- /.container -->
      </footer>
    </div><!-- ./wrapper -->
    <!-- jQuery 2.1.4 -->
	<?php
	//print_r($_SESSION['user']['userId']);exit;
	$uid = 0;	
	if(isset($_SESSION['user']['userId']) && $_SESSION['user']['userId'] != "")
	{
		$uid = $_SESSION['user']['userId'];
	}
	
	?>
	<script>
			var adminBaseUrl 	= '<?php echo $baseUrl; ?>';
			var adminBasePath 	= '<?php echo $basePath; ?>';
			var baseUrl 		= '<?php echo $baseUrl; ?>';
		</script>
    <script src="<?php echo $basePath;?>/js/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="<?php echo $basePath;?>/js/bootstrap.min.js"></script>
    <!-- SlimScroll -->
    <script src="<?php echo $basePath;?>/js/jquery.slimscroll.min.js"></script>
    <!-- AdminLTE App -->
    <script src="<?php echo $basePath;?>/js/app.js"></script>
	<script src="<?php echo $basePath;?>/js/ripples.min.js"></script>
	<script src="<?php echo $basePath;?>/js/material.min.js"></script>
	<script src="<?php echo $basePath;?>/js/oauthpopup.js"></script> 
	<script src="<?php echo $basePath;?>/js/custom.js"></script>
	<script src="<?php echo $basePath;?>/js/isotope.js"></script>
	<script src="<?php echo $basePath;?>/js/common-scripts.js"></script>
	<script src="<?php echo $basePath;?>/js/formValidation.js"></script>
	<script src="<?php echo $basePath;?>/js/bootstrap.js"></script>
	<script src="<?php echo $basePath;?>/js/xdi-Jcrop.min.js"></script>
    <!-- Go to www.addthis.com/dashboard to customize your tools -->
		<!--<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5814492129ef0c92"></script>-->
	<!-- Go to www.addthis.com/dashboard to customize your tools -->
  </body>
</html>

<!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog" >
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content overflow_hidden" >
        <div class="modal-header" style="border-bottom:1px solid #ddd;background:#189def;color:#fff;border-radius:2px 2px 0 0">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">SIGN UP</h4>
        </div>
        <div class="modal-body">
         <form class="form-horizontal" style="margin-top:-30px;" data-fv-message="This value is not valid" data-fv-icon-valid="glyphicon"
						data-fv-icon-invalid="glyphicon"  data-fv-icon-validating="glyphicon glyphicon-refresh"
						method="POST" name="registerForm"  
						id="registerForm"  onSubmit="return signUpUser();" enctype="multipart/form-data">
              <div class="form-group is-empty">
                <label class="col-md-2 control-label" for="inputFullName">Full Name</label>

                <div class="col-md-10">
                  <input type="text" placeholder="Full Name" id="inputFullName" name="inputFullName" class="form-control"  required data-fv-notempty="true" 
								   data-fv-notempty-message="The full name is required" />
				</div>
              </div>
			  <div class="form-group is-empty">
                <label class="col-md-2 control-label" for="inputEmail">Email</label>

                <div class="col-md-10">
                  <input type="email" placeholder="Email" id="inputEmail" name="inputEmail" class="form-control input-lg user_login" required data-fv-regexp="true" data-fv-regexp-regexp="^[_a-z0-9]+(\.[_a-z0-9]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$"  data-fv-regexp-message="The email is not a valid">
				  
                </div>
              </div>
              <div class="form-group">
                <label class="col-md-2 control-label" for="inputPassword">Password</label>
                <div class="col-md-10">
                  <input type="password" placeholder="Password" id="inputPassword" name="inputPassword" class="form-control" required data-fv-notempty-message="The password is required">
                </div>
              </div>
             
              <div class="form-group is-empty">
                <label class="col-md-2 control-label" for="textArea">Textarea</label>

                <div class="col-md-10">
                  <textarea id="textArea" name="textArea" rows="3" class="form-control" required data-fv-notempty-message="The texarea feild is required"></textarea>
                  <span class="help-block">A longer block of help text that breaks onto a new line and may extend beyond one line.</span>
                </div>
              </div>
			  <div class="form-group is-empty is-fileinput">
                <label class="col-md-2 control-label" for="inputFile">File</label>

                <div class="col-md-10">
                  <input type="text" placeholder="Browse..." class="form-control" id="userProfilePic" name="userProfilePic">
                  <input type="file" multiple="" id="inputFile" name="inputFile" onChange="return fileName();">
                </div>
              </div>
			  <span id="errorLogin" style="color:red"></span>
        
        </div>
        <div class="modal-footer">
		<button type="submit" class="btn   btn-raised btn-info" id="signUpBtn">Sign UP</button>
          <button type="button" class="btn btn-default cancel_btn" data-dismiss="modal">Close</button>
        </div>
      </div>
        </form>
    </div>
  </div>
  <!-----forget -->
  
  <div class="modal fade" id="myModal1" role="dialog" >
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content overflow_hidden" >
        <div class="modal-header pop_title">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Forget the password</h4>
        </div>
        <div class="modal-body">
         <form id="forgetPasswordForm" class="form-horizontal" style="margin-top:-30px;"  data-fv-message="This value is not valid" data-fv-icon-valid="glyphicon" data-fv-icon-invalid="glyphicon" data-fv-icon-validating="glyphicon glyphicon-refresh" onSubmit="return CheckForgetEmail();" enctype="multipart/form-data">
            <div class="pop">
			  <div class="form-group is-empty">
                <label class="col-md-3 control-label tex_lef" for="ForgetEmail">Email</label>

                <div class="col-md-9">
                  <input type="text" placeholder="Email" id="ForgetEmail" name="ForgetEmail" class="form-control input-lg user_login" required data-fv-regexp="true" data-fv-regexp-regexp="^[_a-z0-9]+(\.[_a-z0-9]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$"  data-fv-regexp-message="The email is not a valid">
				  
                </div>
              </div>
            </div>
			  
        
        </div>
        <div class="modal-footer mar_r5">
			<div class="col-md-8 text-left">
				<span id="forgeterrorEmail" style="color:red"></span>
				<span id="forgetsucessEmail" style="color:red"></span>
			</div>
			<div class="col-md-2 pull-right">
			<button type="submit" class="btn   btn-raised btn-info" id="checkForgetEmail">Submit</button>
			</div>		
        </div>
      </div>
        </form>
    </div>
  </div>
  
  <!-- change password-->
  <div class="modal fade" id="myModal2" role="dialog" >
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content overflow_hidden" >
        <div class="modal-header pop_title">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
		 
          <h4 class="modal-title">Change Password</h4>
        </div>
        <div class="modal-body">
         <form id="changePasswordForm" name="changePasswordForm" class="form-horizontal" style="margin-top:-30px;"  data-fv-message="This value is not valid" data-fv-icon-valid="glyphicon" data-fv-icon-invalid="glyphicon" data-fv-icon-validating="glyphicon glyphicon-refresh"  onSubmit="return CheckPass();">
            <div class="pop">
			  
              <div class="form-group">
			   <?php 
			   $uid = "";
			   if(isset($_SESSION['user']['displayName']) && $_SESSION['user']['displayName'] != ""){ $uid = $_SESSION['user']['userId']; }?>
			   <input type="hidden" name="hidUser_id" id="hidUser_id" value="<?php echo $uid; ?>">
                <label class="col-md-3 control-label tex_lef" for="inputPassword">Current Password</label>
                <div class="col-md-9">
                  <input type="password" placeholder="Current Password" id="currentPassword" name="currentPassword" class="form-control" required data-fv-notempty-message="The Current Password is required">
                </div>
              </div>
			  <div class="form-group">
                <label class="col-md-3 control-label tex_lef" for="inputPassword">New Password</label>
                <div class="col-md-9">
                  <input type="password" placeholder="Current Password" id="newPassword" name="newPassword" class="form-control" required data-fv-notempty-message="The New Password is required">
                </div>
              </div>
			  <div class="form-group">
                <label class="col-md-3 control-label tex_lef" for="inputPassword">  Confirm Password</label>
                <div class="col-md-9">
                  <input type="password" placeholder="Confirm New Password" id="confirmPassword" name="confirmPassword" class="form-control" required data-fv-notempty-message="The Confirm password is required">
                </div>
              </div>
            </div>
			 
        
        </div>
        <div class="modal-footer mar_r5">
			<div class="col-md-8 text-left">
				<span id="errorPass" style="color:red"></span>
				<span id="sucessPass" style="color:green"></span>
				<i class="fa fa-refresh " aria-hidden="true" id="changeRefresh"></i>
			</div>
			<div class="col-md-2 pull-right">
			<button type="submit" class="btn   btn-raised btn-info" id="updatePass">Update</button> 
			</div>
        </div>
      </div>
        </form>
    </div>
  </div>
  <!-- modal end-->
  <!-- reset change password-->
  <div class="modal fade" id="myModalReset" role="dialog" >
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content overflow_hidden" >
        <div class="modal-header pop_title">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
		 
          <h4 class="modal-title">Reset Password</h4>
        </div>
        <div class="modal-body">
         <form class="form-horizontal" id="resetPasswordForm" style="margin-top:-30px;"  data-fv-message="This value is not valid" data-fv-icon-valid="glyphicon" data-fv-icon-invalid="glyphicon" data-fv-icon-validating="glyphicon glyphicon-refresh"  onSubmit="return ResetPswd();">
            <div class="pop">			  
              
			  <div class="form-group">
                <label class="col-md-3 control-label tex_lef" for="f_newPassword">New Password</label>
                <div class="col-md-9">
                  <input type="password" placeholder="Current Password" id="f_newPassword" name="f_newPassword" class="form-control" required data-fv-notempty-message="The New Password is required">
                </div>
              </div>
			  <div class="form-group">
                <label class="col-md-3 control-label tex_lef" for="f_confirmPassword">  Confirm Password</label>
                <div class="col-md-9">
                  <input type="password" placeholder="Confirm New Password" id="f_confirmPassword" name="f_confirmPassword" class="form-control" required data-fv-notempty-message="The Confirm password is required">
				  <input type="hidden" name="f_UserId" id="f_UserId" />
				  <input type="hidden" name="f_token" id="f_token" />
                </div>
              </div>
            </div>
			 
        
        </div>
        <div class="modal-footer mar_r5">
			<div class="col-md-8 text-left">
				<span id="f_errorPass" style="color:red"></span>
				<span id="f_sucessPass" style="color:green"></span>
			</div>
			<div class="col-md-2 pull-right">
			<button type="submit" class="btn   btn-raised btn-info" id="updateForgotPass">Update</button> 
			</div>
        </div>
      </div>
        </form>
    </div>
  </div>
  
  <!--favourite confirmation modals -->
  <div class="modal fade" id="hidden_common_post_quote" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog modal-sm" role="document">
		<div class="modal-content modla_title_line">
			<div class="modal-header pop_title">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close" title="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title" id="myModalLabel1">Please Login</h4>
		  </div>
		  <div class="modal-body">
			<p><span id="alert_message_post_quote"></span></p>
		  </div>
		  <div class="modal-footer">
			<button  type="button" class="btn   btn-raised btn-info btn-sm"  id="post_quote_cnfrmOk">Ok</button>
		  </div>
		</div>
	  </div>
	</div>
	<!-- end popup-->
  
  <!--favourite confirmation modals -->
  <div class="modal fade" id="hidden_common" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog modal-sm" role="document">
		<div class="modal-content modla_title_line">
			<div class="modal-header pop_title">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close" title="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title" id="myModalLabel">Please Login</h4>
		  </div>
		  <div class="modal-body">
			<p><span id="alert-message"></span></p>
		  </div>
		  <div class="modal-footer">
			<button  type="button" class="btn   btn-raised btn-info btn-sm" data-dismiss="modal" id="cnfrmOk">Ok</button>
		  </div>
		</div>
	  </div>
	</div>
	<!-- end popup-->
	<!-- logout -->
	<div class="modal fade" id="user_logout" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog modal-sm" role="document">
		<div class="modal-content">
		  <div class="modal-header pop_title">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close" title="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title" id="myModalLabel">Logout Confirmation</h4>
		  </div>
		  <div class="modal-body">
			<p>Are you sure you want to logout?</p>
		  </div>
		  <div class="modal-footer mar_r5">
			<button type="button" class="btn btn-default btn-sm active" data-dismiss="modal" >Cancel</button>
			<button type="button" class="btn btn-raised btn-info  btn-sm" onclick="userLogout();">Ok</button>
		  </div>
		</div>
	  </div>
	</div>
	<!--favourites -->
	<div class="modal fade" id="user_Favourite" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog modal-sm" role="document">
		<div class="modal-content">
		  <div class="modal-header pop_title">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close" title="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title" id="myModalLabel">Favourite Confirmation</h4>
		  </div>
		  <div class="modal-body">
			<p>Are you sure you want to continue this process?</p>
			<input type="hidden" name="hid_fav" id="hid_fav" value="" />
			<input type="hidden" name="userSessId" id="userSessId" value="<?php echo $uid; ?>" />
		  </div>
		  <div class="modal-footer mar_r5">
			<button type="button" class="btn btn-default active btn-sm" data-dismiss="modal" >Cancel</button>
			<button type="button" class="btn btn-raised btn-info  btn-sm" onclick="userFavourite();"> Ok </button>
		  </div>
		</div>
	  </div>
	</div>
	
	<div class="modal fade" id="forgot_hidden_common" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog modal-sm" role="document">
		<div class="modal-content">

		  <div class="modal-body">
			<p><span id="f_message"></span></p>
		  </div>
		  <div class="modal-footer">
			<button  type="submit" class="btn   btn-raised btn-info btn-sm" data-dismiss="modal" id="forgot_Ok">Ok</button>
		  </div>
		</div>
	  </div>
	</div>
	<!-- logout -->
	<div class="modal fade" id="user_delete_quote_model" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog modal-sm" role="document">
		<div class="modal-content">
		  <div class="modal-header pop_title">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close" title="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title" id="myModalLabelQuote">Quote delete confirmation</h4>
		  </div>
		  <div class="modal-body">
			<p>Are you sure, you want delete the quote?</p>
		  </div>
		  <input type="hidden" id="hid_d_qc_id" name="hid_d_qc_id" value="">

		  <div class="modal-footer mar_r5">
			<button type="button" class="btn btn-default btn-sm active" data-dismiss="modal" >Cancel</button>
			<button type="button" class="btn btn-raised btn-info  btn-sm" onclick="quoteDeleteUser();">Ok</button>
		  </div>
		</div>
	  </div>
	</div>
	
	<div class="modal fade" id="scoial_hidden_common" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog modal-sm" role="document">
		<div class="modal-content">
		  <div class="modal-header pop_title">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close" title="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title" id="myModalLabel">Email Checking</h4>
		  </div>
		  <div class="modal-body">
			<p><span id="sc_message">User with this email already with us.</span></p>
		  </div>
		  <div class="modal-footer">
			<button  type="submit" class="btn   btn-raised btn-info btn-sm" data-dismiss="modal" id="forgot_Ok">Ok</button>
		  </div>
		</div>
	  </div>
	</div>
<script>
  function socialSharing(url){
	  window.open(url, '_blank');
  }
 /* $(document).ready(function() {
	$("#inputEmail").focus(); 
	$('#registerForm').formValidation(); 
	$('#inputPassword').keypress(function (e) { var key = e.which;	if(key == 13){ signUpUser(); } });
 });  */
 $(document).ready(function() {
$('#registerForm').formValidation().on('success.form.fv', function(e) {
		e.preventDefault();
 });
 
$('#updateProfileForm').formValidation().on('success.form.fv', function(e) {
		e.preventDefault();
 });
 $('#changePasswordForm').formValidation().on('success.form.fv', function(e) {
		e.preventDefault();
 }); 
 $('#resetPasswordForm').formValidation().on('success.form.fv', function(e) {
		e.preventDefault();
 }); 
 $('#login-nav').formValidation().on('success.form.fv', function(e) {
		e.preventDefault();
 }); 
$('#forgetPasswordForm').formValidation().on('success.form.fv', function(e) {	
		e.preventDefault();
 }); 
 
	$('#postAQuoteForm').formValidation().on('success.form.fv', function(e) {
		e.preventDefault();
	});		
 });
 
</script>
<script>
var _URL = window.URL || window.webkitURL;
	function showCropPopup(cropType){
		$("#l_i_c").hide();
		$('#cropSrcImgContainer').html('<img alt="" src="" id="cropbox" />');
		$('.export').hide();
		$('#fileCropInp').val("");
		
		$('#crop_user_profile_image').modal('show');		
	}
	function showQuoteCropPopup(cropType){
		$('#cropSrcImgContainer').html('<img alt="" src="" id="cropbox" />');
		$('.export').hide();
		$('#QuoteFileCropInp').val("");
		$('#crop_quote_image').modal('show');			
	}
	function selectCropImage(){
		$('#fileCropInp').click();
	}
	function selectQuoteCropImage(){
		$('#QuoteFileCropInp').click();
	}
	$('#fileCropInp').change(function(click){
		 showCropButton(this);
	});
	$('#QuoteFileCropInp').change(function(click){
		 showQuoteCropButton(this);
	});
	
	function showCropButton(input){
		var imageOrNot = input.files[0].name.split('.');
		var extentionName = imageOrNot[1].toLowerCase();
		if(extentionName == "jpeg" || extentionName == "jpg" || extentionName == "jpe" || extentionName == "gif" || extentionName == "png")
		{			
			var crop_width=0;
			var crop_height=0;
			var file, img;
			if ((file = input.files[0])) {
				img = new Image();
				img.src = _URL.createObjectURL(file);
				img.onload = function() {
					$('#upload_image_blank').hide();
					crop_width=this.width;
					crop_height=this.height;
					$('.export').show();
					cropImagePredefinedBothQ(crop_width,crop_height,img.src);
					 /* if(this.height <= '200' && this.width >= '600' ){
						 $('.export').show();
						 cropImagePredefinedBothQ(crop_width,crop_height,img.src);
					 }else{
						 $('#cropSrcImgContainer').html('<img alt="" src="" id="cropbox" />');
						 $('.export').hide();
						 $('#fileCropInp').val("");
						 alert("Please upload image size is less than 200x600");
					 }  */
					   $('.export').show();
						 cropImagePredefinedBothQ(crop_width,crop_height,img.src);
				};
			}
		}else{
			alert("Please upload images only");
		}
	}
	var jcropminLoaded = 0;
	function cropImagePredefinedBothQ(width,height,src){
		if( ! parseInt(jcropminLoaded) ){
			$('#cropbox').attr('src', src);
			$.getScript( adminBasePath+"/js/xdi-Jcrop.min.js" ).done(function( script, textStatus ){
				jcropminLoaded = 1;
				jQuery(function(){
					jQuery('#cropbox').Jcrop({
						minSize :[200,200],
						aspectRatio: 1,
						setSelect: [0,0,200,200],
						allowResize: true,
						allowSelect : true,
						onChange: updateCoords,
						rotate : 90
					});
				});
			});
		}
		else{
			$('#cropbox').remove();
			var cropBoxImg = $('<img src="" id="cropbox" alt="Image appears here" />');
			$('#cropSrcImgContainer').empty().append(cropBoxImg);
			$('#cropbox').attr('src', src);
			jQuery(function(){
				jQuery('#cropbox').Jcrop({
					minSize :[200,200],
					aspectRatio: 1,
					setSelect: [0,0,200,200],
					allowResize: true,
					allowSelect : true,
					onChange: updateCoords,
					rotate : 90
				});
			});
		}
	}
	function updateCoords(c){
		var ratioW = $('#cropbox')[0].naturalWidth / $('#cropbox').width();
		var ratioH = $('#cropbox')[0].naturalHeight / $('#cropbox').height();
		var currentRatio = Math.min(ratioW, ratioH);
        jQuery('#x').val(Math.round(c.x * currentRatio));
        jQuery('#y').val(Math.round(c.y * currentRatio));
        jQuery('#w').val(Math.round(c.w * currentRatio));
        jQuery('#h').val(Math.round(c.h * currentRatio));
	}
	function checkCoords(){
		if( parseInt(jQuery('#w').val()) > 0 ){
			$("#l_i_c").show();
			var x=jQuery('#x').val();
			var y=jQuery('#y').val();
			var w=jQuery('#w').val();
			var h=jQuery('#h').val();
			var cropTypeValue 	= $('#hidCropType').val();
			var existinImageId = $('#userImg').val();
			var catImageBasicUploadUrl = adminBaseUrl+'upload-profile-image';
			var file_data = $('#fileCropInp').prop('files')[0];
			var form_data = new FormData();
			form_data.append('fileCropInp', file_data);
			form_data.append('croppedX', x);
			form_data.append('croppedY', y);
			form_data.append('croppedNewWidth', w);
			form_data.append('croppedNewHeight', h);
			form_data.append('userImg',existinImageId);
			$('#loadCrop').show();
			$.ajax({
				url: catImageBasicUploadUrl,
				cache: false,
				contentType: false,
				processData: false,
				data: form_data,                         
				type: 'post',
				dataType:'json',
				success: function(data){
					console.log(data.imageName);
					var newCatImageFullPath = adminBasePath+'/uploads/'+data.imageName;
					$("#l_i_c").hide();
					$('#uploadedProfileImage').attr('src', newCatImageFullPath);
					//$('#userImg').val(data.imageName);
					$('#loadCrop').hide();
					$('#cropSrcImgContainer').html('<img alt="" src="" id="cropbox" />');
					$('.export').hide();
					$('#fileCropInp').val("");
					$('#crop_user_profile_image').modal('hide');
					/* if(u_ut_id == 4){ */
						$('#userPic').attr('src', newCatImageFullPath);
						$('#userImg').val( data.imageName );
					/* } */
				}
			});
		}else{
			alert('Please select a crop region then press submit.');
		}
	}
	
	
	
	
	function showQuoteCropButton(input){
		var imageOrNot = input.files[0].name.split('.');
		var extentionName = imageOrNot[1].toLowerCase();
		if(extentionName == "jpeg" || extentionName == "jpg" || extentionName == "jpe" || extentionName == "gif" || extentionName == "png")
		{			
			var crop_width=0;
			var crop_height=0;
			var file, img;
			if ((file = input.files[0])) {
				img = new Image();
				img.src = _URL.createObjectURL(file);
				img.onload = function() {
					$('#upload_image_blank').hide();
					crop_width=this.width;
					crop_height=this.height;
					$('.export').show();
					cropQuoteImagePredefinedBothQ(crop_width,crop_height,img.src);
				};
			}
		}else{
			alert("Please upload images only");
		}
	}
	var jcropminLoaded1 = 0;
	function cropQuoteImagePredefinedBothQ(width,height,src){
		if( ! parseInt(jcropminLoaded1) ){
			$('#cropbox').attr('src', src);
			$.getScript( adminBasePath+"/js/xdi-Jcrop.min.js" ).done(function( script, textStatus ){
				jcropminLoaded1 = 1;
				jQuery(function(){
					jQuery('#cropbox').Jcrop({
						minSize :[200,200],
						aspectRatio: 1.8,
						setSelect: [0,0,720,400],
						allowResize: true,
						allowSelect : true,
						onChange: updateQuoteCoords,
						rotate : 90
					});
				});
			});
		}
		else{
			$('#cropbox').remove();
			var cropBoxImg = $('<img src="" id="cropbox" alt="Image appears here" />');
			$('#cropSrcImgContainer').empty().append(cropBoxImg);
			$('#cropbox').attr('src', src);
			jQuery(function(){
				jQuery('#cropbox').Jcrop({
					minSize :[200,200],
					aspectRatio: 1.8,
					setSelect: [0,0,720,400],
					allowResize: true,
					allowSelect : true,
					onChange: updateQuoteCoords,
					rotate : 90
				});
			});
		}
	}
	function updateQuoteCoords(c){
		var ratioW = $('#cropbox')[0].naturalWidth / $('#cropbox').width();
		var ratioH = $('#cropbox')[0].naturalHeight / $('#cropbox').height();
		var currentRatio = Math.min(ratioW, ratioH);
        jQuery('#x').val(Math.round(c.x * currentRatio));
        jQuery('#y').val(Math.round(c.y * currentRatio));
        jQuery('#w').val(Math.round(c.w * currentRatio));
        jQuery('#h').val(Math.round(c.h * currentRatio));
	}
	function checkQuoteCoords(){
		if( parseInt(jQuery('#w').val()) > 0 ){
			var x=jQuery('#x').val();
			var y=jQuery('#y').val();
			var w=jQuery('#w').val();
			var h=jQuery('#h').val();
			var cropTypeValue 	= $('#hidCropType').val();
			var existinImageId = $('#image').val();
			var catImageBasicUploadUrl = adminBaseUrl+'upload-quote-image';
			var file_data = $('#QuoteFileCropInp').prop('files')[0];
			var form_data = new FormData();
			form_data.append('QuoteFileCropInp', file_data);
			form_data.append('croppedX', x);
			form_data.append('croppedY', y);
			form_data.append('croppedNewWidth', w);
			form_data.append('croppedNewHeight', h);
			form_data.append('image',existinImageId);
			$('#loadCrop').show();
			$.ajax({
				url: catImageBasicUploadUrl,
				cache: false,
				contentType: false,
				processData: false,
				data: form_data,                         
				type: 'post',
				dataType:'json',
				success: function(data){
					console.log(data.imageName);
					var newCatImageFullPath = adminBasePath+'/quotes/'+data.imageName;
					$('#uploadedProfileImage').attr('src', newCatImageFullPath);
					$('#loadCrop').hide();
					$('#cropSrcImgContainer').html('<img alt="" src="" id="cropbox" />');
					$('.export').hide();
					$('#QuoteFileCropInp').val("");
					$('#crop_quote_image').modal('hide');
					/* if(u_ut_id == 4){ */
						$('#image').val( data.imageName );
					/* } */
				}
			});
		}else{
			alert('Please select a crop region then press submit.');
		}
	}
	function loginPostLogin(){
		document.getElementById("login-dp").style.display="block";
		$('#hidvalue').val(1);
	}
	$(document).ready(function(){
		$("#userSignInBtn").click(function(){
			$('#hidvalue').val(0);
			$('#login-dp').slideToggle();
		});		
	});
	$(document).on("click", function (event) {
		event.stopPropagation();
		if($('#hidvalue').val()!=1){
			document.getElementById("login-dp").style.display="none";
		}
		$('#hidvalue').val(0);
	});

	$('#facebook').oauthpopup({
		path: baseUrl+'social-sign-in?id=facebook',
		width:650,
		height:350,
	});
	$.ajax({
		type		:	'GET',
		url			:  	baseUrl+'social-sign-in?id=fdata',
		dataType	: 	"json",
		success: function(data){
			if(data.output != '1'){	
				console.log("Aapthi Technologies");return false;
			}else if(data.output=='1'){				
				var logFBUrl = data.fbdata.u_social_logout;
				$('#scoial_hidden_common').modal('show');
				fbLogout(logFBUrl);	
				setTimeout(function(){						
					$.ajax({
						type 		: 	"GET",
						url			:	baseUrl+"logout?id=google",
						success		: 	function( response ){	
						}
					});
				}, 1500);		
			}
		}
	});
	function fbLogout(logFBUrl){		
		$.ajax({
			type 		: 	"GET",
			jsonp		: 	"callback",
			dataType 	: 	"jsonp",
			url			:	logFBUrl,
			success		: 	function( response ){	
				console.log('Success');
			}
		});		
	}
	$('#gplus').oauthpopup({
		path: baseUrl+'social-sign-in?id=google',
		width:650,
		height:350,
	});
	$.ajax({
		type		:	'GET',
		url			: baseUrl+'social-sign-in?id=google_login',
		dataType	: 	"json",
		success: function(data){
			if(data.output!= '1'){
				console.log('Success');
			}else if(data.output=='1'){				
			  setTimeout(function(){						
					$.ajax({
						type 		: 	"GET",
						url			:	baseUrl+"logout?id=google",
						success		: 	function( response ){	
						}
					});
					$.ajax({
						type 		: 	"GET",
						jsonp		: 	"callback",
						dataType 	: 	"jsonp",
						url			:	"https://www.google.com/accounts/Logout",
						success		: 	function( response ){
							console.log(response);
							// $('#sc_message').html('show');	
							$('#scoial_hidden_common').modal('show');	
						}
					});	
				}, 1500);
			}				
		}
	});
</script>
