<script>
	var basePath     	= '<?php echo $basePath; ?>';
	var baseUrl 		= '<?php echo $baseUrl; ?>';
</script>
<script src="<?php echo $basePath;?>/js/uts-jquery.js"></script>
<script src="<?php echo $basePath;?>/js/bootstrap.min.js"></script>
<script src="<?php echo $basePath;?>/js/commonfunctions.js"></script>
<script src="<?php echo $basePath;?>/js/formValidation.js"></script>
<script src="<?php echo $basePath;?>/js/uts-load-functions.js"></script>
<script src="<?php echo $basePath;?>/js/uts-moment.min.js"></script>
<script src="<?php echo $basePath;?>/js/bootstrap.js"></script>
<script src="<?php echo $basePath;?>/js/uts-bootstrap-datetimepicker.min.js"></script>
<div class="modal fade" id="schduleErrorPop" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
			<h3 class="modal-title" id="lineModalLabel">Warnning </h3>
		</div>
		<div class="modal-body">
			<p>Plase fill date & time.</p>
		</div>
		<div class="modal-footer">
			<div class="btn-group btn-group-justified" role="group" aria-label="group button">
				<div class="btn-group" role="group">
					<button type="button" class="btn btn-default" data-dismiss="modal"  role="button">Close</button>
				</div>
			</div>
		</div>
	</div>
  </div>
</div>


  
  <!-- change password-->
  <div class="modal fade" id="changePwdModal" role="dialog" >
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content" >
        <div class="modal-header" style="border-bottom:1px solid #ddd;background:#189def;color:#fff;border-radius:2px 2px 0 0">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
	      <h4 class="modal-title">Change Password</h4>
        </div>
        <div class="modal-body">
         <form id="changePasswordForm" name="changePasswordForm" class="form-horizontal"  data-fv-message="This value is not valid" data-fv-icon-valid="glyphicon" data-fv-icon-invalid="glyphicon" data-fv-icon-validating="glyphicon glyphicon-refresh"  onSubmit="return CheckPass();">
            <div class="pop">
			  
              <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter a email">
			   <?php 
			   $uid = "";
			   if(isset($_SESSION['user']['user_id']) && $_SESSION['user']['user_id'] != ""){ $uid = $_SESSION['user']['userId']; }?>
			   <input type="hidden" name="hidUser_id" id="hidUser_id" value="<?php echo $uid; ?>">
                <label class="col-md-3 control-label tex_lef" for="inputPassword">Current Password</label>
                <div class="col-md-9">
                  <input type="password" placeholder="Current Password" id="currentPassword" name="currentPassword" class="form-control" required data-fv-notempty-message="The Current Password is required">
                </div>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Enter a password">
			  <div class="form-group">
                <label class="col-md-3 control-label tex_lef" for="inputPassword">New Password</label>
                <div class="col-md-9">
                  <input type="password" placeholder="Current Password" id="newPassword" name="newPassword" class="form-control" required data-fv-notempty-message="The New Password is required">
                </div>
              </div>
            </form>
		</div>
		<div class="modal-footer">
			<div class="btn-group btn-group-justified" role="group" aria-label="group button">
				<div class="btn-group" role="group">
					<button type="button" class="btn btn-default" data-dismiss="modal"  role="button">Close</button>
				</div>
				<div class="btn-group btn-delete hidden" role="group">
					<button type="button" id="delImage" class="btn btn-default btn-hover-red" data-dismiss="modal"  role="button">Delete</button>
				</div>
				<div class="btn-group" role="group">
					<button type="button" id="saveImage" class="btn btn-default btn-hover-green" data-action="save" role="button">Submit</button>
				</div>
			  <div class="form-group">
                <label class="col-md-3 control-label tex_lef" for="inputPassword">  Confirm Password</label>
                <div class="col-md-9">
                  <input type="password" placeholder="Confirm New Password" id="confirmPassword" name="confirmPassword" class="form-control" required data-fv-notempty-message="The Confirm password is required">
                </div>
              </div>
            </div>
			 
        
        </div>
        <div class="modal-footer mar_r5">
			<div class="col-md-8 text-left">
				<span id="errorPass" style="color:red"></span>
				<span id="sucessPass" style="color:green"></span>
				<i class="fa fa-refresh " aria-hidden="true" id="changeRefresh"></i>
			</div>
		</div>
	</div>
			<div class="col-md-2 pull-right">
			<button type="submit" class="btn   btn-raised btn-info" id="updatePass">Update</button> 
			</div>
        </div>
      </div>
        </form>
    </div>
  </div>
</div>
  <!-- modal end-->
<script>
function changeQ(){
	$("#changePwdModal").modal("show");
}
$(document).ready(function() {
	$('#changePasswordForm').formValidation().on('success.form.fv', function(e, data) {	
		e.preventDefault();
	});
});
(function($) {
    $(function() {
		$('#sc-date').datetimepicker({
			 minDate: $.now(),
			 format: 'YYYY-MM-DD'
		});
		$('input[id^=psd]').datetimepicker({
			 format: 'YYYY-MM-DD'
		});
		$('input[id^=ped]').datetimepicker({
			 format: 'YYYY-MM-DD'
		});
    });
})(jQuery);
</script>