<script>
	var basePath     	= '<?php echo $basePath; ?>';
	var baseUrl 		= '<?php echo $baseUrl; ?>';
</script>
<script src="<?php echo $basePath;?>/js/uts-jquery.js"></script>
<script src="<?php echo $basePath;?>/js/bootstrap.min.js"></script>
<script src="<?php echo $basePath;?>/js/commonfunctions.js"></script>
<script src="<?php echo $basePath;?>/js/formValidation.js"></script>
<script src="<?php echo $basePath;?>/js/bootstrap.js"></script>
