<?php
	$header			=	$this->action('Application\Controller\IndexController', 'headerAction');
	$baseUrl 		= 	$header->headerarray['baseUrl'];
	$basePath 		= 	$header->headerarray['basePath'];
?>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
    <title>UmpireTaxSolutions</title>
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link href="<?php echo $basePath;?>/css/bootstrap.min.css" rel="stylesheet">
	<link href="<?php echo $basePath;?>/css/sb-admin.css" rel="stylesheet">
	<link href="<?php echo $basePath;?>/css/umpire.css" rel="stylesheet">
	<link href="<?php echo $basePath;?>/css/morris.css" rel="stylesheet">
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
  </head>
  <body class="bac_img">
    <div id="wrapper">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $baseUrl;?>dashboard"><img src="<?php echo $basePath;?>/img/logo.png"></a>
            </div>
            <ul class="nav navbar-right top-nav">
					<div class="btn_site"> Filing Status: <?php if(isset($_SESSION["user"]["file_name"]) && $_SESSION["user"]["file_name"]!="") { echo $_SESSION["user"]["file_name"]; }else{ echo "No Status"; }?> </div>
					<div class="btn_site" >Make Payment</div>
            </ul>
            <?php include('left-menu.phtml'); ?>
        </nav>
