<footer class="top_footer">
	<div class="footer" id="footer">
		<div class="container">
			<div class="row top_foot">
				<div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
					<ul class="bord_rigt">
						<li> <a href="<?php echo $baseUrl;?>"> Home </a> </li>
						<li> <a href="<?php echo $baseUrl;?>firm-profile"> Profile </a> </li>
						<li> <a href="<?php echo $baseUrl;?>tax-center"> Tax Center </a> </li>
					</ul>
				</div>
				<div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
					<ul class="bord_rigt">
						<li> <a href="<?php echo $baseUrl;?>testimonial"> Testimonials </a> </li>
						<li> <a href="<?php echo $baseUrl;?>carrers"> Carrers </a> </li>
						<li> <a href="<?php echo $baseUrl;?>contact-us"> ContactUs </a> </li>
						
					</ul>
				</div>
				<div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
					<ul class="bord_rigt">
						<li> <a href="<?php echo $baseUrl;?>services"> Services </a> </li>
						<li> <a href="<?php echo $baseUrl;?>privacy-policy"> Privacy Policy </a> </li>
						<li> <a href="<?php echo $baseUrl;?>terms-conditions"> Terms & Conditions </a> </li>
					</ul>
				</div>
				<div class="col-lg-6  col-md-6 col-sm-6 col-xs-12 ">
				   <img class="img-responsive"src="<?php echo $basePath;?>/img/add.png">
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="bor_bot">
	</div>
	</div>
	<div class="footer-bottom mar_t10">
		<div class="container">
			<p class="pull-right"> Copyright © Footer 2014. All right reserved. </p>
		</div>
	</div>
</footer>
<!-- Register -->
	<div class="modal fade" id="regModal" role="dialog" >
		<div class="modal-dialog">
			<div class="modal-content" >
				<div class="modal-header" style="border-bottom:1px solid #ddd;background:#189def;color:#fff;border-radius:2px 2px 0 0">
					<button type="button" class="close" onClick="closeSignup();">&times;</button>
					<h4 class="modal-title">Sign Up</h4>
				</div>
				<div class="modal-body">
					<form class="form-horizontal" data-fv-message="This value is not valid" data-fv-icon-valid="glyphicon" data-fv-icon-invalid="glyphicon"  data-fv-icon-validating="glyphicon glyphicon-refresh"	method="POST" name="registerForm" id="registerForm"  onSubmit="return signUpUser('registerForm');" enctype="multipart/form-data">
						<div class="form-group">
							<div class="col-md-12">
							<input type="text" placeholder="Enter First name" id="inputFirstname" name="inputFirstname" class="form-control"  required data-fv-notempty="true" 
							data-fv-notempty-message="The full name is required" />
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-12">
							<input type="text" placeholder="Enter Last name" id="inputLastname" name="inputLastname" class="form-control"  required data-fv-notempty="true" 
							data-fv-notempty-message="The last name is required" />
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-12">
							<input type="text" placeholder="Enter Occupation" id="occupation" name="occupation" class="form-control user_login" required data-fv-notempty-message="The occupation is required">
								
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-12">
								<input type="text" placeholder="Enter Phone number" id="phone" name="phone" class="form-control user_login" required data-fv-notempty-message="Please enter a phone" data-fv-integer="true" data-fv-integer-message="The value is not an integer" maxlength="10"
							data-fv-stringlength data-fv-stringlength-min="10" data-fv-stringlength-message="Phone number must be 10 digits only" maxlength="10">
								<span id="phoneChecking" style="color:red;"></span>
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-12">
								<input type="text" placeholder="Enter Email id" id="inputEmail" name="inputEmail" class="form-control user_login" required data-fv-notempty-message="The email address is required" 
								data-fv-regexp="true"  data-fv-regexp-regexp="^[_a-z0-9]+(\.[_a-z0-9]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$"  data-fv-regexp-message="The email is not a valid">
								<span id="emailChecking" style="color:red;"></span>
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-12">
								<input type="password" placeholder="Enter Password " id="inputPassword" name="inputPassword" class="form-control" required data-fv-notempty-message="The password is required" maxlength="6"
							data-fv-stringlength data-fv-stringlength-min="6" data-fv-stringlength-message="Password must be at least 6 characters">
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-12">
								<input type="password" placeholder="Enter Confirm password" id="userpwd" name="userpwd" class="form-control" required data-fv-notempty-message="The confirm password is required" data-fv-identical="true" data-fv-identical-field="inputPassword" data-fv-identical-message="Password and the confirmation password are not matching">
							</div>
						</div>
						<div class="form-group">
							<p class="col-md-12 control-label" style=" text-align:left;" align="justify">
								By clicking Submit, you agree to our <a href="<?php echo $baseUrl;?>terms-conditions">Terms </a> and that you have read our Data Policy, including our Cookie Use.
							</p>
						</div>
						<div class="modal-footer mar_r5">
							<div class="col-md-8 text-left">
								
								<span id="forgeterrorEmail" style="color:red"></span>
								<span id="forgetsucessEmail" style="color:red"></span>
							</div><br/>
							<div class="col-md-2 pull-right">
								<button type="submit" class="btn   btn-raised btn-info" id="checkForgetEmail">Submit</button>
							</div>		
						</div>
					</form>	
				</div>				
			</div>
		</div>
	</div>
<!-- End -->


<!-- Login -->
	<div class="modal fade" id="loginModal" role="dialog" >
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h3 class="modal-title" id="lineModalLabel">Login</h3>
				</div>
				<div class="modal-body">
					<form id="loginForm" name="loginForm" class="form-horizontal"  data-fv-message="This value is not valid" data-fv-icon-valid="glyphicon" data-fv-icon-invalid="glyphicon" data-fv-icon-validating="glyphicon glyphicon-refresh" onSubmit="return loginChecking('loginForm');" enctype="multipart/form-data">
						<div class="pop">
							<div class="form-group">
								<label class="col-md-3 control-label tex_lef" for="LoginEmail">Email</label>
								<div class="col-md-9">
									<input type="text" placeholder="Enter your email address" 
									id="useremail" name="useremail" class="form-control user_login" required data-fv-regexp="true" data-fv-regexp-regexp="^[_a-z0-9]+(\.[_a-z0-9]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$"  data-fv-regexp-message="The email is not a valid">
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-3 control-label tex_lef" for="LoginPassword">Password</label>
								<div class="col-md-9">
								  <input type="password" placeholder="Enter your password" id="userpassword" name="userpassword" class="form-control" required data-fv-notempty-message="The password is required">
								</div>
							</div>
						</div>
						<div class="form-group">
							<span id="errorLogin" style="margin-left:66px;color:red"></span>
						</div>
						<div class="modal-footer mar_r5">
							<div class="mar_t10">
								<div class="col-md-8">
								<a style="color:#222;" href="javascript:void(0);" id='forget_popup' onClick="forgetForm();" class=""><span class="col-md-6 control-label tex_lef" for="LoginPassword">Forgot password?</span></a>
								</div>
								<div class="col-md-2 pull-right">
									<button type="submit" class="btn   btn-raised btn-info" id="checkForgetEmail">Submit</button>
								</div>		
							</div>		
						</div>
					</form>
				</div>					
			</div>
		</div>
	</div>
<!-- End -->
<!-- Forgot Password -->
	<div class="modal fade" id="forgotpasswordModal" role="dialog" data-backdrop="static" data-keyboard="false">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" onClick = "closeForget()">&times;</button>
					<h3 class="modal-title" id="lineModalLabel">Forget the password</h3>
				</div>
				<div class="modal-body">
					<form id="forgetPasswordForm" class="form-horizontal"  data-fv-message="This value is not valid" data-fv-icon-valid="glyphicon" data-fv-icon-invalid="glyphicon" data-fv-icon-validating="glyphicon glyphicon-refresh" onSubmit="CheckForgetEmail();" enctype="multipart/form-data">
						<div class="pop">
							<div class="form-group is-empty">
								<label class="col-md-3 control-label tex_lef" for="ForgetEmail">Email</label>
								<div class="col-md-9">
									<input type="text" placeholder="Email" id="ForgetEmail" name="ForgetEmail" class="form-control  user_login" required data-fv-regexp="true" data-fv-notempty-message="The email is required" data-fv-regexp-regexp="^[_a-z0-9]+(\.[_a-z0-9]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$"  data-fv-regexp-message="The email is not a valid">
								</div>
							</div>
						</div>
						<div class="modal-footer mar_r5">
							<div class="col-md-8 text-left">
								<span id="forgetMessage" style="color:red"></span>
								<span id="forgetSuccMessage"></span>
							</div><br/>
							<div class="col-md-2 pull-right">
								<button type="submit" class="btn   btn-raised btn-info" id="checkForgetEmail">Submit</button>
							</div>		
						</div>
					</form>
				</div>					
			</div>
		</div>
	</div>
<!-- End -->
<?php	
// Forget Password Code
	$emailfwdvalue = 0;
	$fuid          = 0;
	if(isset($_GET['reset']) && $_GET['reset']!=""){
		if($_GET['reset']==1){
			$emailfwdvalue = 1;
			if(isset($_GET['uid']) && $_GET['uid']!=""){
				$fuid   = $_GET['uid'];
				$ftoken = $_GET['token'];
			}else{
				$fuid   = 0;
				$ftoken = 0;
			}
		}else{
			$emailfwdvalue = 0;
		}
	}else{
		$emailfwdvalue = 0;
		$fuid          = 0;
		$ftoken        = 0;
	}
?>	
<input type="hidden" id="verifyfemail" name="verifyfemail" value="<?php echo $emailfwdvalue; ?>">
<input type="hidden" id="uidfemail" name="uidfemail" value="<?php echo $fuid; ?>">	
<input type="hidden" id="uidftoken" name="uidftoken" value="<?php echo $ftoken; ?>">

<?php	
// Sign up Code
	$emailsingupvalue = 0;
	$uid          = 0;	
	if(isset($_GET['auth']) && $_GET['auth']!=""){
		if($_GET['auth']==1){
			$emailsingupvalue = 1;
			if(isset($_GET['regid']) && $_GET['regid']!=""){
				$udata   = base64_decode($_GET['regid']);
				$exPlode = explode('UTS-',$udata);
				$uid = $exPlode[1];
			}else{
				$uid   = 0;
			}
		}else{
			$emailsingupvalue = 0;
		}
	}else{
		$emailsingupvalue = 0;
		$uid              = 0;
	}
?>	
<input type="hidden" id="emailsgverify" name="emailsgverify" value="<?php echo $emailsingupvalue; ?>">
<input type="hidden" id="uidsg" name="uidsg" value="<?php echo $uid; ?>">	



 <!-- reset change password-->
  <div class="modal fade" id="myModalReset" role="dialog" >
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content overflow_hidden" >
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
		 
          <h4 class="modal-title">Reset Password</h4>
        </div>
        <div class="modal-body">
         <form class="form-horizontal" id="resetPasswordForm"  data-fv-message="This value is not valid" data-fv-icon-valid="glyphicon" data-fv-icon-invalid="glyphicon" data-fv-icon-validating="glyphicon glyphicon-refresh"  onSubmit="return resetPasswordFun();">
            <div class="pop">			  
              
			  <div class="form-group">
                <label class="col-md-3 control-label tex_lef" for="f_newPassword">New Password</label>
                <div class="col-md-9">
                  <input type="password" placeholder="Current Password" id="f_newPassword" name="f_newPassword" class="form-control" required data-fv-notempty-message="The New Password is required">
                </div>
              </div>
			  <div class="form-group">
                <label class="col-md-3 control-label tex_lef" for="f_confirmPassword">  Confirm Password</label>
                <div class="col-md-9">
                  <input type="password" placeholder="Confirm New Password" id="f_confirmPassword" name="f_confirmPassword" class="form-control" required data-fv-notempty-message="The Confirm password is required">
				  <input type="hidden" name="f_UserId" id="f_UserId" />
				  <input type="hidden" name="f_token" id="f_token" />
                </div>
              </div>
            </div>        
        </div>
        <div class="modal-footer mar_r5">
			<div class="col-md-8 text-left">
				<span id="f_errorPass" style="color:red"></span>
				<span id="f_sucessPass" style="color:green"></span>
			</div>
			<div class="col-md-2 pull-right">
			<button type="submit" class="btn   btn-raised btn-info" id="updateForgotPass">Update</button> 
			</div>
        </div>
      </div>
        </form>
    </div>
  </div>
<div class="modal fade" id="forgot_hidden_common" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-sm" role="document">
	<div class="modal-content">
	 <div class="modal-header pop_title">
		<button type="button" class="close" data-dismiss="modal" aria-label="Close" title="Close"><span aria-hidden="true">&times;</span></button>
		<h4 class="modal-title" id="myModalLabel">Reset Confirmation</h4>
	  </div>	
	  <div class="modal-body">
		<p><span id="f_message"></span></p>
	  </div>
	  <div class="modal-footer">
		<button  type="submit" class="btn   btn-raised btn-info btn-sm" data-dismiss="modal" id="forgot_Ok">Ok</button>
	  </div>
	</div>
  </div>
</div>

<div class="modal fade" id="sg_hidden_common" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-sm" role="document">
	<div class="modal-content">
	 <div class="modal-header pop_title">
		<button type="button" class="close" data-dismiss="modal" aria-label="Close" title="Close"><span aria-hidden="true">&times;</span></button>
		<h4 class="modal-title" id="myModalLabel">Registration Confirmation</h4>
	  </div>	
	  <div class="modal-body">
		<p><span id="sgu_message"></span></p>
	  </div>
	  <div class="modal-footer">
		<button  type="submit" class="btn   btn-raised btn-info btn-sm" data-dismiss="modal" id="forgot_Ok">Ok</button>
	  </div>
	</div>
  </div>
</div>

		<script>
			var basePath     	= '<?php echo $basePath; ?>';
			var baseUrl 		= '<?php echo $baseUrl; ?>';
		</script>
		<script src="<?php echo $basePath;?>/js/uts-jquery.js"></script>
		<script src="<?php echo $basePath;?>/js/bootstrap.min.js"></script>
		<script src="<?php echo $basePath;?>/js/commonfunctions.js"></script>
		<script src="<?php echo $basePath;?>/js/formValidation.js"></script>
		<script src="<?php echo $basePath;?>/js/bootstrap.js"></script>

		<script>
			$('.carousel').carousel({
				interval: 5000 
			});
			
			
		$(document).ready(function() {
			$('#loginForm,#registerForm,#forgetPasswordForm,#referFriendForm,#resetPasswordForm').formValidation().on('success.form.fv', function(e, data) {	
				e.preventDefault();
			});
		});
		function loginChecking(jForm){ 
			var d 		= new Date();
			var time 	= d.getTime();
			$("#loginForm").formValidation().on('success.form.fv', function(e) {
				e.stopImmediatePropagation();
				var u_email    = $("#useremail").val();
				var u_password = $("#userpassword").val();
				$.ajax({
					type:'POST',
					url:  baseUrl+'checking-login?sRch='+time,
					data:{u_email:u_email,u_password:u_password},
					success: function(data){
						$("#errorLogin").html('');
						if(data.output == "emailnotinrecord"){
							$("#errorLogin").html('Entered email is not in records');
						}else if(data.output == "fail"){	
							$("#errorLogin").html('Please email is requried');					
						}else if(data.output == "wrongdeatils"){
							$("#errorLogin").html('Entered email or password are wrong');	
						}else if(data.output == "success"){
							window.location = baseUrl+'dashboard';
						}
					}
				});
				e.preventDefault();	
			});
		}
		function closeSignup(){
			$('#registerForm').formValidation('resetForm', true);
			$('#regModal').modal('hide');
			$("#emailChecking").html("");
		}
		function signUpUser(JFrom){
			var d 		= new Date();
			var time 	= d.getTime();
			$("#registerForm").formValidation().on('success.form.fv', function(e) {
				e.stopImmediatePropagation();
					var inputEmail     = $("#inputEmail").val();
					var userpwd        = $("#userpwd").val();
					var inputFirstname = $("#inputFirstname").val();
					var inputLastname  = $("#inputLastname").val();
					var occupation     = $("#occupation").val();
					var phone          = $("#phone").val();
					$("#loadMes").html("Loading...");
					$.ajax({
						type		:   'POST',
						url			:  	baseUrl+'sign-up?srch='+time,
						dataType	: 	"json",
						data:{inputEmail:inputEmail,userpwd:userpwd,inputFirstname:inputFirstname,inputLastname:inputLastname,occupation:occupation},
						success: function(data){
							$("#loadMes").html("");
							if(data.output == 'success'){
								$("#emailChecking").html("");
								$('#registerForm').formValidation('resetForm', true);
								$('#regModal').modal('hide');
								$('#successForgetPopUp').modal('show');
								$('#message').html('Registration Successfull.\nPlease check your mail box to validate your email id.');
							}else if(data.output == 'emailexists'){
								$("#emailChecking").html("Email id already exists");
							}else if(data.output == 'notsuccess'){
								$("#emailChecking").html("Email id is required");
							}
						}
					});
				
				e.preventDefault();	
			});
		}
		
		
		function forgetForm(){
			$('#forgetMessage').html('');
			$('#forgetSuccMessage').html('');
			$('#loginModal').modal('hide');
			$('#forgotpasswordModal').modal('show');
		}
		function closeForget(){
			$('#forgetMessage').html('');
			$('#forgetSuccMessage').html('');
			$('#forgotpasswordModal').formValidation('resetForm', true);
			$('#forgotpasswordModal').modal('hide');
		}
		function CheckForgetEmail(){
			var d 		= new Date();
			var time 	= d.getTime();
			$('#forgetMessage').html('');
			$('#forgetSuccMessage').html('');
			$("#forgetPasswordForm").formValidation().on('success.form.fv', function(e) {
				e.stopImmediatePropagation();
				$('#forgetSuccMessage').html('loading..');
					$.ajax({
						type		:   'POST',
						url			:  	baseUrl+'check-email-exits?sRch='+time,
						dataType	: 	"json",
						data:$('#forgetPasswordForm').serialize(),
						success: function(data){
							$('#forgotpasswordModal').modal('hide');
							$('#forgetSuccMessage').html('');
							if(data.output == "success"){
								$('#forgetPasswordForm').formValidation('resetForm', true);
								$('#successForgetPopUp').modal('show');
								$('#message').html('Successfully sent.Please check your mail box.');
							}else{
								$('#successForgetPopUp').modal('show');
								$('#message').html('Email id not in records');
							}
						}
					});
				e.preventDefault();	
			});
		}
		//Reset Password 
		function resetPasswordFun(){
			$('#resetMessage').html('');
			$('#resetSuccMessage').html('');
			$("#resetPasswordForm").formValidation().on('success.form.fv', function(e) {
				e.stopImmediatePropagation();
					$.ajax({
						type		:   'POST',
						url			:  	baseUrl+'save-password',
						dataType	: 	"json",
						data        :  $('#resetPasswordForm').serialize(),
						success: function(data){
							if(data.output == "success"){
								$('#myModalReset').modal('hide');
								$('#f_message').html('Successfully Updated Please login.');
								$('#forgot_hidden_common').modal('show');
								window.location = baseUrl;
							}else{
								$('#myModalReset').modal('hide');
								$('#f_message').html('Your verfication link has expired.');
								$('#forgot_hidden_common').modal('show');
							}
						}
					});
				e.preventDefault();	
			});
		}
		
		
		var sguid	= $("#uidsg").val();
		var sgValue	= $("#emailsgverify").val();
		if(sguid != 0 && sgValue!=0)
		{		
			$.ajax({
			type:'POST',
			url:  baseUrl+'check-reg-auth',
			data:{sguid:sguid},
				success: function(data){									
					console.log(data);
					if(data.output == 'success')
					{
						$('#sgu_message').html('Successfully.');
						$('#sg_hidden_common').modal('show');
					}else if(data.output == 'exists'){
						$('#sgu_message').html('Your verfication link has expired.');
						$('#sg_hidden_common').modal('show');
					}else{
						$('#sgu_message').html('Server not found.');
						$('#sg_hidden_common').modal('show');
					}
				}
			});
		}
		
		
		
		
		var uid			= $("#uidfemail").val();
		var token		= $("#uidftoken").val();
		var resetValue	= $("#verifyfemail").val();
		if(uid != 0 && resetValue!=0)
		{		
			$.ajax({
			type:'POST',
			url:  baseUrl+'check-fuid',
			data:{uid:uid,token:token},
				success: function(data){									
					console.log(data);
					if(data.output == 'sucess')
					{
						$('#f_UserId').val(uid);
						$('#f_token').val(token);
						$('#myModalReset').modal('show');
					}else{
						$('#f_message').html('Your verfication link has expired.');
						$('#forgot_hidden_common').modal('show');
					}
				}
			});
		}
		</script>
	</body>
</html>
