<?php
	$header			=	$this->action('Application\Controller\IndexController', 'headerAction');
	$baseUrl 		= 	$header->headerarray['baseUrl'];
	$basePath 		= 	$header->headerarray['basePath'];
?>
<!DOCTYPE html>
<html lang="en">
	<head>
	    <meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<title>UmpireTaxSolutions</title>
		<link href="<?php echo $basePath;?>/css/bootstrap.min-home.css" rel="stylesheet">
		<link href="<?php echo $basePath;?>/css/custom-home.css" rel="stylesheet">
		<link href="<?php echo $basePath;?>/css/style-home.css" rel="stylesheet">
		<link href="<?php echo $basePath;?>/font-awesome/css/font-awesome.min.css" rel="stylesheet">  
	</head>
    <body>
		<nav class="navbar  navbar-default navbar-fixed-top" role="navigation">
			<div class="pad_res">
				<div class="top_bar">
					<ul class="nav navbar-nav ">
						<li class="res ">
							<p class="mar_t15">CONTACT US:<strong> <span class="site_col">Hello@umpiretaxsolutions.com</span></strong></p>
						</li>
						<li class="res site_col">
							<div class="mar_t5">
								<img src="<?php echo $basePath;?>/img/us-flag.png" class="">&nbsp;<strong>+1(828)-548-6793</strong><br>
								<img src="<?php echo $basePath;?>/img/us-flag.png" class="pull-left">&nbsp;<strong>+1(910)-835-1810</strong>
							</div>
						</li><li class="res site_col">
							<p class="pull-left mar_t5">
							<span><img src="<?php echo $basePath;?>/img/ind.png" class="pull-left">&nbsp;<strong>+91-720-754-3882</strong></span>
							</br>
							<span>Office Timings: Mon to Sun - 08:00AM CST to 6:30PM CST</span>
							</p>
						</li>
						<li class="res btn_ref">
								<a  class="login_btn"><i class="fa fa-lock"> </i> Login / Sign Up</a>
								<a class="ref_frnd"  data-toggle="modal" data-target="#squarespaceModal" ui-sref="main.referalProgram"><i class="fa fa-user"></i> Refer a Friend</a>	
						</li>
					</ul>
				</div>
			</div>
		</nav>
		<div class="mar_t50">
			<nav class="navbar navbar-inverse pos_nav " role="navigation">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand logo_res" href="index.html"><img class="img-responsive" src="<?php echo $basePath;?>/img/logo-home.png"></a>
					</div>
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="margin-top:30px;">
						<ul class="nav navbar-nav navbar-right menu_pad">
							<li>
								<a class="active"href="index.html">Home</a>
							</li> 
							<li>
								<a href="firm-profile.php">FIRM PROFILE</a>
							</li>
							<li>
								<a href="">OUR SERVICES</a>
							</li>
							<li>
								<a href="#">TAX CENTER</a>
							</li> 
							<li>
								<a href="#">CAREERS</a>
							</li> 
							<li>
								<a href="#">CONTACT US</a>
							</li>
							
								</ul>
							</li>
						</ul>
					</div>
				</div>
			</nav>
		</div>
  




	
