<footer class="top_footer">
	<div class="footer" id="footer">
		<div class="container">
			<div class="row top_foot">
				<div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
					<ul class="bord_rigt">
						<li> <a href="#"> Home </a> </li>
						<li> <a href="#"> Firm Profile </a> </li>
						<li> <a href="#"> Tax Center </a> </li>
					</ul>
				</div>
				<div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
					<ul class="bord_rigt">
						<li> <a href="#"> Carrers </a> </li>
						<li> <a href="#"> ContactUs </a> </li>
						
					</ul>
				</div>
				<div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
					<ul class="bord_rigt">
						<li> <a href="#"> Our Services </a> </li>
					</ul>
				</div>
				<div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
					<ul>
						<li> <a href="#"> &nbsp; </a> </li>
						
					</ul>
				</div>
				<div class="col-lg-3  col-md-3 col-sm-6 col-xs-12 ">
				   <img class="img-responsive"src="<?php echo $basePath;?>/img/add.png">
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="bor_bot">
	</div>
	</div>
	<div class="footer-bottom mar_t10">
		<div class="container">
			<p class="pull-left"> Copyright © Footer 2014. All right reserved. </p>
			<div class="pull-right">
				<ul class="nav nav-pills payments">
					<li>Payment T&C Refund Policy</li>
					<li>Privacy Policy</li>
					<li>Terms & Conditions</li>
				   
				</ul> 
			</div>
		</div>
	</div>
</footer>
		
<div class="modal fade" id="squarespaceModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
			<h3 class="modal-title" id="lineModalLabel">Login </h3>
		</div>
		<div class="modal-body">
			<form>
              <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter a email">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Enter a password">
              </div>
            </form>
		</div>
		<div class="modal-footer">
			<div class="btn-group btn-group-justified" role="group" aria-label="group button">
				<div class="btn-group" role="group">
					<button type="button" class="btn btn-default" data-dismiss="modal"  role="button">Close</button>
				</div>
				<div class="btn-group btn-delete hidden" role="group">
					<button type="button" id="delImage" class="btn btn-default btn-hover-red" data-dismiss="modal"  role="button">Delete</button>
				</div>
				<div class="btn-group" role="group">
					<button type="button" id="saveImage" class="btn btn-default btn-hover-green" data-action="save" role="button">Submit</button>
				</div>
			</div>
		</div>
	</div>
  </div>
</div>
<div class="modal fade" id="myModal1" role="dialog" >
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content overflow_hidden" >
        <div class="modal-header pop_title">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Forget the password</h4>
        </div>
        <div class="modal-body">
         <form id="forgetPasswordForm" class="form-horizontal" style="margin-top:-30px;"  data-fv-message="This value is not valid" data-fv-icon-valid="glyphicon" data-fv-icon-invalid="glyphicon" data-fv-icon-validating="glyphicon glyphicon-refresh" onSubmit="return CheckForgetEmail();" enctype="multipart/form-data">
            <div class="pop">
			  <div class="form-group is-empty">
                <label class="col-md-3 control-label tex_lef" for="ForgetEmail">Email</label>

                <div class="col-md-9">
                  <input type="text" placeholder="Email" id="ForgetEmail" name="ForgetEmail" class="form-control input-lg user_login" required data-fv-regexp="true" data-fv-regexp-regexp="^[_a-z0-9]+(\.[_a-z0-9]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$"  data-fv-regexp-message="The email is not a valid">
				  
                </div>
              </div>
            </div>
			  
        
        </div>
        <div class="modal-footer mar_r5">
			<div class="col-md-8 text-left">
				<span id="forgeterrorEmail" style="color:red"></span>
				<span id="forgetsucessEmail" style="color:red"></span>
			</div>
			<div class="col-md-2 pull-right">
			<button type="submit" class="btn   btn-raised btn-info" id="checkForgetEmail">Submit</button>
			</div>		
        </div>
      </div>
        </form>
    </div>
  </div>		
		
		
		
		<script>
			var basePath     	= '<?php echo $basePath; ?>';
			var baseUrl 		= '<?php echo $baseUrl; ?>';
		</script>
		<script src="<?php echo $basePath;?>/js/uts-jquery.js"></script>
		<script src="<?php echo $basePath;?>/js/bootstrap.min.js"></script>
		<script>
			$('.carousel').carousel({
				interval: 5000 
			});
		</script>
	</body>
</html>
