<footer class="top_footer">
	<div class="footer" id="footer">
		<div class="container">
			<div class="row top_foot">
				<div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
					<ul class="bord_rigt">
						<li> <a href="#"> Home </a> </li>
						<li> <a href="#"> Firm Profile </a> </li>
						<li> <a href="#"> Tax Center </a> </li>
					</ul>
				</div>
				<div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
					<ul class="bord_rigt">
						<li> <a href="#"> Carrers </a> </li>
						<li> <a href="#"> ContactUs </a> </li>
						
					</ul>
				</div>
				<div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
					<ul class="bord_rigt">
						<li> <a href="#"> Our Services </a> </li>
					</ul>
				</div>
				<div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
					<ul>
						<li> <a href="#"> &nbsp; </a> </li>
						
					</ul>
				</div>
				<div class="col-lg-3  col-md-3 col-sm-6 col-xs-12 ">
				   <img class="img-responsive"src="<?php echo $basePath;?>/img/add.png">
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="bor_bot">
	</div>
	</div>
	<div class="footer-bottom mar_t10">
		<div class="container">
			<p class="pull-left"> Copyright © Footer 2014. All right reserved. </p>
			<div class="pull-right">
				<ul class="nav nav-pills payments">
					<li>Payment T&C Refund Policy</li>
					<li>Privacy Policy</li>
					<li>Terms & Conditions</li>
				   
				</ul> 
			</div>
		</div>
	</div>
</footer>
		
<div class="modal fade" id="squarespaceModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
			<h3 class="modal-title" id="lineModalLabel">My Modal</h3>
		</div>
		<div class="modal-body">
			
            <!-- content goes here -->
			<form>
              <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
              </div>
              <div class="form-group">
                <label for="exampleInputFile">File input</label>
                <input type="file" id="exampleInputFile">
                <p class="help-block">Example block-level help text here.</p>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Check me out
                </label>
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
            </form>

		</div>
		<div class="modal-footer">
			<div class="btn-group btn-group-justified" role="group" aria-label="group button">
				<div class="btn-group" role="group">
					<button type="button" class="btn btn-default" data-dismiss="modal"  role="button">Close</button>
				</div>
				<div class="btn-group btn-delete hidden" role="group">
					<button type="button" id="delImage" class="btn btn-default btn-hover-red" data-dismiss="modal"  role="button">Delete</button>
				</div>
				<div class="btn-group" role="group">
					<button type="button" id="saveImage" class="btn btn-default btn-hover-green" data-action="save" role="button">Save</button>
				</div>
			</div>
		</div>
	</div>
  </div>
</div>
		
		
		
		
		<script>
			var basePath     	= '<?php echo $basePath; ?>';
			var baseUrl 		= '<?php echo $baseUrl; ?>';
		</script>
		<script src="<?php echo $basePath;?>/js/uts-jquery.js"></script>
		<script src="<?php echo $basePath;?>/js/bootstrap.min.js"></script>
		<script>
			$('.carousel').carousel({
				interval: 5000 
			});
		</script>
	</body>
</html>
