<?php
	//echo "<pre>"; print_r($_SERVER); exit;
	$header			=	$this->action('Application\Controller\IndexController', 'headerAction');
	$baseUrl 		= 	$header->headerarray['baseUrl'];
	$basePath 		= 	$header->headerarray['basePath'];
	$home = "";
	$testimonial = "";
	$textCenter  = "";
	$profile     = "";
	$services    = "";
	$careers      = "";
	$contactUs     = "";
	if($_SERVER['REQUEST_URI'] == '/utsproject/trunk/uts-fronted/'){
		$home    = "active";
	}
	if($_SERVER['REQUEST_URI'] == '/uts/'){
		$home    = "active";
	}
	if(strpos($_SERVER['REQUEST_URI'], 'testimonial') !== false){
		$testimonial    = "active";
	}
	if(strpos($_SERVER['REQUEST_URI'], 'tax-center') !== false){
		$textCenter    = "active";
	}
	if(strpos($_SERVER['REQUEST_URI'], 'firm-profile') !== false){
		$profile    = "active";
	}
	if(strpos($_SERVER['REQUEST_URI'], 'services') !== false){
		$services    = "active";
	}
	if(strpos($_SERVER['REQUEST_URI'], 'carrers') !== false){
		$careers    = "active";
	}
	if(strpos($_SERVER['REQUEST_URI'], 'contact-us') !== false){
		$contactUs    = "active";
	}
	
?>
<!DOCTYPE html>
<html lang="en">
	<head>
	    <meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<title>UmpireTaxSolutions</title>
		<link href="<?php echo $basePath;?>/css/bootstrap.min-home.css" rel="stylesheet">
		<link href="<?php echo $basePath;?>/css/custom-home.css" rel="stylesheet">
		<link href="<?php echo $basePath;?>/css/style-home.css" rel="stylesheet">
		<link href="<?php echo $basePath;?>/css/animate-home.css" rel="stylesheet">
		<link href="<?php echo $basePath;?>/font-awesome/css/font-awesome.min.css" rel="stylesheet">  
	</head>
    <body>
		<nav class="navbar  navbar-default navbar-fixed-top" role="navigation">
			<div class="">
				<div class="">
				<div class="">
						<div class="res col-md-3">
							<p class="mar_t15">
							<div class="col-md-3">
								<img class="img-responsive imgRes sm-hide" style="border-radius:50%;width:100%"src="<?php echo $basePath;?>/img/cust.png">
							</div>
							<div class="col-md-9">
								<strong> <span class="site_col">Hello@umpiretaxsolutions.com</span></strong><br>
								<strong> <span class="site_col">Clientsupport@umpiretaxsolutions.com</span></strong>
							</div>
							</p>
						</div>
						<div class="res site_col col-md-2 pad_lf70">
							<div class="mar_t17" style="">
								<img src="<?php echo $basePath;?>/img/us-flag.png" class="">&nbsp;<strong>+1(631)-407-1040</strong><br>
								<!--<img src="<?php echo $basePath;?>/img/us-flag.png" class="pull-left">&nbsp;<strong>+1(910)-835-1810</strong>-->
								<img src="<?php echo $basePath;?>/img/ind.png" class="pull-left">&nbsp;<strong>+9140-6999-1040</strong>
							</div>
						</div>
						<div class="res site_col col-md-3 pad_lf90">
							<p class="pull-left mar_t15">
							<!--<span><img src="<?php echo $basePath;?>/img/ind.png" class="pull-left">&nbsp;<strong>+9140-6999-1040</strong></span>
							</br>-->
							<span style="font-size:16px;font-weight:600">Office Timings: Mon to Sun  <br> 06:00AM CST to 6:30PM CST</span>
							</p>
						</div>
						<style>
							.btn_padd a{
							margin:0 2px;
							}
						</style>
						<div class="res btn_ref col-md-4 btn_padd mar_t15">
								<?php if(isset($_SESSION["user"]["user_id"]) && $_SESSION["user"]["user_id"]!=""){ ?>
									<a  class="login_btn" href="<?php echo $baseUrl;?>dashboard"><i class="fa fa-tachometer "> </i> Go To Dashboard </a>
								<?php }else { ?>
									<a  style="cursor: pointer;font-size:16px;"class="login_btn" data-toggle="modal" data-target="#regModal"><i class="fa fa-user"> </i> Sign Up </a>
									<a  style="cursor: pointer;font-size:16px;"class="login_btn" data-toggle="modal" data-target="#loginModal"><i class="fa fa-lock"> </i> Login </a>
								<?php } ?>
								<span class="blink_me"><a style="font-size:16px;" class=" ref_frnd" href="<?php echo $baseUrl?>referral"><i class="fa fa-user"></i> Refer a Friend</a>	</span>
						</div>
				</div>
			</div>
			</div>
		</nav>
		<div class="mar_t50">
			<nav class="navbar navbar-inverse pos_nav " role="navigation">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand logo_res" href="<?php echo $baseUrl;?>"><img class="img-responsive" src="<?php echo $basePath; ?>/img/logo-home.png"></a>
					</div>
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="margin-top:30px;">
						<ul class="nav navbar-nav navbar-right menu_pad drop_st" style="margin-right:-100px;">
							<li  class="<?php echo $home;?>">
								<a class="" href="<?php echo $baseUrl;?>">Home</a>
							</li> 
							<li class = "<?php echo $profile;?>" >
								<a href="<?php echo $baseUrl;?>firm-profile">PROFILE</a>
							</li>
							<li class="dropdown <?php echo $services; ?>">
								<a href="<?php echo $baseUrl;?>services">SERVICES</a>
								 <div class="dropdown-content mob_hid">
									<a href="<?php echo $baseUrl;?>services">US Tax Services</a>
									<a href="<?php echo $baseUrl;?>services#inServices">Individual Services </a>
									<a href="<?php echo $baseUrl;?>services#bServices">Business Services</a>
									<a href="<?php echo $baseUrl;?>services#indianSer">Indian Tax Services</a>
									<a href="<?php echo $baseUrl;?>services">Advisory on Taxation</a>
									<a href="<?php echo $baseUrl;?>services#auditTaxation">Audit and Certification </a>
									<a href="<?php echo $baseUrl;?>services#others">Service Tax VAT & others</a>
								  </div>
							</li>
							<li class = "<?php echo $textCenter;?>" >
								<a href="<?php echo $baseUrl;?>tax-center">TAX CENTER</a>
							</li>
							<li class = "<?php echo $testimonial;?>" >
								<a href="<?php echo $baseUrl;?>testimonial">TESTIMONIALS</a>
							</li> 
							<li class = "<?php echo $careers;?>" >
								<a href="<?php echo $baseUrl;?>carrers">CAREERS</a>
							</li> 
							<li class = "<?php echo $contactUs;?>" >
								<a href="<?php echo $baseUrl;?>contact-us">CONTACT US</a>
							</li>
							
								</ul>
							</li>
						</ul>
					</div>
				</div>
			</nav>
		</div>
  




	
