<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<?php
	
	$header			=	$this->action('Application\Controller\IndexController', 'headerAction');
	$baseUrl 		= 	$header->headerarray['baseUrl'];
	$basePath 		= 	$header->headerarray['basePath'];	
?>
<?php
	if($_SERVER['REQUEST_URI'] == '/utsproject/trunk/uts-fronted/'){
		include 'home-header.phtml';
	}else if(strpos($_SERVER['REQUEST_URI'], 'checking-login') == true){
		include 'home-header.phtml';
	}else if(strpos($_SERVER['REQUEST_URI'], 'firm-profile') == true){
		include 'home-header.phtml';
	}else if(strpos($_SERVER['REQUEST_URI'], 'services') == true){
		include 'home-header.phtml';
	}else if(strpos($_SERVER['REQUEST_URI'], 'tax-center') == true){
		include 'home-header.phtml';
	}else if(strpos($_SERVER['REQUEST_URI'], 'carrers') == true){
		include 'home-header.phtml';
	}else if(strpos($_SERVER['REQUEST_URI'], 'contact-us') == true){
		include 'home-header.phtml';
	}else if(strpos($_SERVER['REQUEST_URI'], 'reset-mode') == true){
		include 'home-header.phtml';
	}else if(strpos($_SERVER['REQUEST_URI'], 'referral') == true){
		include 'home-header.phtml';
	}else{
		include 'header.phtml';
	}	
	echo $this->content;	
	if($_SERVER['REQUEST_URI'] == '/utsproject/trunk/uts-fronted/'){
		include 'home-footer.phtml';
	}else if(strpos($_SERVER['REQUEST_URI'], 'checking-login') == true){
		include 'home-footer.phtml';
	}else if(strpos($_SERVER['REQUEST_URI'], 'firm-profile') == true){
		include 'home-footer.phtml';
	}else if(strpos($_SERVER['REQUEST_URI'], 'services') == true){
		include 'home-footer.phtml';
	}else if(strpos($_SERVER['REQUEST_URI'], 'tax-center') == true){
		include 'home-footer.phtml';
	}else if(strpos($_SERVER['REQUEST_URI'], 'carrers') == true){
		include 'home-footer.phtml';
	}else if(strpos($_SERVER['REQUEST_URI'], 'contact-us') == true){
		include 'home-footer.phtml';
	}else if(strpos($_SERVER['REQUEST_URI'], 'reset-mode') == true){
		include 'home-footer.phtml';
	}else if(strpos($_SERVER['REQUEST_URI'], 'referral') == true){
		include 'home-footer.phtml';
	}else{
		include 'footer.phtml';
	}	
?>
<!-- side refer friend -->
<style>
.cust_pop{
   position: fixed;
   right: -99px;
   z-index: 9999999;
   top: 152px;
   transition: all 1s ease-in-out;
   cursor: pointer;
}

.cust_pop:hover{
   right:0px;
   transition: all 1s ease-in-out;
}
.cust{
   border-radius: 100%;
   float: left;

   padding: 10px;
}

.cust_pop a{
   float: left;
}

.cust_pop >div{
   background-color: #fff;
   margin-top: 17px;
   padding: 5px;
}
.cust_pop >div a{
   float: left;
   clear: left;
   text-decoration: none;
   padding: 5px;
   margin-top: 5px;
   padding: 0;
}
</style>
<div class="cust_pop sm-hide"  ng-if="userbody==''">
   <img src="<?php echo $basePath;?>/img/cust.png" class="cust">
   <div class="pull-left">
   <a ui-sref="main.referalProgram">
       Refer a Friend
   </a>
       <a ui-sref="main.contactUs">
       Contact us
           </a>
   </div>
</div>
<!--  end side refer friend -->
<!-- Refer a Friend -->
	<div class="modal fade" id="referFriendPopUp" role="dialog" data-backdrop="static" data-keyboard="false">
		<div class="modal-dialog">
			<div class="modal-content" >
				<div class="modal-header" style="border-bottom:1px solid #ddd;background:#189def;color:#fff;border-radius:2px 2px 0 0">
					<button type="button" class="close" onclick="closeForm()">&times;</button>
					<center><h4 class="modal-title">REFER A FRIEND</h4><p> Please provide the following detailes of the Friend Whom you wish to Refer.<p></center>
				</div>
				<div class="modal-body">
					<form class="form-horizontal" data-fv-message="This value is not valid" data-fv-icon-valid="glyphicon" data-fv-icon-invalid="glyphicon"  data-fv-icon-validating="glyphicon glyphicon-refresh"	method="POST" name="referFriendForm" id="referFriendForm"  onSubmit="referFriend();" enctype="multipart/form-data">
						<div class="form-group">
							<!--<label class="col-md-3 control-label" for="inputFullName">Your Name</label>-->
							<div class="col-md-12">
							<input type="text" placeholder="Your Name" id="yourName" name="yourName" class="form-control"  required data-fv-notempty="true" 
							data-fv-notempty-message="The full name is required" />
							</div>
						</div>
						<div class="form-group">
							<!--<label class="col-md-3 control-label tex_lef" for="inputEmail">Your Email Id</label>-->
							<div class="col-md-12">
								<input type="text" placeholder="Your Email Id" id="yourEmail" name="yourEmail" class="form-control user_login" required data-fv-notempty-message="The email is required" 
								data-fv-regexp="true"  data-fv-regexp-regexp="^[_a-z0-9]+(\.[_a-z0-9]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$"  data-fv-regexp-message="The email is not a valid">
								<span id="emailChecking" style="color:red;"></span>
							</div>
						</div>
						<div class="form-group">
							<!--<label class="col-md-3 control-label tex_lef" for="phone">Your Mobile Number</label>-->
							<div class="col-md-12">
								<input type="text" placeholder="Your Mobile Number" id="yourPhone" name="yourPhone" class="form-control user_login" required data-fv-notempty-message="Please enter a phone" data-fv-integer="true" data-fv-integer-message="The value is not an integer" maxlength="10"
							data-fv-stringlength data-fv-stringlength-min="10" data-fv-stringlength-message="Phone number must be 10 digits only" maxlength="10">
								<span id="phoneChecking" style="color:red;"></span>
							</div>
						</div>
						<div class="form-group">
							<!--<label class="col-md-3 control-label" for="inputFullName">Name Of Your Friend </label>-->
							<div class="col-md-12">
							<input type="text" placeholder="Name of Your Friend" id="friendName" name="friendName" class="form-control"  required data-fv-notempty="true" 
							data-fv-notempty-message="The full name is required" />
							</div>
						</div>
						<div class="form-group">
							<!--<label class="col-md-3 control-label tex_lef" for="inputEmail">Friend's Email Id</label>-->
							<div class="col-md-12">
								<input type="text" placeholder="Friend's Email Id" id="friendEmail" name="friendEmail" class="form-control user_login" required data-fv-notempty-message="The email is required" 
								data-fv-regexp="true"  data-fv-regexp-regexp="^[_a-z0-9]+(\.[_a-z0-9]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$"  data-fv-regexp-message="The email is not a valid">
								<span id="emailChecking" style="color:red;"></span>
							</div>
						</div>
						<div class="form-group">
							<!--<label class="col-md-3 control-label tex_lef" for="phone">Friend's Mobile Number</label>-->
							<div class="col-md-12">
								<input type="text" placeholder="Friend's Mobile Number" id="friendPhone" name="friendPhone" class="form-control user_login" required data-fv-notempty-message="Please enter a phone" data-fv-integer="true" data-fv-integer-message="The value is not an integer" maxlength="10"
							data-fv-stringlength data-fv-stringlength-min="10" data-fv-stringlength-message="Phone number must be 10 digits only" maxlength="10">
								<span id="phoneChecking" style="color:red;"></span>
							</div>
						</div>
						<div class="form-group">
							<!--<label class="col-md-3 control-label" for="inputFullName">Description</label>-->
							<div class="col-md-12">
							<input type="text" placeholder="Description" id="description" name="description" class="form-control"  required data-fv-notempty="true" 
							data-fv-notempty-message="The description is required" />
							</div>
						</div>
						<div class="modal-footer mar_r5">
							<div class="col-md-8 text-left">
								<span id="refMesage" style="color:red"></span>
								<span id="refSuccMesage" style="color:green"></span>
							</div><br/>
							<div class="col-md-2 pull-right">
								<button type="submit" class="btn   btn-raised btn-info" >Submit</button>
							</div>		
						</div>
					</form>	
				</div>				
			</div>
		</div>
	</div>
<!-- End -->
<script>
$(document).ready(function() {
	$('#contactForm').formValidation().on('success.form.fv', function(e, data) {	
		e.preventDefault();
	});
});
	
function referFriend(){
		$('#refMesage').html('');
		$('#refSuccMesage').html('');
			$("#referFriendForm").formValidation().on('success.form.fv', function(e) {
				e.stopImmediatePropagation();
					$.ajax({
						type		:   'POST',
						url			:  	baseUrl+'refer-friend',
						dataType	: 	"json",
						data:$('#referFriendForm').serialize(),
						success: function(data){
							if(data.output == "success"){
								$('#refSuccMesage').html('Successfully Saved');
							}else{
								$('#refMesage').html('Friend email already exits');
							}
						}
					});
				e.preventDefault();	
			});
		}
		function referFriendPopFun(){
			$('#refMesage').html('');
			$('#refSuccMesage').html('');
			$('#referFriendForm').formValidation('resetForm', true);
			$.ajax({
				type		:   'GET',
				url			:  	baseUrl+'get-user-info',
				dataType	: 	"json",
				success: function(data){
					if(data.output == "success"){
						$('#yourName').val(data.userInfo['user_name']);
						$('#yourEmail').val(data.userInfo['email']);
						$('#yourPhone').val(data.userInfo['phone']);
					}
					$('#referFriendPopUp').modal('show');
				}
			});
		}
		function closeForm(){
			$('#refMesage').html('');
			$('#refSuccMesage').html('');
			$('#referFriendForm').formValidation('resetForm', true);
			$('#referFriendPopUp').modal('hide');
		}
		
		function contactFormFun(){
		 $('#successContact').html('');
			$("#contactForm").formValidation().on('success.form.fv', function(e) {
				e.stopImmediatePropagation();
					$.ajax({
						type		:   'POST',
						url			:  	baseUrl+'contact-form',
						dataType	: 	"json",
						data:$('#contactForm').serialize(),
						success: function(data){
							if(data.output == "success"){
								$('#contactForm').formValidation('resetForm', true);
								$('#successContact').html('Successfull');
								//window.location = baseUrl;
							}
						}
					});
				e.preventDefault();	
			});
		}
		</script>