<?php
	$header			=	$this->action('Application\Controller\IndexController', 'headerAction');
	$baseUrl 		= 	$header->headerarray['baseUrl'];
	$basePath 		= 	$header->headerarray['basePath'];
?>
<div class="collapse navbar-collapse navbar-ex1-collapse">
	<ul class="nav navbar-nav side-nav">
		<li class="active">
			<a href="<?php echo $baseUrl; ?>dashboard"> <i class="fa fa-product-home"></i> Home <i class="fa fa-chevron-circle-down"></i></a>
		</li>
		<li>
			<a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-product-hunt"></i> Profile Information <i class="fa fa-chevron-circle-down"></i></a>
			<ul id="demo" class="collapse">
				<li>
					<a href="<?php echo $baseUrl;?>tax-info"><i class="fa fa-chevron-circle-right"></i> Tax Payer Info </a>
				</li>
				<li>
					<a href="<?php echo $baseUrl;?>spouse-info"><i class="fa fa-chevron-circle-right"></i> Spouse </a>
				</li>
				<li>
					<a href="<?php echo $baseUrl;?>emp-info"><i class="fa fa-chevron-circle-right"></i> Employer Info </a>
				</li>
				<li>
					<a href="<?php echo $baseUrl;?>dependents-info"><i class="fa fa-chevron-circle-right"></i> Dependents (If any) </a>
				</li>
			</ul>
		</li>
		<li>
			<a href="<?php echo $baseUrl;?>schedule-tax-info"><i class="fa fa-sticky-note"></i> Schedule For Tax Notes</a>
		</li>
		<li>
			<a href="<?php echo $baseUrl;?>upload-documents-info"><i class="fa fa-upload"></i> Upload Tax Documents</a>
		</li>
		<li>
			<a href="<?php echo $baseUrl;?>summary-info"><i class="fa fa-file-archive-o"></i> View Tax Summary</a>
		</li>
		<li>
			<a href=""><i class="fa fa-cc-paypal"></i> Make Payment</a>
		</li>
		<li>
			<a href="javascript:void(0);" style="cursor:default;"><i class="fa fa-download"></i>Download Tax Return Copy</a>
		</li>
		<li>
			<a href="javascript:void(0);"><i class="fa fa-hand-o-right"></i> Disclaimer Agreement</a>
		</li>
		<li>
			<a href="<?php echo $baseUrl; ?>"><i style="color:black;" class="glyphicon glyphicon-lock"></i> Go TO Home</a>
		</li>
	</ul>
</div>