<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Eva\View\Helper\Action'                            => __DIR__ . '/src/Application/Helper/Action.php',
	'Application\Controller\Plugin\Myplugin'            => __DIR__ . '/src/Application/Plugin/MyPlugin.php',
 );