<style>
	.und_lin tr{
		border-bottom:1px solid #ddd;
	}			
</style>
<div class="content-wrapper">
	<div class="container">
		<div class="mar_t30"></div>
		<ul class="nav nav-pills nav_pill_sty">
			<li><a data-toggle="pill" href="#basicInfoTab" onclick="tabsUserInfo(<?php echo $this->userId; ?>,<?php echo $this->processStatus; ?>,1);">Basic Info</a></li>
			<li><a data-toggle="pill" href="#otherInfoTab" onclick="tabsUserInfo(<?php echo $this->userId; ?>,<?php echo $this->processStatus; ?>,2);">Other Info</a></li>
			<li><a data-toggle="pill" href="#scheduleTab" onclick="tabsUserInfo(<?php echo $this->userId; ?>,<?php echo $this->processStatus; ?>,3);">Schedule Time</a></li>
			<li><a data-toggle="pill" href="#downloadTab" onclick="tabsUserInfo(<?php echo $this->userId; ?>,<?php echo $this->processStatus; ?>,4);">Download documents</a></li>
			<li><a data-toggle="pill" href="#uploadTab" onclick="tabsUserInfo(<?php echo $this->userId; ?>,<?php echo $this->processStatus; ?>,5);">Upload documents</a></li>
			<li><a data-toggle="pill" href="#fileTab" onclick="tabsUserInfo(<?php echo $this->userId; ?>,<?php echo $this->processStatus; ?>,6);">File status</a></li>
			<li><a data-toggle="pill" href="#paymentTab" onclick="tabsUserInfo(<?php echo $this->userId; ?>,<?php echo $this->processStatus; ?>,7);">Payment Info</a></li>
		</ul>
		<div class="tab-content mar_t30">
			<div id="basicInfoTab" class="tab-pane fade in active"></div>
			<div id="otherInfoTab" class="tab-pane fade in active"></div>
			<div id="scheduleTab" class="tab-pane fade in active"></div>
			<div id="downloadTab" class="tab-pane fade in active"></div>
			<div id="uploadTab" class="tab-pane fade in active"></div>
			<div id="fileTab" class="tab-pane fade in active"></div>
			<div id="paymentTab" class="tab-pane fade in active"></div>
		</div>
	</div>
</div>
<script>
tabsUserInfo(<?php echo $this->userId; ?>,<?php echo $this->processStatus; ?>,1);
</script>
