<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1>Change Password</h1>
		<ol class="breadcrumb">
			<?php if(isset($_SESSION['user']['userId']) && $_SESSION['user']['ut_type_name']!="admin"){?>
			<li><a href="<?php echo $baseUrl;?>/steps-process?id=1"><i class="fa fa-dashboard"></i> Home</a></li>
			<?php }else{ ?>
			<li><a href="<?php echo $baseUrl;?>/dashboard"><i class="fa fa-dashboard"></i> Home</a></li>
			<li><a href="<?php echo $baseUrl;?>/dashboard">Users</a></li>
			<?php } ?>
			<li class="active">Change Password</li>
		</ol>
	</section>
	<section class="content">
		<div class="row">
			<div class="col-md-12">
				<div class="box box-info">
					<div class="box-header with-border">
						<h3 class="box-title">Change Password</h3>
					</div><!-- /.box-header -->
					<?php //echo "<pre>";print_r($_SESSION['user']); exit;?>
					<!-- form start -->
					<form id="uChangePwd" name="uChangePwd" method="POST" class="form-horizontal" 
						data-fv-message="This value is not valid"
						data-fv-icon-valid="glyphicon glyphicon-ok"
						data-fv-icon-invalid="glyphicon glyphicon-remove"
						data-fv-icon-validating="glyphicon glyphicon-refresh" onSubmit="changePassword();">
						<div class="box-body">													
							<div class="form-group">
								<label for="inputPassword3" class="col-sm-2 control-label">Old Password</label>
								<div class="col-sm-4">
									<input type="password" class="form-control" id="o_u_password" name="o_u_password" placeholder="Password" value="<?php if(isset($this->data['o_u_password']) && $this->data['o_u_password']!=""){ echo $this->data['o_u_password']; }?>"
									required data-fv-notempty-message="Please enter a old password" data-fv-regexp="true" data-fv-regexp-regexp="^.*(?=.{5,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%&!^*()~<>,.{}'?+=-?/|]).*$" data-fv-regexp-message="Must be at least 5 characters long, with at least 1 number, 1 lowercase letter, 1 uppercase letter,1 special character">
								</div>
							</div>
							<div class="form-group">
								<label for="inputPassword3" class="col-sm-2 control-label">New Password</label>
								<div class="col-sm-4">
									<input type="password" class="form-control" id="n_u_password" name="n_u_password" placeholder="Password" value="<?php if(isset($this->data['n_u_password']) && $this->data['n_u_password']!=""){ echo $this->data['n_u_password']; }?>"
									required data-fv-notempty-message="Please enter a new password" data-fv-regexp="true" data-fv-regexp-regexp="^.*(?=.{5,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%&!^*()~<>,.{}'?+=-?/|]).*$" data-fv-regexp-message="Must be at least 5 characters long, with at least 1 number, 1 lowercase letter, 1 uppercase letter,1 special character">
								</div>
							</div>
							<div class="form-group">
								<label for="inputPassword3" class="col-sm-2 control-label">Confirm Password</label>
								<div class="col-sm-4">
									<input type="password" class="form-control" id="u_password" name="u_password" placeholder="Password" value="<?php if(isset($this->data['u_password']) && $this->data['u_password']!=""){ echo $this->data['u_password']; }?>"
									required data-fv-notempty-message="Please enter a confirm password" data-fv-regexp="true" data-fv-regexp-regexp="^.*(?=.{5,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%&!^*()~<>,.{}'?+=-?/|]).*$" data-fv-regexp-message="Must be at least 5 characters long, with at least 1 number, 1 lowercase letter, 1 uppercase letter,1 special character" data-fv-identical="true" data-fv-identical-field="n_u_password" data-fv-identical-message="The password and its confirm are not the same">
								</div>
							</div>
							<input type="hidden" id="u_id" name="u_id" value="<?php if(isset($_SESSION['user']['userId']) && $_SESSION['user']['userId']!=""){ echo $_SESSION['user']['userId']; }?>">
						</div><!-- /.box-body -->
						<div class="box-footer">
							<?php if(isset($_SESSION['user']['userId']) && $_SESSION['user']['ut_type_name']!="admin"){?><a href="<?php echo $this->baseUrl;?>/steps-process?id=1" class="btn btn-default">Cancel</a>
							<?php }else{ ?>
							<a href="<?php echo $this->baseUrl;?>/members" class="btn btn-default">Cancel</a>
							<?php } ?>
							<button type="submit"  id="changePwdTbtn"  name="changePwdTbtn" class="btn btn-info pull-right">Change Password</button>
							<center><span style="color:green"><?php if(isset($this->sucMsg) && $this->sucMsg!=""){ echo $this->sucMsg; }?></span></center>
							<center><span style="color:red"><?php if(isset($this->errMsg) && $this->errMsg!=""){ echo $this->errMsg; }?></span></center>
						</div><!-- /.box-footer -->						
					</form>
				</div>
			</div>
		</div>
	</section>
</div>
<script type="text/javascript">
	$(document).ready(function() {
		$('#uChangePwd').formValidation();
	});
</script>