  <?php
		$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
		$baseUrl = $header->headerarray['baseUrl'];
		$basePath = $header->headerarray['basePath'];
	?>
  <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
			<h1> Referels </h1>
          <ol class="breadcrumb">
            <li><a href="<?php echo $baseUrl?>/members"><i class="fa fa-dashboard"></i> Home</a></li>
		    / Referels 
          </ol>
        </section>
        <!-- Main content -->
        <section class="content">
        <div class="box">
                <div class="box-body tEList">
                 
                </div><!-- /.box-body -->
              </div><!-- /.box -->
		</section>
    </div><!-- /.content-wrapper -->
<script>
  $(function () {
	$(".tEList").html("Please wait loading.....");
	$.ajax({
		type:	'GET',
		dataType:'json',
		url: '<?php echo $this->baseUrl; ?>/get-referels-info',
		success: function(data){			
		$('.tEList').html('<table id="serchList" class="table table-bordered table-striped"><thead><tr><th>Referels Name</th><th>Referels Email</th><th>Referenced By Name</th><th>Referenced By Email</th></tr></thead><tbody></tbody></table>');				
		var oTable = $('#serchList').dataTable( {
				aoColumnDefs: [{bSortable: false,
								aTargets: [ 0 ]
								}],
				"bStateSave": true,
				"bAutoWidth": true,
				"sRowSelect": "multi",
				"sPaginationType": "full_numbers",
				"bProcessing": true,
				"aaData": data.aaData,
				"aoColumns": [				
					{ "mData": "rf_name" },
					{ "mData": "rf_email"},	
					{ "mData": "re_on_name"},	
					{ "mData": "re_on_email" },						
				] 
			});	
		}
	});
  });
</script>