<?php
		$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
		$baseUrl = $header->headerarray['baseUrl'];
		$basePath = $header->headerarray['basePath'];
	?>
  <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
           Want Us To Call 
          </h1>
          <ol class="breadcrumb">
            <li><a href="<?php echo $baseUrl?>/members"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Want Us To Call</li>
          </ol>
        </section>
        <!-- Main content -->
        <section class="content">
        <div class="box">
                <div class="box-body tEList table-responsive">
                 
                </div><!-- /.box-body -->
              </div><!-- /.box -->
		</section>
    </div><!-- /.content-wrapper -->
<script>
  $(function () {
	$(".tEList").html("Please wait loading.....");
	$.ajax({
		type:	'GET',
		dataType:'json',
		url: '<?php echo $this->baseUrl; ?>/get-want-us-info?sRch=<?php echo time(); ?>',
		success: function(data){			
		$('.tEList').html('<table  width="100%" id="serchList" class="table table-bordered table-striped"><thead><tr><th width="15%">Client Name</th><th width="15%">Phone Number</th><th width="20%">E-Mail</th><th width="50%">Message</th></tr></thead><tbody></tbody></table>');				
		var oTable = $('#serchList').dataTable( {
				aoColumnDefs: [{bSortable: false,
								aTargets: [ 0 ]
								}],
				"bStateSave": true,
				"bSort": false,
				"order": [],
				"bAutoWidth": true,
				"sRowSelect": "multi",
				"sPaginationType": "full_numbers",
				"bProcessing": true,
				"aaData": data.aaData,
				"aoColumns": [
					{ "mData": "c_name" },					
					{ "mData": "c_phone" },
					{ "mData": "c_email"},	
					{ "mData": "c_message"},						
				] 
			});	
		}
	});
  });
</script>