<div class="content-wrapper">
        <section class="content-header">
          <h1>
          Add New Shop
          </h1>
          <ol class="breadcrumb">
            <li><a href="<?php echo $baseUrl?>/dashboard"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="<?php echo $baseUrl?>/shops-list">Mechanics</a></li>
            <li class="active">Add New Shop</li>
          </ol>
        </section>
		 <section class="content">
		<div class="row">
		 
		 <div class="col-md-12">

			<div class="box box-info">

                <div class="box-header with-border">

                  <h3 class="box-title">Add New Shop</h3>

                </div><!-- /.box-header -->

                <!-- form start -->

                <form class="form-horizontal" id="shopForm" method="post" class="form-horizontal" data-fv-message="This value is not valid" class="error_vl"
					  data-fv-icon-valid="glyphicon glyphicon-ok"
                      data-fv-icon-invalid="glyphicon glyphicon-remove" onSubmit="addShop();">

                  <div class="box-body">

                    <div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">First Name</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control" name="me_fname" id="me_fname" value="" placeholder="First Name" required data-fv-notempty-message="The first name is required and cannot be empty" />
                      </div>
                    </div>
					<div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">Last Name</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control" name="me_lname" id="me_lname" value="" placeholder="Last Name" required data-fv-notempty-message="The last name is required and cannot be empty" />
                      </div>
                    </div>
					<div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">Shop Name</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control" name="me_shopname" id="me_shopname" value="" placeholder="Shop Name" required data-fv-notempty-message="The shop name is required and cannot be empty" />
                      </div>
                    </div>
					<div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">Shop Address</label>
                      <div class="col-sm-4">
                        <textarea class="form-control" name="me_shopadd" id="me_shopadd"  placeholder="Complete Address" required data-fv-notempty-message="Please enter a shop address"/></textarea>
                      </div>
                    </div>
					<div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">Area Name</label>
                      <div class="col-sm-4">
                        <input class="form-control" type="text" name="me_area" id="me_area" value="" placeholder="Area" required data-fv-notempty-message="The area name is required and cannot be empty" />
                      </div>
                    </div>
					<div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">Landmark</label>
                      <div class="col-sm-4">
                        <input class="form-control" type="text" name="me_landmark" id="me_landmark" value="" placeholder="Land Mark" required data-fv-notempty-message="The landmark is required and cannot be empty"  />
                      </div>
                    </div>
					<div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">Pin Code</label>
                      <div class="col-sm-4">
                       <input class="form-control" type="text" name="me_pcode" id="me_pcode" value="" placeholder="Pincode" required data-fv-notempty-message="The pin code is required and cannot be empty" data-fv-integer="true" data-fv-integer-message="Pin code must be integer" data-fv-stringlength 
					   data-fv-stringlength-min="6" data-fv-stringlength-message="Pin code must be minimum 6 digits" maxlength="6" />
                      </div>
                    </div>
					<div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">Primary Contact Number</label>
                      <div class="col-sm-4">
                        <input class="form-control" type="text" name="me_mno1" id="me_mno1" value="" placeholder="Phone" required data-fv-notempty-message="Please enter a primary contact number" data-fv-integer="true" data-fv-integer-message="Phone number must be integer" data-fv-stringlength
						data-fv-stringlength-min="10" data-fv-stringlength-message="Phone number must be minimum 10 digits"
						 maxlength="10"/>
                      </div>
                    </div>
					<div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">Secondary Contact Number</label>
                      <div class="col-sm-4">
                        <input class="form-control" type="text" name="me_mno2"  id="me_mno2" value="" placeholder="Phone2" required data-fv-notempty-message="Please enter a secondary contact number" data-fv-integer="true" data-fv-integer-message="Phone number must be integer" data-fv-stringlength 
						data-fv-stringlength-min="10" data-fv-stringlength-message="Phone number must be minimum 10 digits"
						maxlength="10"/>
                      </div>
                    </div>
					<div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">Owner Has Android Mobile</label>
                      <div class="col-sm-4">
                        <input  type="radio" id="me_android" name="me_android"  value="Yes" required data-fv-notempty-message="The Owner Has Android Mobile is required"/>&nbsp;&nbsp;Yes
					    <input type="radio" id="me_android" name="me_android" value="No" />&nbsp;&nbsp;No
                      </div>
                    </div><div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">City Name</label>
                      <div class="col-sm-4">
                        <select class="form-control" input name="me_ci_id" id="me_ci_id" data-fv-notempty data-fv-notempty-message="The city name is required">
							<option value="">selected</option>
							<?php 
							if(count($this->cities)!=0){foreach($this->cities as $citys){
							?>
							<option value="<?php echo $citys['ci_id'];  ?>"><?php echo $citys['ci_name']; ?></option>
							<?php
							}
							}							
							?>
						</select>
                      </div>
                    </div><div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">Experience</label>
                      <div class="col-sm-4">
                        <select class="form-control" input name="me_experience" id="me_experience" data-fv-notempty data-fv-notempty-message="The experience is required">
							<option value="1-3">1-3</option>
							<option value="4-6">4-6</option>
							<option value="7-9">7-9</option>
							<option value="9-12">9-12</option>
							<option value="12 Above">12 Above</option>
						</select>
                      </div>
                    </div><div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">No of Employees</label>
                      <div class="col-sm-4">
                        <select class="form-control"  name="me_no_of_employees" id="me_no_of_employees" data-fv-notempty data-fv-notempty-message="The no of employees is required" >
						<option value="2">2</option>
						<option value="3">3</option>
						<option value="4">4</option>
						<option value="5">5</option>
						<option value="6">6</option>
						<option value="7">7</option>
						<option value="8">8</option> 
						<option value="9">9</option>
						<option value="10">10</option> 
						</select>
                      </div>
                    </div><div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">Special Bikes</label>
                      <div class="col-sm-4">
                        <select class="form-control" id="me_sb_id" name="me_sb_id" multiple data-fv-notempty data-fv-notempty-message="The special bikes is required">
							<option value="">selected</option>
							<?php 
							if(count($this->sBList)!=0){foreach($this->sBList as $list){
							?>
							<option value="<?php echo $list['sb_id'];  ?>"><?php echo $list['sb_name']; ?></option>
							<?php
							}
							}							
							?>
						</select>
                      </div>
                    </div>
					<input type="hidden" id="me_id" name="me_id" value="">
					<div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">Photo of Owner With Shop</label>
                      <div class="col-sm-4">
                        <input  type="file" name="me_shop_photo" id="me_shop_photo" required data-fv-notempty-message="The photo of owner with shop is required and cannot be empty"  />
						<input type="hidden" id="hid_shop_photo" name="hid_shop_photo" value="">
						<span id="shopPhotoError" name="shopPhotoError" style="color:red"></span>
                      </div>
                    </div>
					<div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">ID Proof Type</label>
                      <div class="col-sm-4">
                        <select class="form-control" input name="me_proof_name" id="me_proof_name" data-fv-notempty data-fv-notempty-message="The ID Proof Type is required">
							<option value="">None</option>
							<option value="Aadhar Card">Aadhar Card</option>
							<option value="Voter Card">Voter ID</option>
							<option value="Driving licence">Driving Licence</option>                
							<option value="Ration Card">Ration Card</option>
							<option value="PAN Card">PAN Card</option>
							<option value="Others">Others</option>
						</select>
                      </div>
                    </div>
					<div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">Shop Id Proof</label>
                      <div class="col-sm-4">
                       <input type="file" name="me_proof_photo" id="me_proof_photo"  required data-fv-notempty-message="The shop id proof is required and cannot be empty" />
						<input type="hidden" id="hid_proof_photo" name="hid_proof_photo" value="">
						<span id="proofPhotoError" name="proofPhotoError" style="color:red"></span>
                      </div>
                    </div>
					<div class="form-group">
                      <label for="inputEmail3" class="col-sm-2 control-label">Have Union</label>
                      <div class="col-sm-4">
                        <input  type="radio" id="me_have_union"  name="me_have_union" value="Yes" required data-fv-notempty-message="The have union is required" />&nbsp;&nbsp;Yes
					    <input type="radio" id="me_have_union" name="me_have_union" value="No" />&nbsp;&nbsp;No
                      </div>
                    </div>
                </div>
				<input type="hidden" id="me_u_id" name="me_u_id" value="<?php if(isset($_SESSION['user']['userId']) && $_SESSION['user']['userId']!=""){ echo $_SESSION['user']['userId']; }?>">
				<div class="box-footer">
					<a class="btn btn-default" href="<?php echo $baseUrl;?>/shops-list">Cancel</a>
					<button type="submit"  class="btn btn-info pull-right">Save</button>
				</div>

                </form>

            </div>

            </div>

        </div>

		 </section>

</div>
<script>
$(document).ready(function() {
	    $('#shopForm').formValidation().on('success.form.fv', function(e) { 
			 e.preventDefault();
		 });
	   // File uploads
       $('#me_shop_photo').on('change', function() {
			var val = $('#me_shop_photo').val();
			switch(val.substring(val.lastIndexOf('.') + 1).toLowerCase()){
				case 'gif': case 'jpg': case 'png': case 'jpeg':
					if($("#me_shop_photo").prop("files")[0].size <= 2048000){
						$("#loadedImage").show();
						var file_data = $("#me_shop_photo").prop("files")[0]; 
						var form_data = new FormData();   
						form_data.append("pre-file", $("#hid_shop_photo").val());
						form_data.append("type-upload", 1);
						form_data.append("upload-name", "shop");						
						form_data.append("file", file_data);
						var url= baseUrl+'/upload-shop-images';
						$.ajax({
							type:'POST',
							url:   url,
							dataType: "json",
							contentType: false,
							processData: false,
							enctype: 'multipart/form-data',
							data:form_data,
							success: function(result){
								$("#loadedImage").hide();
								if(result.output=='success'){
									$("#shopPhotoError").html("");
									$("#hid_shop_photo").val(result.file_name);
								}else if(result.output=='exe'){
									$("#me_shop_photo").val("");
									$("#hid_shop_photo").val("");
									$("#shopPhotoError").html("Upload image only");
								}else{
									$("#me_shop_photo").val("");
									$("#hid_shop_photo").val("");
									$("#shopPhotoError").html("Upload Error");
								}
							}
						});
					}else{
						$("#me_shop_photo").val("");
						$("#hid_shop_photo").val("");
						$("#shopPhotoError").html("Image size should be below 2MB");
					}
					break;
				default:
						$("#me_shop_photo").val("");
						$("#hid_shop_photo").val("");
						$('#shopPhotoError').html('Please upload image only');
						break;
			}
		});
		$('#me_proof_photo').on('change', function() {
			var val = $('#me_proof_photo').val();
			switch(val.substring(val.lastIndexOf('.') + 1).toLowerCase()){
				case 'gif': case 'jpg': case 'png': case 'jpeg':
					if($("#me_proof_photo").prop("files")[0].size <= 2048000){
					$("#loadedImage1").show();
					var file_data = $("#me_proof_photo").prop("files")[0]; 
					var form_data = new FormData();
					form_data.append("pre-file", $("#hid_proof_photo").val());			
					form_data.append("type-upload", 1);
					form_data.append("upload-name", "id_proof");					
					form_data.append("file", file_data) ;
					var url= baseUrl+'/upload-shop-images';
					$.ajax({
						type:'POST',
						url:   url,
						dataType: "json",
						contentType: false,
						processData: false,
						enctype: 'multipart/form-data',
						data:form_data,
						success: function(result){
							$("#loadedImage1").hide();
							if(result.output=='success'){
								$("#proofPhotoError").html("");
								$("#hid_proof_photo").val(result.file_name);
							}else if(result.output=='exe'){
								$("#me_proof_photo").val("");
								$("#hid_proof_photo").val("");
								$("#proofPhotoError").html("Upload image only");
							}else{
								$("#me_proof_photo").val("");
								$("#hid_proof_photo").val("");
								$("#proofPhotoError").html("Upload Error");
							}
						}
					});
					}else{
						$("#me_proof_photo").val("");
						$("#hid_proof_photo").val("");
						$("#proofPhotoError").html("Image size should be below 2MB");
					}
					break;
				default:
						$("#me_proof_photo").val("");
						$("#hid_proof_photo").val("");
						$('#proofPhotoError').html('Please upload image only');
						break;
			}
		});	
	});
		function addShop(){
		$('#shopForm').formValidation() .on('success.form.fv', function(e) { 
			e.stopImmediatePropagation();
				var me_fname    = $("#me_fname").val();
				var me_lname    = $("#me_lname").val();
				var me_shopname = $("#me_shopname").val();
				var me_shopadd  = $("#me_shopadd").val();
				var me_area     = $("#me_area").val();
				var me_landmark = $("#me_landmark").val();
				var me_pcode    = $("#me_pcode").val();
				var me_mno1     = $("#me_mno1").val();
				var me_mno2     = $("#me_mno2").val();
				var me_android  = $("input[name=me_android]:checked").val();
				var me_experience = $("#me_experience").val();
				var me_no_of_employees = $("#me_no_of_employees").val();
				var me_sb_id = $("#me_sb_id").val();
				var shop_photo = $("#hid_shop_photo").val();
				var proof_photo = $("#hid_proof_photo").val();
				var me_proof_name = $("#me_proof_name").val();
				var me_have_union = $("input[name=me_have_union]:checked").val();
				var me_ci_id = $("#me_ci_id").val();
				var me_id = $("#me_id").val();
				var me_u_id    = $("#me_u_id").val();
				var initialLocation;
				var lat = '';
				var lang = '';
				if (navigator.geolocation)  {
					browserSupportFlag = true;
					navigator.geolocation.getCurrentPosition(function (position) {
						// initialLocation = new google.maps.LatLng(position.coords.latitude,
						// position.coords.longitude);
						lat  = position.coords.latitude;
						lang = position.coords.longitude;
						$.ajax({
							type		:	'POST',
							url			:  	baseUrl+'/add-shop',
							dataType	: 	"json",
							data		:	{me_id:me_id,me_fname:me_fname,me_lname:me_lname,me_shopname:me_shopname,me_shopadd:me_shopadd,me_area:me_area,me_landmark:me_landmark,me_pcode:me_pcode,me_mno1:me_mno1,me_mno2:me_mno2,me_android:me_android,me_experience:me_experience,me_have_union:me_have_union,me_u_id:me_u_id,me_shop_photo:shop_photo,me_proof_photo:proof_photo,me_proof_name:me_proof_name,me_no_of_employees:me_no_of_employees,me_lat:lat,me_lang:lang,me_sb_id:me_sb_id,me_ci_id:me_ci_id},
							success: function(data){
								if(data.status=='success'){
									 window.location = baseUrl+"/shops-list";
								}
							}
						});
					}, function () {
					});				
				} 
				e.preventDefault();
			});
		}
</script>