  <?php
		$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
		$baseUrl = $header->headerarray['baseUrl'];
		$basePath = $header->headerarray['basePath'];
	?>
  <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
           Assigned Service List
          </h1>
          <ol class="breadcrumb">
            <?php if(isset($_SESSION['user']['ut_type_name']) && $_SESSION['user']['ut_type_name']!="admin"){?>
			<li><a href="<?php echo $baseUrl?>/steps-process?id=1"><i class="fa fa-dashboard"></i> Home</a></li>
			<?php } else {?>
			<li><a href="<?php echo $baseUrl?>/dashboard"><i class="fa fa-dashboard"></i> Home</a></li>
			<?php } ?>
            <li class="active">Assigned Service List</li>
          </ol>
        </section>
        <!-- Main content -->
        <section class="content">
          <!-- Info boxes -->
          <div class="row">
            		         
          </div><!-- /.row -->

		<div class="box">
                <div class="box-body assignedList">
                 
                </div><!-- /.box-body -->
              </div><!-- /.box -->
		</section>
    </div><!-- /.content-wrapper -->
<script>
  $(function () {	
	$(".assignedList").html("Please wait loading.....");
	$.ajax({
			type:	'GET',
			dataType:'json',
			url: baseUrl+'/assigned-services?sRch=<?php echo time();?>',
			success: function(data){			
			$('.assignedList').html('<table id="assignedList" class="table table-bordered table-striped"><thead><tr><th>Booking ID</th><th>Date</th><th>Time</th><th>Assigned To</th><th>Re Assign</th></tr></thead><tbody></tbody></table>');				
			var oTable = $('#assignedList').dataTable( {
					aoColumnDefs: [{bSortable: false,
									aTargets: [ 0 ]
									}],
					"bStateSave": false,
					"bAutoWidth": true,
					"sRowSelect": "multi",
					"sPaginationType": "full_numbers",
					"bProcessing": true,
					"aaData": data.aaData,
					"aoColumns": [
						{ "mData": "bo_track_code" },
						{ "mData": "bo_estimated_date" },
						{ "mData": "bo_estimated_time" },
						{ "mData": "u_name" },
						{ "mData": "action"},						
					] 
				});	
			}
		});
  });
</script>