<?php
	$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
	$baseUrl = $header->headerarray['baseUrl'];
	$basePath = $header->headerarray['basePath'];
?>
<div class="content-wrapper">
   <section class="content-header">
      <h1>
         Processing View
      </h1>
      <ol class="breadcrumb">
			<?php if(isset($_SESSION['user']['ut_type_name']) && $_SESSION['user']['ut_type_name']!="admin"){?>
			 <li><a href="<?php echo $baseUrl?>/steps-process?id=1"><i class="fa fa-dashboard"></i> Home</a></li>
		   <?php } else {?>
		   <li><a href="<?php echo $baseUrl?>/dashboard"><i class="fa fa-dashboard"></i> Home</a></li>
		   <?php } ?>
         <li class="active">Service View</li>
      </ol>
   </section>
   <!-- Main content -->
   <section class="content">
      <div class="row">
         <div class="col-md-6">
            <div class="box box-primary">
               <div class="box-body box-profile">
                  <h3 class="profile-username text-center"><?php if(isset($this->gBInfo->ud_first_name) && $this->gBInfo->ud_first_name!=""){ echo ucfirst($this->gBInfo->ud_first_name);}else if(isset($this->gBInfo->gu_fname) && $this->gBInfo->gu_fname!=""){ echo ucfirst($this->gBInfo->gu_fname); }else{}?></h3>
                     <ul class="list-group list-group-unbordered">
                        <li class="list-group-item">
                           <b>First Name</b> <a class="pull-right"><?php if(isset($this->gBInfo->ud_first_name) && $this->gBInfo->ud_first_name!=""){ echo ucfirst($this->gBInfo->ud_first_name);}else if(isset($this->gBInfo->gu_fname) && $this->gBInfo->gu_fname!=""){ echo ucfirst($this->gBInfo->gu_fname); }else{}?></a>
                        </li>
                        <li class="list-group-item">
                           <b>Last Name</b> <a class="pull-right"><?php if(isset($this->gBInfo->ud_last_name) && $this->gBInfo->ud_last_name!=""){ echo ucfirst($this->gBInfo->ud_last_name);}else if(isset($this->gBInfo->gu_lname) && $this->gBInfo->gu_lname!=""){ echo ucfirst($this->gBInfo->gu_lname); }else{}?></a>
                        </li>
                        <li class="list-group-item">
                           <b>Mobile Number</b> <a class="pull-right"><?php if(isset($this->gBInfo->u_phone) && $this->gBInfo->u_phone!=""){ echo $this->gBInfo->u_phone;}else if(isset($this->gBInfo->gu_phone) && $this->gBInfo->gu_phone!=""){ echo $this->gBInfo->gu_phone; }else{}?></a>
                        </li>
                        <li class="list-group-item">
                           <b>Email ID</b> <a class="pull-right"><?php if(isset($this->gBInfo->u_email) && $this->gBInfo->u_email!=""){ echo $this->gBInfo->u_email;}else if(isset($this->gBInfo->gu_email) && $this->gBInfo->gu_email!=""){ echo $this->gBInfo->gu_email; }else{}?></a>
                        </li>
                        <li class="list-group-item">
                           <b>Address</b> <a class="pull-right"><?php echo $this->gBInfo->sa_address;?></a>
                        </li>
                     </ul>
				  <input type="hidden" id="boid" name="boid" value="<?php if(isset($this->gBInfo->bo_id) && $this->gBInfo->bo_id!=""){ echo $this->gBInfo->bo_id;}?>">
               </div>
            </div>
            <div class="box box-primary">
			    <li class="list-group-item">
                    <b style="text-transform:uppercase;">Customer Request</b>
                </li>
				<li class="list-group-item">
				   <b>Booking ID</b> <a class="pull-right"><?php if(isset($this->gBInfo->bo_track_code) && $this->gBInfo->bo_track_code!=""){ echo $this->gBInfo->bo_track_code;}?></a>
				</li>
				<li class="list-group-item">
				   <b>Info</b> <a class="pull-right"><?php if(isset($this->gBInfo->bo_message) && $this->gBInfo->bo_message!=""){ echo $this->gBInfo->bo_message;}echo $this->gBInfo->bo_message;?></a>
				</li>
				<li class="list-group-item">
				   <b>Date</b> <a class="pull-right"><?php if(isset($this->gBInfo->bo_estimated_date) && $this->gBInfo->bo_estimated_date!=""){ echo $this->gBInfo->bo_estimated_date;}?></a>
				</li>
				<li class="list-group-item">
				   <b>Time</b> <a class="pull-right"><?php if(isset($this->gBInfo->bo_estimated_time) && $this->gBInfo->bo_estimated_time!=""){ echo $this->gBInfo->bo_estimated_time;}?></a>
				</li>
            </div>
			<!--<?php if(isset($this->assinedList->be_assigned_u_id) && $this->assinedList->be_assigned_u_id!="" && $this->assinedList->be_assigned_u_id!="0"){?>
			<div class="box box-primary">
					 <li class="list-group-item">
                        <b style="text-transform:uppercase;">Service Provider</b>
                     </li>					 
					 <li class="list-group-item">
                        <b>Shop Name</b> <a class="pull-right"><?php if(isset($this->gBInfo->me_shopname) && $this->gBInfo->me_shopname!=""){ echo ucfirst($this->gBInfo->me_shopname); } ?></a>
                     </li>
                     <li class="list-group-item">
                        <b>Shop ID</b> <a class="pull-right"><?php if(isset($this->gBInfo->me_unique_code) && $this->gBInfo->me_unique_code!=""){ echo $this->gBInfo->me_unique_code; } ?></a>
                     </li>
                     <li class="list-group-item">
                        <b>Address</b> <a class="pull-right"><?php if(isset($this->gBInfo->me_area) && $this->gBInfo->me_area!=""){  echo $this->gBInfo->me_area; } ?> , <?php if(isset($this->gBInfo->me_landmark) && $this->gBInfo->me_landmark!=""){ echo $this->gBInfo->me_landmark; } ?>, <?php echo ucfirst($this->gBInfo->ci_name);?> , <?php if(isset($this->gBInfo->me_pcode) && $this->gBInfo->me_pcode!=""){ echo $this->gBInfo->me_pcode; }?> </a>
                     </li>
                     <li class="list-group-item">
                        <b>Mobile Number</b> <a class="pull-right"><?php if(isset($this->gBInfo->me_mno1) && $this->gBInfo->me_mno1!=""){  echo $this->gBInfo->me_mno1; } ?>,  <?php if(isset($this->gBInfo->me_mno2) && $this->gBInfo->me_mno2!=""){  echo $this->gBInfo->me_mno2; } ?></a>
                     </li>
            </div>
			<?php } ?>-->
         </div>
		 <input type="hidden" id="hid_be_assigned_u_id" name="hid_be_assigned_u_id" value="<?php if(isset($this->assinedList->be_assigned_u_id) && $this->assinedList->be_assigned_u_id!="" ){ echo $this->assinedList->be_assigned_u_id; } ?>">
         <div class="col-md-6">
            <div class="box box-success">
               <div class="box-header">
                  <i class="fa fa-th"></i>
                  <h3 class="box-title">Assigned To</h3>
                  <div class="box-tools pull-right" data-toggle="tooltip" title="Status"></div>
               </div>
			   
               <div class="box box-primary" style="border-top:none;">
                  <div class="box-body box-profile">
				<?php if(isset($_SESSION['user']['u_ut_type_id']) && $_SESSION['user']['u_ut_type_id']=="1"){?>				 <b>Team Leads</b>
					<select class="form-control" id="selectLead" name="selectLead" onChange="selectExecutive();">
						<option value="">select a team lead</option>
						<?php foreach($this->teamLeadsList as $teamLeads){?>
						<?php if(isset($this->assinedList->be_assigened_by_u_id) && $this->assinedList->be_assigened_by_u_id!=""){if($this->assinedList->be_assigened_by_u_id==$teamLeads['u_id']){?>
						<option value="<?php echo $teamLeads['u_id'];?>" selected="selected"><?php echo $teamLeads['u_name']; ?></option>
						<?php }else{ ?>
						<option value="<?php echo $teamLeads['u_id'];?>"><?php echo ucfirst($teamLeads['u_name']); ?></option>
						<?php }}else{ ?>
						<option value="<?php echo $teamLeads['u_id'];?>"><?php echo ucfirst($teamLeads['u_name']); ?></option>
						<?}?>
						<?}?>
					</select>
					<b> Executive </b>
					<select class="form-control" id="selectExecutive" name="selectExecutive">
						<option value=""> selecte a executive  </option>	
						<!--<?php if(isset($this->assinedList->be_assigened_by_u_id) && $this->assinedList->be_assigned_u_id!="" && $this->assinedList->be_assigned_u_id!="0"){ ?>
							<?php foreach($this->teamLeadsList as $teamLeads){ if($this->assinedList->be_assigened_by_u_id==$teamLeads['u_id']){?>
						<option value="<?php echo $teamLeads['u_id'];?>" selected="selected"><?php echo ucfirst($teamLeads['u_name']); ?> ( <?php echo ucfirst($teamLeads['ut_type_name']); ?> )</option>
						<?php }}?>
						<?php } ?>	-->										
						<?php foreach($this->leadExec as $executives){?>
						<?php if(isset($this->assinedList->be_assigned_u_id) && $this->assinedList->be_assigned_u_id!=""){
						if($this->assinedList->be_assigned_u_id==$executives['u_id']){?>
						<option value="<?php echo $executives['u_id']; ?>" selected><?php echo ucfirst($executives['u_name']); ?></option>
						<?php }else{ ?>
						<option value="<?php echo $executives['u_id']; ?>"><?php echo ucfirst($executives['u_name']); ?></option>
						<?php }}}?>
					</select>
				<?php }else{ ?>
					<b>Executives</b>
					<select class="form-control" id="selectExecutive" name="selectExecutive">
					<option value="">Selecte a executives</option>
						<?php foreach($this->executivesList as $executives){?>
						<?php if(isset($this->assinedList->be_assigned_u_id) && $this->assinedList->be_assigned_u_id!=""){if($this->assinedList->be_assigned_u_id==$executives['u_id']){?>
						<option value="<?php echo $executives['u_id']; ?>" selected><?php echo ucfirst($executives['u_name']); ?></option>
						<?php }else{ ?>
						<option value="<?php echo $executives['u_id']; ?>"><?php echo ucfirst($executives['u_name']); ?></option>
						<?php }}else{ ?>
						<option value="<?php echo $executives['u_id']; ?>"><?php echo ucfirst($executives['u_name']); ?></option>
						<?}?>
						<?}?>
					</select>
					<input type="hidden" id="hidleadId" name="hidleadId" value="<?php echo $_SESSION['user']['userId'];?>" >
				<?php } ?>
                  </div>
               </div>
			   
            </div>
         </div>
		 <div class="pull-left">
                <button onClick="_selfAssign('<?php if(isset($this->gBInfo->bo_id) && $this->gBInfo->bo_id!=""){ echo $this->gBInfo->bo_id;}?>','<?php echo $_SESSION['user']['ut_type_name']; ?>','<?php echo $_SESSION['user']['userId']; ?>');" class="btn btn-primary">Self Assign</button>
         </div>
		 <div class="pull-right">
                <button onClick="assignTomembers('<?php if(isset($this->gBInfo->bo_id) && $this->gBInfo->bo_id!=""){ echo $this->gBInfo->bo_id;}?>','<?php echo $_SESSION['user']['ut_type_name']; ?>');" class="btn btn-primary">Assigned</button>
         </div>
      </div>
   </section>
</div>