<div class="content-wrapper">
   <section class="content-header">
	  <h1>
	   Request Processing - Step <?php if(isset($_GET['id']) && $_GET['id']!=""){ echo $_GET['id']; }?>
	  </h1>
	  <ol class="breadcrumb">
		<?php if(isset($_SESSION['user']['userId']) && $_SESSION['user']['ut_type_name']!="admin"){?>
			<li><a href="<?php echo $baseUrl;?>/steps-process?id=1"><i class="fa fa-dashboard"></i> Home</a></li>
			<?php }else{ ?>
			<li><a href="<?php echo $baseUrl?>/dashboard"><i class="fa fa-dashboard"></i> Home</a></li>
			<?php } ?>
		
		<li class="active">Request Processing</li>
	  </ol>
	</section>
	<section class="content">
		<div class="row">
		</div><!-- /.row -->
		<div class="box">
			<div class="box-body stepsProcess">
			 
			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</section>
</div><!-- /.content-wrapper -->
<script>
  $(function () {
	var url = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');	
	for (var i = 0; i < url.length; i++) {
		var urlparam = url[i].split('=');
		if (urlparam[0] == 'id') {
			var id = urlparam[1];
		}
	}
	if(id=='1'){
		var textStatus = 'AssignToServiceProvider';
	}else{
		var textStatus = 'Proccessing';
	}
	$(".stepsProcess").html("Please wait loading.....");
	$.ajax({
			type:	'GET',
			dataType:'json',
			url: baseUrl+'/steps/'+id+'/<?php echo time(); ?>',
			success: function(data){			
			$('.stepsProcess').html('<table id="stepsProcess" class="table table-bordered table-striped"><thead><tr><th>Booking ID</th><th>Name</th><th>Level Type</th><th>Mobile Number</th><th>Date and Time</th><th>Status</th><th>'+textStatus+'</th></tr></thead><tbody></tbody></table>');				
			var oTable = $('#stepsProcess').dataTable( {
					aoColumnDefs: [{bSortable: false,
									aTargets: [ 0 ]
									}],
					"bStateSave": true,
					"bAutoWidth": true,
					"sRowSelect": "multi",
					"sPaginationType": "full_numbers",
					"bProcessing": true,
					"aaData": data.aaData,
					"aoColumns": [
						{ "mData": "bo_track_code" },
						{ "mData": "u_name" },
						{ "mData": "u_type" },
						{ "mData": "u_phone" },
						{ "mData": "bo_created_at" },
						{ "mData": "bo_sta_status"},						
						{ "mData": "action"},						
					] 
				});	
			}
		});
  });
</script>