<div class="headerLine careers_bg"></div>
	<div class="container">
    <div class="row pad_sit">
        <h3 style="text-align:center;"><span class="hedd">Careers</span></h3>
        <br>
        <br>
        <p class="text-justify mb20">
            We welcome people from all backgrounds such as EA CA MBA B.COM B.TECH and more.
            Our distinctive approach to diversity is based on a belief that each of us is personally accountable
            for creating and sustaining an inclusive environment. Diversity and inclusion enhance our
            perspectives and our ability to give our clients a distinctive experience.
            Whether you're a fresh graduate or an experienced professional, we believe that a career at
            Umpire Tax Solutions will set you apart.
            Forward your C.V to <a style="font-weight:bold;">Hello@umpiretaxsolutions.com</a><br>
            We’ll bring a world of opportunities.
        </p>
    </div>
</div>
