<div class="headerLine contact_bg img-responsive"></div>
<div class="container">
    <div class="row">
        <h3 style="text-align:center;"><span class="hedd">Contact Us</span></h3><br>
        <div class="col-sm-6">
            <div class="col-sm-12">
                <div class="col-sm-11">
                    <h4 style="color: #16b1df;font-size: 20px;">Umpire Tax Solutions,LLC</h4>
                    <address>
                    <img src="<?php echo $basePath;?>/img/contact.jpg" alt="" style="float:left; margin-right:20px; width:206px ">
					<div class="Contacts">
                        <p><strong>Corporate Office:</strong> <br>9500 Grove Crest Ln<br>
                            Charlotte NC 28262</p>
                        <p><strong>Processing Center:</strong>  <br>Habsiguda Hyderabad<br>
								 &nbsp;Telangana</p><br>

                        <p><strong>E-mail:</strong> Hello@umpiretaxsolutions.com</p>
                        </div>
                    </address>

                </div>

            </div>
          
        </div>
        <div class="col-sm-6">
        <form id="contactForm" name="contactForm"  onSubmit="contactFormFun()" data-fv-message="This value is not valid" data-fv-icon-valid="glyphicon" data-fv-icon-invalid="glyphicon" data-fv-icon-validating="glyphicon glyphicon-refresh">
            <h4 style="color: #16b1df;font-size: 20px;">Contact Form</h4>

            <div class="form-group">
                <label for="usr">Name</label>
				<input type="text" class="form-control" id="c_name" name="c_name" placeholder="Name" required data-fv-notempty="true" data-fv-notempty-message="The name is required">
            </div>
            <div class="form-group">
                <label for="usr">Email</label>
               <input type="text" class="form-control" id="c_email" name="c_email" placeholder="Email"required data-fv-notempty-message="The email is required"	data-fv-regexp="true"  data-fv-regexp-regexp="^[_a-z0-9]+(\.[_a-z0-9]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$"  data-fv-regexp-message="The email is not a valid">
            </div>
            <div class="form-group">
                <label for="usr">Phone</label>
               <input type="text" class="form-control" id="c_phone" name="c_phone" placeholder="Mobile Number" required data-fv-notempty-message="Please enter a phone" data-fv-integer="true" data-fv-integer-message="The value is not an integer" maxlength="10" data-fv-stringlength data-fv-stringlength-min="10" data-fv-stringlength-message="Phone number must be 10 digits only" maxlength="10">
            </div>
            <div class="form-group">
                <label>Message</label>
               <textarea class="form-control" type="textarea" id="c_message" name="c_message" placeholder="Message" maxlength="140" rows="7" required data-fv-notempty="true" data-fv-notempty-message="The message is required"></textarea>
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-lg" type="submit">Submit
                </button> &nbsp;&nbsp;<span id="successContact" name="successContact" style="color:green"> </span>
            </div>
</form>

        </div>


    </div>
	

</div>
