<!--<div class="headerLine terms_bg"></div>-->
<img class="img-responsive" src="<?php echo $basePath;?>/img/disclaimer.png">
<style>
	.container h2 {
		color:#00c4fd;
		font-size:20px;
	}
	.container h1 {
		font-size:28px;
	}
</style>
<div class="container">
	<h1>Disclaimer Agreement</h1>
	<h2>Welcome to Umpire Tax Solutions, LLC.</h2>

	<p>This web-site <a hidden="http://www.umpiretaxsolutions.com">http://www.umpiretaxsolutions.com</a> ("Website") is a public resource for general information about Umpire Tax Solutions.</p>
	<p>The material on our Website has been prepared and published for general information only. There is no effort or intention to solicit new clients or new engagements from existing clients by way of this web site.</p>
	<p>By using this Web Site, you agree to be bound by the following terms and all applicable laws and regulations (including export and re-export control laws), and agree that you are responsible for compliance with any applicable local laws</p>
	<p><strong>Federal law</strong> requires this consent form be provided to you. Unless authorized by  law, we cannot disclose, without your consent, your tax return information to  third parties for purposes other than the preparation and filing of your tax  return. If you consent to the disclosure of your tax return information,  Federal law may not protect your tax return information from further use or  distribution.</p>
	<p><strong>Umpire Tax  Solutions, LLC</strong> has endeavored to comply with all applicable  legal and ethical requirements in compiling this site. Under no circumstances  will Umpire Tax Solutions undertake any engagement that conflicts with any  ethical, statutory or other requirement applicable to the performance of  professional legal services.</p>
	<p>This consent to disclose may result in your tax  return information being disclosed to a tax return preparer located outside the  United States, including your personally identifiable information such as your  Social Security Number (&ldquo;SSN&rdquo;). If you consent to the disclosure of your tax  return information, Federal agencies may not be able to enforce U.S. laws that  protect the privacy of your tax return information against a tax return preparer  located outside of the U.S. to which the information is disclosed.&nbsp;</p>
	<p>Umpire Tax Solutions makes no Representations  or Warranties about the Accuracy, Completeness or Suitability of any of the  Material on this Website, or on any of the sites Linked to the Website.</p>


			<h2>Security</h2>
	<p>Umpire Tax Solutions maintains physical, electronic, and procedural safeguards that comply with applicable law and federal standards. When users submit sensitive information via the website, it is protected both online and offline. Umpire Tax Solutions uses Secure Socket Layer (SSL) encryption technology to protect all sensitive information. SSL technology is the most commonly-used method on the Internet to safely transmit data. Access to your personally identifiable information is protected by a password, of your choosing, in order to maintain security for your account. Only you, or someone with whom you share your password, can access your account to make changes to your return or account information.</p>
	<p>Along with using SSL encryption to protect sensitive information online, we also take great care to protect user information offline. All user information, not just the sensitive information mentioned above, is restricted to only key employees who need the information to perform a specific job function.</p>
	<h2>Information Sharing</h2>
	<p>We will share your personally identifiable information with third parties only in the ways that are described in this privacy statement. We do not sell your personally identifiable information to third parties.</p>
	<p><strong>Warning:</strong> Once your tax return  information has been disclosed to a third party per your consent, we have no  control over what the third party does with your tax return information. If the  third party uses or discloses your tax return information for purposes other  than the purpose for which you authorized the disclosure, we are not  responsible for that unauthorized disclosure, and federal tax law may not  protect that unauthorized disclosure. </p>
	<p>Umpire tax solutions reserves the right, at  any time to modify, alter, or update the content on the website www.Umpire tax  solutions.com and/or these terms of use and disclaimer and all users shall be  bound by the terms and conditions so altered, modified or updated. Governing Law  &amp; Jurisdiction: The relationship between you and Umpire tax solutions shall  be governed by the Laws of U.S.</p>
		</ul>
	<h2>Contact Information</h2>
	<p>If you have additional questions regarding Umpire Tax Solutions, LLC Disclaimer Agreement or security policies, please send your question to <a href="mailto:Hello@umpiretaxsolutions.com">Hello@umpiretaxsolutions.com</a>.</p>
	<p>I authorize, Umpire Tax Solutions, LLC to disclose my information. Disclosure of the tax return information described above has been specifically requested by me. </p>

</div>     

	
