<div class="headerLine prof_bg"></div>
<div class="container"> <h3 style="text-align:center;"><span class="hedd">Profile</span></h3><br />

	<div class="row">

	<div class="col-md-6 animated bounceInLeft" ><i class="fa fa-angle-down right_icon mob_hid"></i>
			<h4 style="color:#2d7da4;">UMPIRE TAX SOLUTIONS</h4>
			<ul class="about_list">
				<li><i class="fa fa-check-square-o"></i> Umpire Tax Solutions, LLC is a company established with a group of Qualified professionals such as Certified Public Accountants and Enrolled Agents. Umpire Tax Solutions provide outstanding services to the clients because of our Commitment to the five underlying principles of Professionalism, Accuracy, Dedication, Integrity and Responsibility. The qualified professionals of our company hard work experience of 6 years in the fields of International Taxation and Various Financial Services.</li>
				<li><i class="fa fa-check-square-o"></i> Our expertise services are not just restricted to Individuals, We are also good in partnerships and corporations with Tax Preparation and Tax related matters. Through hard work, we have earned the respect of the business and financial communities. This respect illustrates our diverse talents, dedication and ability to respond quickly.</li>

				<li><i class="fa fa-check-square-o"></i> Our Team assists you at each level to comply with all the applicable laws in regards to the Tax filing.</li>
			</ul>

		</div>
		<div class="col-md-6 bord_left animated bounceInRight">
			<h4 class="ml20" style="text-align:left; color:#2d7da4;">Advantages with UTS....</h4>
			<p class="text-justify ml20">HOW TO PAY LESS TAXES BY TAKING THE QUALIFIED ADVANTAGES????<br> Umpire Tax will direct you in asserting the advantages which gave by the Federal and State Governments with the goal that it will help you to diminish the TAXES.</p>
			<ul class="about_list">
				<li> <i class="fa fa-check-square-o"></i>  IRA (Individual Retirement Arrangement) </li>
				<li><i class="fa fa-check-square-o"></i> HSA (Health Savings Account) </li>
				<li><i class="fa fa-check-square-o"></i>  Credits <br><ul class="SUbmenu" style="list-style:none;margin-top:2px;">
				<li><i class="glyphicon glyphicon-hand-right"></i>Educational Credits</li>
				<li><i class="glyphicon glyphicon-hand-right"></i>Foriegn Tax Credit</li>
				<li><i class="glyphicon glyphicon-hand-right"></i>Earned Income Credit</li>
				<li> <i class="glyphicon glyphicon-hand-right"></i>Child Tax Credit</li>
				 <li><i class="glyphicon glyphicon-hand-right"></i>Dependant Care Credit</li>
				</ul> 
				</li>
				<li><i class="fa fa-check-square-o"></i> Home loan Interest Deduction (U.S/Foreign)</li>
				<li><i class="fa fa-check-square-o"></i> Student loan Interest Deduction (U.S/Foreign)</li>
				<li><i class="fa fa-check-square-o"></i> Medical Expenses</li>
				<li><i class="fa fa-check-square-o"></i> Charities </li>
				<li><i class="fa fa-check-square-o"></i> Free Federal & State Filing Extensions</li>
				<li><i class="fa fa-check-square-o"></i> Free Tax Estimates </li>
				<li><i class="fa fa-check-square-o"></i> 100% Guarantee to get the Estimated Refunds</li>
			</ul>

		</div>
	</div>



	<p  style="padding:10px 0; text-align:center;"><strong>When you are ready for an appointment please give us a call at  631-407-1040<br />

		Thank you for visiting Umpire Tax Solutions LLC.</strong>
	</p>

</div>
