<?php
	$header			=	$this->action('Application\Controller\IndexController', 'headerAction');
	$baseUrl 		= 	$header->headerarray['baseUrl'];
	$basePath 		= 	$header->headerarray['basePath'];
?>
<header id="myCarousel" class="carousel slide">
	<!-- Indicators -->
	<ol class="carousel-indicators">
		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#myCarousel" data-slide-to="1"></li>
		<li data-target="#myCarousel" data-slide-to="2"></li>
		<li data-target="#myCarousel" data-slide-to="3"></li>
		<li data-target="#myCarousel" data-slide-to="4"></li>
		<li data-target="#myCarousel" data-slide-to="5"></li>
	</ol>

	<!-- Wrapper for slides -->
	<div class="carousel-inner">
		<div class="item active">
			<div><img class=""src="<?php echo $basePath; ?>/img/sl1.jpg"></div>
			<div class="carousel-caption">
				<h2>Caption 1</h2>
			</div>
		</div>
		<div class="item">
			<div><img class="" src="<?php echo $basePath; ?>/img/ban4.png"></div>
			<div class="carousel-caption">
				<h2>Caption 2</h2>
			</div>
		</div>
		<div class="item">
			<div><img src="<?php echo $basePath; ?>/img/sl2.jpg"></div>
			<div class="carousel-caption">
				<h2>Caption 3</h2>
			</div>
		</div>
		<div class="item">
			<div><img src="<?php echo $basePath; ?>/img/sl3.jpg"></div>
			<div class="carousel-caption">
				<h2>Caption 4</h2>
			</div>
		</div>
		<div class="item">
			<div><img src="<?php echo $basePath; ?>/img/sl4.jpg"></div>
			<div class="carousel-caption">
				<h2>Caption 5</h2>
			</div>
		</div> <div class="item">
			<div><img src="<?php echo $basePath; ?>/img/sl5.jpg"></div>
			<div class="carousel-caption">
				<h2>Caption 6</h2>
			</div>
		</div>
	</div>

	<!-- Controls -->
	<a class="left carousel-control" href="#myCarousel" data-slide="prev">
		<span class="icon-prev"></span>
	</a>
	<a class="right carousel-control" href="#myCarousel" data-slide="next">
		<span class="icon-next"></span>
	</a>
</header>
<div class="container mar_t20">
	<div class="">
		<div class="col-lg-12">
		   <h1 class="text-center">
				Welcome To Umpire Tax Solutions
			</h1>
			<p>Umpire Tax Solutions, LLC is a company established with a group of Qualified professionals such as Certified Public Accountants and Enrolled Agents. Umpire Tax Solutions provide outstanding services to the clients because of our Commitment to the five underlying principles of Professionalism, Accuracy, Dedication, Integrity and Responsibility. The qualified professionals of our company hard work experience of 6 years in the fields of International Taxation and Various Financial Services.</p>
		</div>
	</div>
 </div>
 <div class=" col-md-12 about_div mar_t10">
				<div class="col-md-6">
					<img class="img-responsive" src="<?php echo $basePath; ?>/img/about.jpg" alt="">
				</div>
		<div class="col-md-6">
				<h2>Advantages with UTS.... </h2>
			<p class="head_process text-justify">

			HOW TO PAY LESS TAXES BY TAKING THE QUALIFIED ADVANTAGES????<br><br>
			Umpire Tax will direct you in asserting the advantages which gave by the Federal and State Governments with the goal that it will help you to diminish the TAXES.

			</p>
			<ul class="about_list">
			<li> IRA (Individual Retirement Arrangement)</li>
			<li> HSA (Health Savings Account)</li>
			<li> Credits <br>
				<ul class="SUbmenu">
					<li>Educational Credits</li>
					<li>Foriegn Tax Credit</li>
					<li>Earned Income Credit</li>
					<li>Child Tax Credit</li>
					<li>Dependant Care Credit</li>
				</ul>
			</li>
			<li> Home loan Interest Deduction (U.S/Foreign)</li>
			<li> Student loan Interest Deduction (U.S/Foreign)</li>
			<li> Medical Expenses</li>
			<li> Charities</li>
			<li> Free Federal & State Filing Extensions</li>
			<li> Free Tax Estimates</li>
			<li> 100% Guarantee to get the Estimated Refunds</li>

			<a href="#" class="more-btn btn btn-primary mar_t10" ng-click="referals()"><i class="fa fa-user"></i> Refer a
				Friend</a>
			</ul>	
		</div>
</div>
<div class="container">
		<div class="col-md-12">
			<div class="text-center">
				<h1>Contact Us</h1>
			</div>
				<div class="col-md-4">
					<img  class="img-responsive"src="<?php echo $basePath; ?>/img/contact.jpg" alt="">
				</div>
				<div class="col-md-3">
					<h3>Umpire Tax Solutions,LLC</h3>
						<address>
							<p><strong>Corporate Office:</strong> <br>9500 Grove Crest Ln<br>
							 Charlotte NC 28262</p>
							<p><strong>Processing Center:</strong> <br>T-Hub Hyderabad<br>
								 &nbsp;Telangana</p>
							 
							<p><strong>E-mail:</strong> Hello@umpiretaxsolutions.com</p>
						</address>
						<br/>

						<h3>Social</h3>
						<p><i class="icon-facebook icon"></i> <a href="#">Facebook</a></p>
						<p><i class="icon-google_plus icon"></i> <a href="#">Google+</a></p>
						<p class="margin-bottom"><i class="icon-linked_in icon"></i> <a
								href="#">LinkedIn</a></p>
				</div>
				
			<div class="col-md-5">
				<div class="form-area">  
					<form role="form" id="contactForm" name="contactForm"  onSubmit="contactFormFun()" data-fv-message="This value is not valid" data-fv-icon-valid="glyphicon" data-fv-icon-invalid="glyphicon" data-fv-icon-validating="glyphicon glyphicon-refresh">
					<br style="clear:both">
								<h3 style="margin-bottom: 20px;">Contact Form</h3>
								<div class="form-group">
									<input type="text" class="form-control" id="c_name" name="c_name" placeholder="Name" required data-fv-notempty="true" data-fv-notempty-message="The name is required">
								</div>
								<div class="form-group">
									<input type="text" class="form-control" id="c_email" name="c_email" placeholder="Email"required data-fv-notempty-message="The email is required"	data-fv-regexp="true"  data-fv-regexp-regexp="^[_a-z0-9]+(\.[_a-z0-9]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$"  data-fv-regexp-message="The email is not a valid">
								</div>
								<div class="form-group">
									<input type="text" class="form-control" id="c_phone" name="c_phone" placeholder="Mobile Number" required data-fv-notempty-message="Please enter a phone" data-fv-integer="true" data-fv-integer-message="The value is not an integer" maxlength="10" data-fv-stringlength data-fv-stringlength-min="10" data-fv-stringlength-message="Phone number must be 10 digits only" maxlength="10">
								</div>
								<div class="form-group">
									<input type="text" class="form-control" id="c_subject" name="c_subject" placeholder="Subject" required data-fv-notempty="true" data-fv-notempty-message="The subject is required">
								</div>
								<div class="form-group">
								<textarea class="form-control" type="textarea" id="c_message" name="c_message" placeholder="Message" maxlength="140" rows="7" required data-fv-notempty="true" data-fv-notempty-message="The message is required"></textarea>
									<span class="help-block"><p id="characterLeft" class="help-block ">You have reached the limit</p></span>                    
								</div>
						<span id="successContact" name="successContact" style="color:green"> </span>
					<button type="submit" class="btn btn-primary pull-right">Submit Form</button>
					</form>
				</div>

			</div>
		</div>
	</div>