<img class="img-responsive" src="<?php echo $basePath;?>/img/privacy.png">
<style>
	.container h2 {
		color:#00c4fd;
		font-size:20px;
	}
	.container h1 {
		font-size:28px;
	}
</style>
<div class="container">
	<h1>Umpire Tax Solutions Privacy Statement</h1>
<h2>Effective: 11/16/2015</h2>
<p>This privacy statement applies to www.UmpireTaxSolutions.com.which is owned

operated by UTS, Inc. This privacy statement describes how UTS, Inc. collects and uses 

the personally identifiable information you provide on our web 

site: www.umpiretaxsolutions.com (UTS). It also describes the choices available to you 

regarding our use of your personally identifiable information and how you can access and 

update this information. UTS treats your financial and personally identifiable information as 

confidential and will not sell or rent any information.</p>

<h2>Information Collection and Use</h2>
<p>UTS, Inc. is the sole owner of the information collected on

Information is collected in order for taxpayers to prepare and electronically file their tax 

returns. Tax return information is only disclosed to appropriate government and financial 

institutions in order to file tax returns and comply with Internal Revenue Service 

requirements. The data collected includes everything that is needed to prepare a tax return, 

such as names, Social Security numbers, birth dates, mailing address, email address, and 

any tax-related information (e.g. W-2s and 1099 forms). If a purchase is made, credit card 

information for a credit card payment or bank account information for an e-check payment 

will be gathered.</p>
<h2>Usage Information</h2>
<p>Like most websites, Umpire Tax Solutions uses log files and analytical software to track 

website usage. The information collected may include IP addresses, browser types, 

browser configuration, internet service providers (ISP), referring/exit pages, platform types, 

and number of clicks to analyze trends, administer the site, track user movement, and 

gather broad demographic information for use in improving the site. We link this 

automatically collected data to other information we collect about you.</p>

<h2>Service Announcements</h2>
<p>On rare occasions, it is necessary to send out a strictly service related announcement. For 

instance, if service is temporarily suspended for maintenance, Umpire Tax Solutions might 

send users a notification via email. </p>

<h2>Client Service</h2>
<p>Client Service for Umpire Tax Solutions is provided through our tax application or email.

When a customer support request is received, we will reply via the customer support portion 

of the application or email. If your personally identifiable information changes, or if you no 

longer desire to use our service, you may correct, update or delete it by signing in to your 

account and making any changes; we will respond within a reasonable time frame. 

However, once the IRS accepts your e-filed tax return, no changes can be made to your 

account that would change any of the information on the tax return.

We will retain your information for as long as needed to provide you services. We will retain 

and use your information as necessary to comply with our legal obligations, resolve 

disputes, and enforce our agreements. </p>

<h2>Legal Disclosures</h2>
<p>Though every effort is made to preserve user privacy, Umpire Tax Solutions may need to

disclose personally identifiable information when required by law wherein we have a good-

faith belief that such action is necessary to protect our rights, protect your safety or the 

safety of others, to investigate fraud to comply with a current judicial proceeding, a court 

order or legal process served on our website. </p>


<h2>Information Sharing</h2>
<p>We will share your personally identifiable information with third parties only in the ways that 

are described in this privacy statement. We do not sell your personally identifiable 

information to third parties. </p>

<h2>Links to 3rd Party Sites</h2>
<p>Our Site includes links to other websites whose privacy practices may differ from those of 

Umpire Tax Solutions. If you submit personally identifiable information to any of those sites, 

your information is governed by their privacy statements. We encourage you to carefully 

read the privacy statement of any website you visit.</p>

<h2>Social Media Widgets</h2>
<p>Our website includes social media widgets, such as the Facebook "Like" button, the 

"Google+" button, and other social widgets. These features may collect your IP address, the 

URL of the page you are coming from, and may set a cookie to enable the feature to 

function properly. Social media features and widgets are either hosted by a third party or 

hosted directly on our website. Your interactions with these features are governed by the 

privacy statement of the company providing it.</p>
<h2>Contact Information</h2>
<p>If you have additional questions regarding privacy or security policies, please send your 

query to <a href="#" style="color:#0092bd;">Hello@umpiretaxsolutions.com</a></p>

</div>
