 <div class="headerLine taxxenter_bg"></div>	
	<div class="container ref_btns">
    <h3 style="text-align:center;">
	<span style="float:left;" class="hedd mar_t64">Referral Program</span>
	<span><img src="<?php echo $basePath;?>/img/Referral-Rewards.png"></span>
        <a ng-click="referals()" style="margin-left:8%;">
            <button style="font-size: 20px; padding: 5px 0;" class=" mar_t64 btn btn-success col-md-2 pull-right"> Refer a Friend</button>
        </a>
    </h3>
    <br/>

    <div class="row">

        <div class="col-md-12 animated bounceInLeft"><!-- <i class="fa fa-angle-down right_icon"></i> -->
            <!--<h4 style="color:#2d7da4;">Referal Program</h4>-->
            <ul class="about_list">
                <li><i class="fa fa-check-square-o"></i>
                    <p>Apart from filing the Accurately Tax Filing at the Umpire Tax
                    Solutions, LLC you can also be awarded

                    with a cash check in the form of Referral Bonus. If you had a Great experience with our Professional

                    service(s) if we would truly appreciate your help in spreading of our Business. We realize that most
                    of

                    you do this out of the kindness of your hearts- and we are faithful to all of you. Refer your
                    friends to

                    avail our Professional services and earn 10% referral bonus on each person you refer. You have
                    also

                    chance of winning I phone 6, Dell laptop and Tab if you are among the TOP THREE REFERALS. Request

                    you to be part of our expansion of the business and also the Clients. Get awarded and make your
                    friends

                    feel great of you.

                   </p>
                    <p>
                        Please provide the following details of the Friend whom you wish to Refer.
                    </p></li>

            </ul>


        </div>
        <div class="col-md-12 animated bounceInLeft">
            <h4 style="color:#2d7da4;">Top 3 Referral Gifts</h4>
            <div class="imgDiv">
               <img class="img-responsive"src="<?php echo $basePath;?>/img/ref_img1.png">
            </div>

		
            <div class="mt20">
            <h4 style="color:#2d7da4;">Points To Consider:-</h4>
            <ul style="list-style: none">
                <li>1.&nbsp;You will be eligible for referral bonus only when you&rsquo;re friend or referred person
                    file the U.S Tax return with Umpire Tax Solutions, LLC.
                </li>

                <li>2.&nbsp;We will be paying you straight away 10% on each friend or referred person fees.</li>


                <li>3.&nbsp;If you are among the <strong>Top Three Referrals,</strong> you have chance of winning all
                    these things.
                </li>

                <li>
                    <ul class="ml30" style="margin-top: 3px;margin-bottom: 3px;">
                        <li><strong>I phone 6S –Minimum 15 Referrals</strong></li>
                        <li><strong>Dell All in one Desktop – Minimum 10 Referrals</strong></li>
                        <li><strong>Go Pro Hero camera – Minimum 6 Referrals</strong></li>
                        <li>Refer your friends and get Awarded Accordingly.</li>
                    </ul>
                </li>

                <li>4.&nbsp;To be a part of Top Three Referrals, you need to refer a minimum of <strong>6</strong>
                    people.
                </li>


                <li>5.&nbsp;Referral bonus under referral program will be given after April 20 2017 and Top 3 referral
                    gifts will be announced in the month of November 2017.
                </li>


                <li>6.&nbsp;We would like to take this opportunity and Request you to Refer your friends and be Part of
                    our Global expansion of the Business.
                </li>

                <p class="text-center" style="margin:20px 0">Thank you for Choosing Umpire Tax Solutions, LLC.</p>

        </div>


    </div>
    </div>
    </div>
