<!--<div class="headerLine terms_bg"></div>-->
<img class="img-responsive" src="<?php echo $basePath;?>/img/terms.png">
<style>
	.container h2 {
		color:#00c4fd;
		font-size:20px;
	}
	.container h1 {
		font-size:28px;
	}
</style>
<div class="container">
	<h1>Terms & Conditions </h1>
	<p>Please read carefully the terms of the agreement which follows. By accessing Umpire Tax Solutions website you agree to be bound by the terms of this agreement.  If you do not wish to be bound to the terms of this agreement, you must not access the site.</p>
	<p>The material contained in this website is of general information and compilation of statutes, circulars, and notifications etc. It is not intended to be legal advice on any particular matter. Since, the contents in this website are dynamic in nature; viewers are advised, in their own interest, to refer to relevant Government publications before arriving at any final conclusion.</p>
	<h2>Online conduct</h2>
	<p>Visitors agree to use the website only for lawful purposes and are prohibited from posting on the website any unlawful, harmful, threatening, abusive, harassing, defamatory, or obscene material of any kind, including, but not limited to, any material which encourages conduct that would constitute a criminal offense, give rise to civil liability or otherwise violate any applicable local, state, national or international law.</p>
	<h2>Information subject to change</h2>
	<p>Any information on this website may include technical inaccuracies or typographical errors. Furthermore, the information may change from time to time without any notice.
	Umpire Tax Solutions reserves the right, at any time to modify, alter, or update the content on the website <a href="www.Umpiretaxsolutions.com" target="_blank">www.Umpiretaxsolutions.com</a> and/or these terms of use and disclaimer and all users shall be bound by the terms and conditions so altered, modified or updated. Governing Law & Jurisdiction: The relationship between you and Umpire tax solutions shall be governed by the Laws of USA. You and Umpire Tax Solutions agree to submit to the personal and exclusive jurisdiction of the courts located at California USA.
	</p>
	<h2>Security of information</h2>
	<p>No data transmission over the Internet can be guaranteed as totally secure. Whilst we strive to protect such information we do not warrant and cannot ensure the security of information which you transmit to us. Accordingly, any information which you transmit to us is transmitted at your own risk.</p>
	<h2>Virus warning</h2>
	<p>Umpire Tax Solutions does not represent that any information obtained from or through this site is free from computer viruses or other faults or defects. It is your responsibility to scan any such information for computer viruses. Umpire tax solutions will not be liable to you or to any other person for any loss or damage, however caused and whether by negligence or otherwise, which may result directly or indirectly from any such information. To the extent that any applicable law that cannot be excluded imposes any liability on us, that liability shall be limited to the cost of re-supplying that information.</p>
	<h2>Copyright</h2>
	<p>Copyright in this website rests with Umpire Tax Solutions Financial Advisors unless otherwise stated.</p>
	<p>Umpire Tax Solutions has made appropriate efforts to avoid errors or omissions in the content of this website. The user of this website acknowledges that some errors or omissions may be inherent in the content of the website, which cannot be prevented.</p>
	<p>Any mistake, error or discrepancy noted may be brought to our attention and appropriate efforts shall be undertaken to rectify the same.</p>
	<p>At any stage if the user is dissatisfied with any portion of the web site <a href="www.Umpiretaxsolutions.com" target="_blank">www.Umpiretaxsolutions.com</a>  or with any of these terms of use, the user's sole and exclusive remedy is to discontinue the use of the <a href="www.Umpiretaxsolutions.com" target="_blank">www.Umpiretaxsolutions.com</a> </p>

</div>     

	
