<style>
	.pad_head .panel-heading{
		color:#00c4fd;		
	}
</style>
<div class="headerLine testimonials_bg"></div>	
<!--<div class=""><img class="img-responsive" src="img/sl1.jpg"></div>-->
	<div class="container pad_head">
        <div class="row" style="padding:0 10px;">
			<div class="col-md-12">
				<div class="panel panel-default">
				  <div class="panel-heading text-center"> <h2>Happy Clients</h2></div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="panel panel-default">
				  <div class="panel-heading"><b>Priyanka Guha Roy, Maryland</b></div>
				  <div class="panel-body">
					Incredibly happy with the services and constant help we got from the company
				  </div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="panel panel-default">
				  <div class="panel-heading"><b>Sunil Venugopal, California</b></div>
				  <div class="panel-body">
					It was a wonderful experience!!!<br>Please do get in touch with me for filing my returns next year!!!
				  </div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="panel panel-default">
				  <div class="panel-heading"><b>Raj Maurya, California</b></div>
				  <div class="panel-body">
					<b>U</b>  - Ultimate team to engage with<br>
					<b>M</b>  - Max return guaranteed <br>
					<b>P</b>  - Professional in work <br>
					<b>I</b>  - Ideal approach <br>
					<b>R</b>  - Ready to work 24/7  <br>
					<b>E</b>  - Easy filing <br>
				  </div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="panel panel-default">
				  <div class="panel-heading">
						<b>Varalakshmi Naresh, Kentucky</b>
				  </div>
				  <div class="panel-body">
					I am glad  to write a feedback on your services.<br>
					Your returns was good when compared to other Tax consultancies and most of all is when ever I called you for questions, you picked the call and emailed me clarifications, that was really good. Keep up the good work. 
					<br>Thanks so much<br><br><br>
				  </div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="panel panel-default">
				  <div class="panel-heading"><b>Srini Battula, Minnesota</b></div>
				  <div class="panel-body">
					I am Thankful by filling through Umpire Tax Solutions.<br>
					I appreciate your prompt response, followup process and knowledge on IRS terms and conditions.
				  </div>
				</div>
			</div>
			
        </div>
	</div>
