 <div class="headerLine testimonials_bg"></div>	
<!--<div class=""><img class="img-responsive" src="img/sl1.jpg"></div>-->
	<div class="container">
        <div class="row" style="padding:0 10px;">
			<div class="col-md-12">
				<div class="panel panel-default">
				  <div class="panel-heading text-center"> <h3>Testimonials</h3></div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="panel panel-default">
				  <div class="panel-heading"><b>Priyanka Guha Roy, Maryland</b></div>
				  <div class="panel-body">
					Incredibly happy with the services and constant help we got from the company
				  </div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="panel panel-default">
				  <div class="panel-heading"><b>Sunil Venugopal, California</b></div>
				  <div class="panel-body">
					It was a wonderful experience!!!<br>Please do get in touch with me for filing my returns next year!!!
				  </div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="panel panel-default">
				  <div class="panel-heading"><b>Raj Maurya ,California</b></div>
				  <div class="panel-body">
					U - Ultimate team to engage with<br>
					M - Max return guaranteed <br>
					P - Professional in work <br>
					I - Ideal approach <br>
					R - Ready to work 24/7  <br>
					E - Easy filing <br>
				  </div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="panel panel-default">
				  <div class="panel-heading">
						<b>Varalakshmi Naresh, Kentucky</b>
				  </div>
				  <div class="panel-body">
					I am glad  to write a feedback on your services.<br>
					Your returns was good when compared to other Tax consultancies and most of all is when ever I called you for questions, you picked the call or emailed me clarifications, that was really good. Keep up the good work. Thanks so much<br><br><br>
				  </div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="panel panel-default">
				  <div class="panel-heading"><b>Srini Battula ,Minnesota</b></div>
				  <div class="panel-body">
					I am Thankful by filling through Umpire Tax Solutions.<br>
					I appreciate their prompt response,followup process and knowledge on IRS terms and conditions
				  </div>
				</div>
			</div>
			
        </div>
	</div>
