<?php
$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
$baseUrl = $header->headerarray['baseUrl'];
$basePath = $header->headerarray['basePath'];
?>
<link rel="stylesheet" href="<?php echo $basePath; ?>/css/bikeseva-all.css">
	<body class="hold-transition login-page">
		<div class="login-box">
			<div class="login-logo">
				<a href="#"><b><img class="logo1" src="<?php echo $basePath; ?>/img/logo.png"></b> Admin</a>
			</div>
			<div class="login-box-body" id="logDiv">
			<!--	<p class="login-box-msg">Sign in</p>-->
				<form id="adminLogin" name="adminLogin" method="POST" data-fv-message="This value is not valid"
								  data-fv-icon-valid="glyphicon glyphicon-ok"
								  data-fv-icon-invalid="glyphicon glyphicon-remove"
								  data-fv-icon-validating="glyphicon glyphicon-refresh">
					<div class="form-group has-feedback">
						<input type="email" class="form-control" name="u_email" id="u_email" placeholder="Email" required 
						data-fv-regexp="true" data-fv-regexp-regexp="^[_a-z0-9]+(\.[_a-z0-9]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$"  data-fv-regexp-message="The input is not a valid email address"/>
						<span class="glyphicon glyphicon-lock form-control-feedback"/>
						<span class="glyphicon glyphicon-envelope form-control-feedback"></span>
					</div>
					<div class="form-group has-feedback">
						<input type="password" class="form-control" name="u_password" id="u_password" placeholder="Password" required data-fv-notempty-message="The password is required"/>
						<span class="glyphicon glyphicon-lock form-control-feedback"></span>
					</div>
					<div class="row">								
						<div class="col-xs-4">
							<button type="submit" onClick="loginBtnV('adminLogin');" id="aLoginBtn"  name="aLoginBtn" class="btn btn-primary btn-block btn-flat">Login</button>
						</div><!-- /.col -->
					</div>
				</form>	
				<span id="errorMsg" style="color:red"></span>			
			</div><br/><br/>			
		</div><!-- /.login-box -->	
		<script type="text/javascript">
			$(document).ready(function() {
				$('#adminLogin').formValidation();
			});	
			$('#u_password').keypress(function (e) {
				var key = e.which;
				if(key == 13){
					loginBtnV('adminLogin');
				}
			}); 
		</script>
